In [2]:
import pandas as pd

In [3]:
data_with_description=pd.read_csv(r"C:\Users\user\Downloads\Projet ML\Model2 textvectorclassificator(countvectorizer)\Dataset2\IMDb movies.csv")

C:\Users\user\AppData\Local\Temp\ipykernel_12184\1665690020.py:1: DtypeWarning: Columns (3) have mixed types. Specify dtype option on import or set low_memory=False.
  data_with_description=pd.read_csv(r"C:\Users\user\Downloads\Projet ML\Model2 textvectorclassificator(countvectorizer)\Dataset2\IMDb movies.csv")

In [4]:
data_with_description

,imdb_title_id,title,original_title,year,date_published,genre,duration,country,language,director,...,actors,description,avg_vote,votes,budget,usa_gross_income,worlwide_gross_income,metascore,reviews_from_users,reviews_from_critics
0,tt0000009,Miss Jerry,Miss Jerry,1894,1894-10-09,Romance,45,USA,NaN,Alexander Black,...,"Blanche Bayliss, William Courtenay, Chauncey D...",The adventures of a female reporter in the 1890s.,5.9,154,NaN,NaN,NaN,NaN,1.0,2.0
1,tt0000574,The Story of the Kelly Gang,The Story of the Kelly Gang,1906,1906-12-26,"Biography, Crime, Drama",70,Australia,NaN,Charles Tait,...,"Elizabeth Tait, John Tait, Norman Campbell, Be...",True story of notorious Australian outlaw Ned ...,6.1,589,$ 2250,NaN,NaN,NaN,7.0,7.0
2,tt0001892,Den sorte drøm,Den sorte drøm,1911,1911-08-19,Drama,53,"Germany, Denmark",NaN,Urban Gad,...,"Asta Nielsen, Valdemar Psilander, Gunnar Helse...",Two men of high rank are both wooing the beaut...,5.8,188,NaN,NaN,NaN,NaN,5.0,2.0
3,tt0002101,Cleopatra,Cleopatra,1912,1912-11-13,"Drama, History",100,USA,English,Charles L. Gaskill,...,"Helen Gardner, Pearl Sindelar, Miss Fielding, ...",The fabled queen of Egypt's affair with Roman ...,5.2,446,$ 45000,NaN,NaN,NaN,25.0,3.0
4,tt0002130,L'Inferno,L'Inferno,1911,1911-03-06,"Adventure, Drama, Fantasy",68,Italy,Italian,"Francesco Bertolini, Adolfo Padovan",...,"Salvatore Papa, Arturo Pirovano, Giuseppe de L...",Loosely adapted from Dante's Divine Comedy and...,7.0,2237,NaN,NaN,NaN,NaN,31.0,14.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
85850,tt9908390,Le lion,Le lion,2020,2020-01-29,Comedy,95,"France, Belgium",French,Ludovic Colbeau-Justin,...,"Dany Boon, Philippe Katerine, Anne Serra, Samu...",A psychiatric hospital patient pretends to be ...,5.3,398,NaN,NaN,$ 3507171,NaN,NaN,4.0
85851,tt9911196,De Beentjes van Sint-Hildegard,De Beentjes van Sint-Hildegard,2020,2020-02-13,"Comedy, Drama",103,Netherlands,"German, Dutch",Johan Nijenhuis,...,"Herman Finkers, Johanna ter Steege, Leonie ter...",A middle-aged veterinary surgeon believes his ...,7.7,724,NaN,NaN,$ 7299062,NaN,6.0,4.0
85852,tt9911774,Padmavyuhathile Abhimanyu,Padmavyuhathile Abhimanyu,2019,2019-03-08,Drama,130,India,Malayalam,Vineesh Aaradya,...,"Anoop Chandran, Indrans, Sona Nair, Simon Brit...",NaN,7.9,265,NaN,NaN,NaN,NaN,NaN,NaN
85853,tt9914286,Sokagin Çocuklari,Sokagin Çocuklari,2019,2019-03-15,"Drama, Family",98,Turkey,Turkish,Ahmet Faik Akinci,...,"Ahmet Faik Akinci, Belma Mamati, Metin Keçeci,...",NaN,6.4,194,NaN,NaN,$ 2833,NaN,NaN,NaN
85854,tt9914942,La vida sense la Sara Amat,La vida sense la Sara Amat,2019,2020-02-05,Drama,74,Spain,Catalan,Laura Jou,...,"Maria Morera Colomer, Biel Rossell Pelfort, Is...","Pep, a 13-year-old boy, is in love with a girl...",6.7,102,NaN,NaN,$ 59794,NaN,NaN,2.0

In [5]:
data_without_description=pd.read_pickle(r"C:\Users\user\Downloads\Projet ML\Model1(KNN)\Données nettoyées\fusion_final.pkl.gz")
data_without_description

,tconst,titleType,primaryTitle,originalTitle,startYear,runtimeMinutes,genres,French_Title,averageRating,numVotes,primaryName
0,tt0003883,movie,L'enfant de Paris (1913),L'enfant de Paris (1913),1913,124.0,"Crime,Drama",L'Enfant de Paris (1913),7.2,446.0,"Léonce Perret,Louis Leubas,Maurice Lagrenée,Ém..."
1,tt0006206,movie,Les vampires (1915),Les vampires (1915),1915,421.0,"Action,Adventure,Crime",Les vampires (1915),7.3,5398.0,"Stacia Napierkowska,Musidora,Édouard Mathé,Mar..."
2,tt0006864,movie,Intolerance (1916),Intolerance: Love's Struggle Throughout the Ag...,1916,163.0,"Drama,History",Intolérance (1916),7.7,16642.0,"Lillian Gish,Robert Harron,Mae Marsh,F.A. Turner"
3,tt0006886,movie,Judex (1916),Judex (1916),1916,300.0,"Adventure,Crime",Judex (1916),7.2,1117.0,"René Cresté,Musidora,René Poyen,Édouard Mathé"
4,tt0009968,movie,Broken Blossoms (1919),Broken Blossoms or The Yellow Man and the Girl...,1919,90.0,"Drama,Romance",Le lys brisé (1919),7.2,11014.0,"Norman Selby,Lillian Gish,Richard Barthelmess,..."
...,...,...,...,...,...,...,...,...,...,...,...
13089,tt9900782,movie,Kaithi (2019),Kaithi (2019),2019,145.0,"Action,Crime,Drama",Kaithi (2019),8.4,42096.0,"Karthi,Narain,Arjun Das,George Maryan"
13090,tt9904844,movie,Ott Tänak: The Movie (2019),Ott Tänak: The Movie (2019),2019,125.0,"Documentary,Sport",NaN,8.1,501.0,NaN
13091,tt9905462,movie,Pengalila (2019),Pengalila (2019),2019,111.0,Drama,NaN,7.6,680.0,NaN
13092,tt9911196,movie,The Marriage Escape (2020),De beentjes van Sint-Hildegard (2020),2020,103.0,"Comedy,Drama",De Beentjes van Sint-Hildegard (2020),7.4,3306.0,"Herman Finkers,Johanna ter Steege,Leonie ter B..."
13093,tt9911774,movie,Padmavyuhathile Abhimanyu (2019),Padmavyuhathile Abhimanyu (2019),2019,130.0,Drama,NaN,8.5,380.0,NaN

In [6]:
data_with_description = data_with_description.loc[:, ["imdb_title_id", "description"]]
data_with_description

      imdb_title_id                                        description
0         tt0000009  The adventures of a female reporter in the 1890s.
1         tt0000574  True story of notorious Australian outlaw Ned ...
2         tt0001892  Two men of high rank are both wooing the beaut...
3         tt0002101  The fabled queen of Egypt's affair with Roman ...
4         tt0002130  Loosely adapted from Dante's Divine Comedy and...
...             ...                                                ...
85850     tt9908390  A psychiatric hospital patient pretends to be ...
85851     tt9911196  A middle-aged veterinary surgeon believes his ...
85852     tt9911774                                                NaN
85853     tt9914286                                                NaN
85854     tt9914942  Pep, a 13-year-old boy, is in love with a girl...

[85855 rows x 2 columns]

In [7]:
fusion=pd.merge(data_with_description,data_without_description,left_on='imdb_title_id',right_on='tconst',how='right')

In [8]:
fusion

,imdb_title_id,description,tconst,titleType,primaryTitle,originalTitle,startYear,runtimeMinutes,genres,French_Title,averageRating,numVotes,primaryName
0,tt0003883,The young daughter of an army captain missing ...,tt0003883,movie,L'enfant de Paris (1913),L'enfant de Paris (1913),1913,124.0,"Crime,Drama",L'Enfant de Paris (1913),7.2,446.0,"Léonce Perret,Louis Leubas,Maurice Lagrenée,Ém..."
1,tt0006206,An intrepid reporter and his loyal friend batt...,tt0006206,movie,Les vampires (1915),Les vampires (1915),1915,421.0,"Action,Adventure,Crime",Les vampires (1915),7.3,5398.0,"Stacia Napierkowska,Musidora,Édouard Mathé,Mar..."
2,tt0006864,"The story of a poor young woman, separated by ...",tt0006864,movie,Intolerance (1916),Intolerance: Love's Struggle Throughout the Ag...,1916,163.0,"Drama,History",Intolérance (1916),7.7,16642.0,"Lillian Gish,Robert Harron,Mae Marsh,F.A. Turner"
3,tt0006886,A twelve part serial following the adventures ...,tt0006886,movie,Judex (1916),Judex (1916),1916,300.0,"Adventure,Crime",Judex (1916),7.2,1117.0,"René Cresté,Musidora,René Poyen,Édouard Mathé"
4,tt0009968,"A frail waif, abused by her brutal boxer fathe...",tt0009968,movie,Broken Blossoms (1919),Broken Blossoms or The Yellow Man and the Girl...,1919,90.0,"Drama,Romance",Le lys brisé (1919),7.2,11014.0,"Norman Selby,Lillian Gish,Richard Barthelmess,..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...
13089,tt9900782,A recently released prisoner becomes involved ...,tt9900782,movie,Kaithi (2019),Kaithi (2019),2019,145.0,"Action,Crime,Drama",Kaithi (2019),8.4,42096.0,"Karthi,Narain,Arjun Das,George Maryan"
13090,NaN,NaN,tt9904844,movie,Ott Tänak: The Movie (2019),Ott Tänak: The Movie (2019),2019,125.0,"Documentary,Sport",NaN,8.1,501.0,NaN
13091,tt9905462,An unusual bond between a sixty year old Dalit...,tt9905462,movie,Pengalila (2019),Pengalila (2019),2019,111.0,Drama,NaN,7.6,680.0,NaN
13092,tt9911196,A middle-aged veterinary surgeon believes his ...,tt9911196,movie,The Marriage Escape (2020),De beentjes van Sint-Hildegard (2020),2020,103.0,"Comedy,Drama",De Beentjes van Sint-Hildegard (2020),7.4,3306.0,"Herman Finkers,Johanna ter Steege,Leonie ter B..."
13093,tt9911774,NaN,tt9911774,movie,Padmavyuhathile Abhimanyu (2019),Padmavyuhathile Abhimanyu (2019),2019,130.0,Drama,NaN,8.5,380.0,NaN

In [9]:
fusion=fusion.drop('imdb_title_id',axis=1)
fusion

,description,tconst,titleType,primaryTitle,originalTitle,startYear,runtimeMinutes,genres,French_Title,averageRating,numVotes,primaryName
0,The young daughter of an army captain missing ...,tt0003883,movie,L'enfant de Paris (1913),L'enfant de Paris (1913),1913,124.0,"Crime,Drama",L'Enfant de Paris (1913),7.2,446.0,"Léonce Perret,Louis Leubas,Maurice Lagrenée,Ém..."
1,An intrepid reporter and his loyal friend batt...,tt0006206,movie,Les vampires (1915),Les vampires (1915),1915,421.0,"Action,Adventure,Crime",Les vampires (1915),7.3,5398.0,"Stacia Napierkowska,Musidora,Édouard Mathé,Mar..."
2,"The story of a poor young woman, separated by ...",tt0006864,movie,Intolerance (1916),Intolerance: Love's Struggle Throughout the Ag...,1916,163.0,"Drama,History",Intolérance (1916),7.7,16642.0,"Lillian Gish,Robert Harron,Mae Marsh,F.A. Turner"
3,A twelve part serial following the adventures ...,tt0006886,movie,Judex (1916),Judex (1916),1916,300.0,"Adventure,Crime",Judex (1916),7.2,1117.0,"René Cresté,Musidora,René Poyen,Édouard Mathé"
4,"A frail waif, abused by her brutal boxer fathe...",tt0009968,movie,Broken Blossoms (1919),Broken Blossoms or The Yellow Man and the Girl...,1919,90.0,"Drama,Romance",Le lys brisé (1919),7.2,11014.0,"Norman Selby,Lillian Gish,Richard Barthelmess,..."
...,...,...,...,...,...,...,...,...,...,...,...,...
13089,A recently released prisoner becomes involved ...,tt9900782,movie,Kaithi (2019),Kaithi (2019),2019,145.0,"Action,Crime,Drama",Kaithi (2019),8.4,42096.0,"Karthi,Narain,Arjun Das,George Maryan"
13090,NaN,tt9904844,movie,Ott Tänak: The Movie (2019),Ott Tänak: The Movie (2019),2019,125.0,"Documentary,Sport",NaN,8.1,501.0,NaN
13091,An unusual bond between a sixty year old Dalit...,tt9905462,movie,Pengalila (2019),Pengalila (2019),2019,111.0,Drama,NaN,7.6,680.0,NaN
13092,A middle-aged veterinary surgeon believes his ...,tt9911196,movie,The Marriage Escape (2020),De beentjes van Sint-Hildegard (2020),2020,103.0,"Comedy,Drama",De Beentjes van Sint-Hildegard (2020),7.4,3306.0,"Herman Finkers,Johanna ter Steege,Leonie ter B..."
13093,NaN,tt9911774,movie,Padmavyuhathile Abhimanyu (2019),Padmavyuhathile Abhimanyu (2019),2019,130.0,Drama,NaN,8.5,380.0,NaN

In [10]:
new_order = ['tconst', 'primaryTitle', 'originalTitle', 'startYear', 'runtimeMinutes', 'genres', 'French_Title',
             'averageRating', 'numVotes', 'description', 'primaryName']
fusion=fusion.reindex(columns=new_order)

In [11]:
fusion

,tconst,primaryTitle,originalTitle,startYear,runtimeMinutes,genres,French_Title,averageRating,numVotes,description,primaryName
0,tt0003883,L'enfant de Paris (1913),L'enfant de Paris (1913),1913,124.0,"Crime,Drama",L'Enfant de Paris (1913),7.2,446.0,The young daughter of an army captain missing ...,"Léonce Perret,Louis Leubas,Maurice Lagrenée,Ém..."
1,tt0006206,Les vampires (1915),Les vampires (1915),1915,421.0,"Action,Adventure,Crime",Les vampires (1915),7.3,5398.0,An intrepid reporter and his loyal friend batt...,"Stacia Napierkowska,Musidora,Édouard Mathé,Mar..."
2,tt0006864,Intolerance (1916),Intolerance: Love's Struggle Throughout the Ag...,1916,163.0,"Drama,History",Intolérance (1916),7.7,16642.0,"The story of a poor young woman, separated by ...","Lillian Gish,Robert Harron,Mae Marsh,F.A. Turner"
3,tt0006886,Judex (1916),Judex (1916),1916,300.0,"Adventure,Crime",Judex (1916),7.2,1117.0,A twelve part serial following the adventures ...,"René Cresté,Musidora,René Poyen,Édouard Mathé"
4,tt0009968,Broken Blossoms (1919),Broken Blossoms or The Yellow Man and the Girl...,1919,90.0,"Drama,Romance",Le lys brisé (1919),7.2,11014.0,"A frail waif, abused by her brutal boxer fathe...","Norman Selby,Lillian Gish,Richard Barthelmess,..."
...,...,...,...,...,...,...,...,...,...,...,...
13089,tt9900782,Kaithi (2019),Kaithi (2019),2019,145.0,"Action,Crime,Drama",Kaithi (2019),8.4,42096.0,A recently released prisoner becomes involved ...,"Karthi,Narain,Arjun Das,George Maryan"
13090,tt9904844,Ott Tänak: The Movie (2019),Ott Tänak: The Movie (2019),2019,125.0,"Documentary,Sport",NaN,8.1,501.0,NaN,NaN
13091,tt9905462,Pengalila (2019),Pengalila (2019),2019,111.0,Drama,NaN,7.6,680.0,An unusual bond between a sixty year old Dalit...,NaN
13092,tt9911196,The Marriage Escape (2020),De beentjes van Sint-Hildegard (2020),2020,103.0,"Comedy,Drama",De Beentjes van Sint-Hildegard (2020),7.4,3306.0,A middle-aged veterinary surgeon believes his ...,"Herman Finkers,Johanna ter Steege,Leonie ter B..."
13093,tt9911774,Padmavyuhathile Abhimanyu (2019),Padmavyuhathile Abhimanyu (2019),2019,130.0,Drama,NaN,8.5,380.0,NaN,NaN

In [12]:
#Supprimer les lignes qui ont une valeur manquante dans la colonne description
fusion=fusion.dropna(subset=['description'])

In [13]:
fusion.isnull().sum()

tconst               0
primaryTitle         0
originalTitle        0
startYear            0
runtimeMinutes       0
genres               0
French_Title      3229
averageRating        0
numVotes             0
description          0
primaryName         76
dtype: int64

In [14]:
#Remplacer les valeurs manquantes dans la colonne description par une chaine vide
fusion['primaryName']=fusion['primaryName'].fillna("")

C:\Users\user\AppData\Local\Temp\ipykernel_12184\2799613885.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  fusion['primaryName']=fusion['primaryName'].fillna("")

In [15]:
fusion.to_csv(r"C:\Users\user\Downloads\Projet ML\Model2 textvectorclassificator(countvectorizer)\Dataset2\fusion.csv")

In [16]:
fusion

,tconst,primaryTitle,originalTitle,startYear,runtimeMinutes,genres,French_Title,averageRating,numVotes,description,primaryName
0,tt0003883,L'enfant de Paris (1913),L'enfant de Paris (1913),1913,124.0,"Crime,Drama",L'Enfant de Paris (1913),7.2,446.0,The young daughter of an army captain missing ...,"Léonce Perret,Louis Leubas,Maurice Lagrenée,Ém..."
1,tt0006206,Les vampires (1915),Les vampires (1915),1915,421.0,"Action,Adventure,Crime",Les vampires (1915),7.3,5398.0,An intrepid reporter and his loyal friend batt...,"Stacia Napierkowska,Musidora,Édouard Mathé,Mar..."
2,tt0006864,Intolerance (1916),Intolerance: Love's Struggle Throughout the Ag...,1916,163.0,"Drama,History",Intolérance (1916),7.7,16642.0,"The story of a poor young woman, separated by ...","Lillian Gish,Robert Harron,Mae Marsh,F.A. Turner"
3,tt0006886,Judex (1916),Judex (1916),1916,300.0,"Adventure,Crime",Judex (1916),7.2,1117.0,A twelve part serial following the adventures ...,"René Cresté,Musidora,René Poyen,Édouard Mathé"
4,tt0009968,Broken Blossoms (1919),Broken Blossoms or The Yellow Man and the Girl...,1919,90.0,"Drama,Romance",Le lys brisé (1919),7.2,11014.0,"A frail waif, abused by her brutal boxer fathe...","Norman Selby,Lillian Gish,Richard Barthelmess,..."
...,...,...,...,...,...,...,...,...,...,...,...
13086,tt9892338,Dare to Surf (2019),No Dorai (2019),2019,150.0,Drama,NaN,7.2,705.0,"In a small beach town in Bangladesh, fearless ...","Sunerah Binte Kamal,Sariful Razz,Josefine Lind..."
13087,tt9894394,Upin & Ipin: Keris Siamang Tunggal (2019),Upin & Ipin: Keris siamang tunggal (2019),2019,100.0,"Adventure,Animation,Comedy",NaN,7.3,829.0,"Upin, Ipin and their friends come across a mys...","Asyiela Putri Bt Azhar,Mohd Amir Asyraf Bin Mo..."
13089,tt9900782,Kaithi (2019),Kaithi (2019),2019,145.0,"Action,Crime,Drama",Kaithi (2019),8.4,42096.0,A recently released prisoner becomes involved ...,"Karthi,Narain,Arjun Das,George Maryan"
13091,tt9905462,Pengalila (2019),Pengalila (2019),2019,111.0,Drama,NaN,7.6,680.0,An unusual bond between a sixty year old Dalit...,
13092,tt9911196,The Marriage Escape (2020),De beentjes van Sint-Hildegard (2020),2020,103.0,"Comedy,Drama",De Beentjes van Sint-Hildegard (2020),7.4,3306.0,A middle-aged veterinary surgeon believes his ...,"Herman Finkers,Johanna ter Steege,Leonie ter B..."

In [17]:
fusion.isnull().sum()

tconst               0
primaryTitle         0
originalTitle        0
startYear            0
runtimeMinutes       0
genres               0
French_Title      3229
averageRating        0
numVotes             0
description          0
primaryName          0
dtype: int64

In [18]:
fusion.describe()

         startYear  runtimeMinutes  averageRating      numVotes
count  9244.000000     9244.000000    9244.000000  9.244000e+03
mean   1988.616724      118.872025       7.575995  5.966998e+04
std      24.298936       33.870018       0.357852  1.830193e+05
min    1913.000000       81.000000       7.200000  3.190000e+02
25%    1970.000000       99.000000       7.300000  1.269000e+03
50%    1994.000000      112.000000       7.500000  4.527500e+03
75%    2010.000000      132.000000       7.800000  2.287600e+04
max    2020.000000      808.000000       9.400000  2.870332e+06

In [19]:
fusion.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9244 entries, 0 to 13092
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   tconst          9244 non-null   object
 1   primaryTitle    9244 non-null   object
 2   originalTitle   9244 non-null   object
 3   startYear       9244 non-null   int64
 4   runtimeMinutes  9244 non-null   float64
 5   genres          9244 non-null   object
 6   French_Title    6015 non-null   object
 7   averageRating   9244 non-null   float64
 8   numVotes        9244 non-null   float64
 9   description     9244 non-null   object
 10  primaryName     9244 non-null   object
dtypes: float64(3), int64(1), object(7)
memory usage: 866.6+ KB

In [20]:
fusion['tconst'].duplicated().sum()

657

In [21]:
data_ml_modele2 = fusion.drop_duplicates(subset = "tconst")

In [22]:
# Réindexer le DataFrame après la suppression des doublons
data_ml_modele2 = data_ml_modele2.reset_index(drop=True)

In [23]:
data_ml_modele2

,tconst,primaryTitle,originalTitle,startYear,runtimeMinutes,genres,French_Title,averageRating,numVotes,description,primaryName
0,tt0003883,L'enfant de Paris (1913),L'enfant de Paris (1913),1913,124.0,"Crime,Drama",L'Enfant de Paris (1913),7.2,446.0,The young daughter of an army captain missing ...,"Léonce Perret,Louis Leubas,Maurice Lagrenée,Ém..."
1,tt0006206,Les vampires (1915),Les vampires (1915),1915,421.0,"Action,Adventure,Crime",Les vampires (1915),7.3,5398.0,An intrepid reporter and his loyal friend batt...,"Stacia Napierkowska,Musidora,Édouard Mathé,Mar..."
2,tt0006864,Intolerance (1916),Intolerance: Love's Struggle Throughout the Ag...,1916,163.0,"Drama,History",Intolérance (1916),7.7,16642.0,"The story of a poor young woman, separated by ...","Lillian Gish,Robert Harron,Mae Marsh,F.A. Turner"
3,tt0006886,Judex (1916),Judex (1916),1916,300.0,"Adventure,Crime",Judex (1916),7.2,1117.0,A twelve part serial following the adventures ...,"René Cresté,Musidora,René Poyen,Édouard Mathé"
4,tt0009968,Broken Blossoms (1919),Broken Blossoms or The Yellow Man and the Girl...,1919,90.0,"Drama,Romance",Le lys brisé (1919),7.2,11014.0,"A frail waif, abused by her brutal boxer fathe...","Norman Selby,Lillian Gish,Richard Barthelmess,..."
...,...,...,...,...,...,...,...,...,...,...,...
8582,tt9892338,Dare to Surf (2019),No Dorai (2019),2019,150.0,Drama,NaN,7.2,705.0,"In a small beach town in Bangladesh, fearless ...","Sunerah Binte Kamal,Sariful Razz,Josefine Lind..."
8583,tt9894394,Upin & Ipin: Keris Siamang Tunggal (2019),Upin & Ipin: Keris siamang tunggal (2019),2019,100.0,"Adventure,Animation,Comedy",NaN,7.3,829.0,"Upin, Ipin and their friends come across a mys...","Asyiela Putri Bt Azhar,Mohd Amir Asyraf Bin Mo..."
8584,tt9900782,Kaithi (2019),Kaithi (2019),2019,145.0,"Action,Crime,Drama",Kaithi (2019),8.4,42096.0,A recently released prisoner becomes involved ...,"Karthi,Narain,Arjun Das,George Maryan"
8585,tt9905462,Pengalila (2019),Pengalila (2019),2019,111.0,Drama,NaN,7.6,680.0,An unusual bond between a sixty year old Dalit...,
8586,tt9911196,The Marriage Escape (2020),De beentjes van Sint-Hildegard (2020),2020,103.0,"Comedy,Drama",De Beentjes van Sint-Hildegard (2020),7.4,3306.0,A middle-aged veterinary surgeon believes his ...,"Herman Finkers,Johanna ter Steege,Leonie ter B..."

In [24]:
data_ml_modele2.to_pickle(r'C:\Users\user\Downloads\Projet ML\Model2 textvectorclassificator(countvectorizer)\Dataset2\data_ml_modele2.pkl.gz')

In [25]:
data_ml_modele2

,tconst,primaryTitle,originalTitle,startYear,runtimeMinutes,genres,French_Title,averageRating,numVotes,description,primaryName
0,tt0003883,L'enfant de Paris (1913),L'enfant de Paris (1913),1913,124.0,"Crime,Drama",L'Enfant de Paris (1913),7.2,446.0,The young daughter of an army captain missing ...,"Léonce Perret,Louis Leubas,Maurice Lagrenée,Ém..."
1,tt0006206,Les vampires (1915),Les vampires (1915),1915,421.0,"Action,Adventure,Crime",Les vampires (1915),7.3,5398.0,An intrepid reporter and his loyal friend batt...,"Stacia Napierkowska,Musidora,Édouard Mathé,Mar..."
2,tt0006864,Intolerance (1916),Intolerance: Love's Struggle Throughout the Ag...,1916,163.0,"Drama,History",Intolérance (1916),7.7,16642.0,"The story of a poor young woman, separated by ...","Lillian Gish,Robert Harron,Mae Marsh,F.A. Turner"
3,tt0006886,Judex (1916),Judex (1916),1916,300.0,"Adventure,Crime",Judex (1916),7.2,1117.0,A twelve part serial following the adventures ...,"René Cresté,Musidora,René Poyen,Édouard Mathé"
4,tt0009968,Broken Blossoms (1919),Broken Blossoms or The Yellow Man and the Girl...,1919,90.0,"Drama,Romance",Le lys brisé (1919),7.2,11014.0,"A frail waif, abused by her brutal boxer fathe...","Norman Selby,Lillian Gish,Richard Barthelmess,..."
...,...,...,...,...,...,...,...,...,...,...,...
8582,tt9892338,Dare to Surf (2019),No Dorai (2019),2019,150.0,Drama,NaN,7.2,705.0,"In a small beach town in Bangladesh, fearless ...","Sunerah Binte Kamal,Sariful Razz,Josefine Lind..."
8583,tt9894394,Upin & Ipin: Keris Siamang Tunggal (2019),Upin & Ipin: Keris siamang tunggal (2019),2019,100.0,"Adventure,Animation,Comedy",NaN,7.3,829.0,"Upin, Ipin and their friends come across a mys...","Asyiela Putri Bt Azhar,Mohd Amir Asyraf Bin Mo..."
8584,tt9900782,Kaithi (2019),Kaithi (2019),2019,145.0,"Action,Crime,Drama",Kaithi (2019),8.4,42096.0,A recently released prisoner becomes involved ...,"Karthi,Narain,Arjun Das,George Maryan"
8585,tt9905462,Pengalila (2019),Pengalila (2019),2019,111.0,Drama,NaN,7.6,680.0,An unusual bond between a sixty year old Dalit...,
8586,tt9911196,The Marriage Escape (2020),De beentjes van Sint-Hildegard (2020),2020,103.0,"Comedy,Drama",De Beentjes van Sint-Hildegard (2020),7.4,3306.0,A middle-aged veterinary surgeon believes his ...,"Herman Finkers,Johanna ter Steege,Leonie ter B..."

In [26]:
#Affichage de la description de la premiere ligne
data_ml_modele2.iloc[0]['description']

'The young daughter of an army captain missing in action runs away from school and is kidnapped by Parisian lowlifes. When the kidnapper flees to Nice with the child, the kind-hearted employee of one of his accomplices sets off in pursuit.'

In [27]:
#Diviser chaque mot de la description par la virgule
data_ml_modele2['description']=data_ml_modele2['description'].apply(lambda x:x.split())
data_ml_modele2.head()

,tconst,primaryTitle,originalTitle,startYear,runtimeMinutes,genres,French_Title,averageRating,numVotes,description,primaryName
0,tt0003883,L'enfant de Paris (1913),L'enfant de Paris (1913),1913,124.0,"Crime,Drama",L'Enfant de Paris (1913),7.2,446.0,"[The, young, daughter, of, an, army, captain, ...","Léonce Perret,Louis Leubas,Maurice Lagrenée,Ém..."
1,tt0006206,Les vampires (1915),Les vampires (1915),1915,421.0,"Action,Adventure,Crime",Les vampires (1915),7.3,5398.0,"[An, intrepid, reporter, and, his, loyal, frie...","Stacia Napierkowska,Musidora,Édouard Mathé,Mar..."
2,tt0006864,Intolerance (1916),Intolerance: Love's Struggle Throughout the Ag...,1916,163.0,"Drama,History",Intolérance (1916),7.7,16642.0,"[The, story, of, a, poor, young, woman,, separ...","Lillian Gish,Robert Harron,Mae Marsh,F.A. Turner"
3,tt0006886,Judex (1916),Judex (1916),1916,300.0,"Adventure,Crime",Judex (1916),7.2,1117.0,"[A, twelve, part, serial, following, the, adve...","René Cresté,Musidora,René Poyen,Édouard Mathé"
4,tt0009968,Broken Blossoms (1919),Broken Blossoms or The Yellow Man and the Girl...,1919,90.0,"Drama,Romance",Le lys brisé (1919),7.2,11014.0,"[A, frail, waif,, abused, by, her, brutal, box...","Norman Selby,Lillian Gish,Richard Barthelmess,..."

In [28]:
#Mettre les colonnes genres et primaryName entre []
data_ml_modele2.iloc[0]['description']

['The',
 'young',
 'daughter',
 'of',
 'an',
 'army',
 'captain',
 'missing',
 'in',
 'action',
 'runs',
 'away',
 'from',
 'school',
 'and',
 'is',
 'kidnapped',
 'by',
 'Parisian',
 'lowlifes.',
 'When',
 'the',
 'kidnapper',
 'flees',
 'to',
 'Nice',
 'with',
 'the',
 'child,',
 'the',
 'kind-hearted',
 'employee',
 'of',
 'one',
 'of',
 'his',
 'accomplices',
 'sets',
 'off',
 'in',
 'pursuit.']

In [29]:
#Remove space
def remove_space(text):
    if isinstance(text, str):  # Vérifier si le texte est une chaîne de caractères
        return text.replace(" ", "")
    else:
        return text  # Retourner la valeur sans modification si ce n'est pas une chaîne de caractères

In [30]:
data_ml_modele2['primaryName'] = data_ml_modele2['primaryName'].apply(remove_space)
data_ml_modele2['genres'] = data_ml_modele2['genres'].apply(remove_space)

In [31]:
data_ml_modele2

,tconst,primaryTitle,originalTitle,startYear,runtimeMinutes,genres,French_Title,averageRating,numVotes,description,primaryName
0,tt0003883,L'enfant de Paris (1913),L'enfant de Paris (1913),1913,124.0,"Crime,Drama",L'Enfant de Paris (1913),7.2,446.0,"[The, young, daughter, of, an, army, captain, ...","LéoncePerret,LouisLeubas,MauriceLagrenée,Émile..."
1,tt0006206,Les vampires (1915),Les vampires (1915),1915,421.0,"Action,Adventure,Crime",Les vampires (1915),7.3,5398.0,"[An, intrepid, reporter, and, his, loyal, frie...","StaciaNapierkowska,Musidora,ÉdouardMathé,Marce..."
2,tt0006864,Intolerance (1916),Intolerance: Love's Struggle Throughout the Ag...,1916,163.0,"Drama,History",Intolérance (1916),7.7,16642.0,"[The, story, of, a, poor, young, woman,, separ...","LillianGish,RobertHarron,MaeMarsh,F.A.Turner"
3,tt0006886,Judex (1916),Judex (1916),1916,300.0,"Adventure,Crime",Judex (1916),7.2,1117.0,"[A, twelve, part, serial, following, the, adve...","RenéCresté,Musidora,RenéPoyen,ÉdouardMathé"
4,tt0009968,Broken Blossoms (1919),Broken Blossoms or The Yellow Man and the Girl...,1919,90.0,"Drama,Romance",Le lys brisé (1919),7.2,11014.0,"[A, frail, waif,, abused, by, her, brutal, box...","NormanSelby,LillianGish,RichardBarthelmess,Don..."
...,...,...,...,...,...,...,...,...,...,...,...
8582,tt9892338,Dare to Surf (2019),No Dorai (2019),2019,150.0,Drama,NaN,7.2,705.0,"[In, a, small, beach, town, in, Bangladesh,, f...","SunerahBinteKamal,SarifulRazz,JosefineLindegaa..."
8583,tt9894394,Upin & Ipin: Keris Siamang Tunggal (2019),Upin & Ipin: Keris siamang tunggal (2019),2019,100.0,"Adventure,Animation,Comedy",NaN,7.3,829.0,"[Upin,, Ipin, and, their, friends, come, acros...","AsyielaPutriBtAzhar,MohdAmirAsyrafBinMohdNoorR..."
8584,tt9900782,Kaithi (2019),Kaithi (2019),2019,145.0,"Action,Crime,Drama",Kaithi (2019),8.4,42096.0,"[A, recently, released, prisoner, becomes, inv...","Karthi,Narain,ArjunDas,GeorgeMaryan"
8585,tt9905462,Pengalila (2019),Pengalila (2019),2019,111.0,Drama,NaN,7.6,680.0,"[An, unusual, bond, between, a, sixty, year, o...",
8586,tt9911196,The Marriage Escape (2020),De beentjes van Sint-Hildegard (2020),2020,103.0,"Comedy,Drama",De Beentjes van Sint-Hildegard (2020),7.4,3306.0,"[A, middle-aged, veterinary, surgeon, believes...","HermanFinkers,JohannaterSteege,LeonieterBraak,..."

In [32]:
#
data_ml_modele2['description'] = data_ml_modele2['description'].apply(lambda x: " ".join(x))

In [33]:
data_ml_modele2

,tconst,primaryTitle,originalTitle,startYear,runtimeMinutes,genres,French_Title,averageRating,numVotes,description,primaryName
0,tt0003883,L'enfant de Paris (1913),L'enfant de Paris (1913),1913,124.0,"Crime,Drama",L'Enfant de Paris (1913),7.2,446.0,The young daughter of an army captain missing ...,"LéoncePerret,LouisLeubas,MauriceLagrenée,Émile..."
1,tt0006206,Les vampires (1915),Les vampires (1915),1915,421.0,"Action,Adventure,Crime",Les vampires (1915),7.3,5398.0,An intrepid reporter and his loyal friend batt...,"StaciaNapierkowska,Musidora,ÉdouardMathé,Marce..."
2,tt0006864,Intolerance (1916),Intolerance: Love's Struggle Throughout the Ag...,1916,163.0,"Drama,History",Intolérance (1916),7.7,16642.0,"The story of a poor young woman, separated by ...","LillianGish,RobertHarron,MaeMarsh,F.A.Turner"
3,tt0006886,Judex (1916),Judex (1916),1916,300.0,"Adventure,Crime",Judex (1916),7.2,1117.0,A twelve part serial following the adventures ...,"RenéCresté,Musidora,RenéPoyen,ÉdouardMathé"
4,tt0009968,Broken Blossoms (1919),Broken Blossoms or The Yellow Man and the Girl...,1919,90.0,"Drama,Romance",Le lys brisé (1919),7.2,11014.0,"A frail waif, abused by her brutal boxer fathe...","NormanSelby,LillianGish,RichardBarthelmess,Don..."
...,...,...,...,...,...,...,...,...,...,...,...
8582,tt9892338,Dare to Surf (2019),No Dorai (2019),2019,150.0,Drama,NaN,7.2,705.0,"In a small beach town in Bangladesh, fearless ...","SunerahBinteKamal,SarifulRazz,JosefineLindegaa..."
8583,tt9894394,Upin & Ipin: Keris Siamang Tunggal (2019),Upin & Ipin: Keris siamang tunggal (2019),2019,100.0,"Adventure,Animation,Comedy",NaN,7.3,829.0,"Upin, Ipin and their friends come across a mys...","AsyielaPutriBtAzhar,MohdAmirAsyrafBinMohdNoorR..."
8584,tt9900782,Kaithi (2019),Kaithi (2019),2019,145.0,"Action,Crime,Drama",Kaithi (2019),8.4,42096.0,A recently released prisoner becomes involved ...,"Karthi,Narain,ArjunDas,GeorgeMaryan"
8585,tt9905462,Pengalila (2019),Pengalila (2019),2019,111.0,Drama,NaN,7.6,680.0,An unusual bond between a sixty year old Dalit...,
8586,tt9911196,The Marriage Escape (2020),De beentjes van Sint-Hildegard (2020),2020,103.0,"Comedy,Drama",De Beentjes van Sint-Hildegard (2020),7.4,3306.0,A middle-aged veterinary surgeon believes his ...,"HermanFinkers,JohannaterSteege,LeonieterBraak,..."

In [34]:
data_ml_modele2['genres'] = data_ml_modele2['genres'].str.replace(',', ' ')
data_ml_modele2['primaryName'] = data_ml_modele2['primaryName'].str.replace(',', ' ')
data_ml_modele2['runtimeMinutes'] = data_ml_modele2['runtimeMinutes'].astype(int)
data_ml_modele2['runtimeMinutes'] = data_ml_modele2['runtimeMinutes'].astype(str)
data_ml_modele2

,tconst,primaryTitle,originalTitle,startYear,runtimeMinutes,genres,French_Title,averageRating,numVotes,description,primaryName
0,tt0003883,L'enfant de Paris (1913),L'enfant de Paris (1913),1913,124,Crime Drama,L'Enfant de Paris (1913),7.2,446.0,The young daughter of an army captain missing ...,LéoncePerret LouisLeubas MauriceLagrenée Émile...
1,tt0006206,Les vampires (1915),Les vampires (1915),1915,421,Action Adventure Crime,Les vampires (1915),7.3,5398.0,An intrepid reporter and his loyal friend batt...,StaciaNapierkowska Musidora ÉdouardMathé Marce...
2,tt0006864,Intolerance (1916),Intolerance: Love's Struggle Throughout the Ag...,1916,163,Drama History,Intolérance (1916),7.7,16642.0,"The story of a poor young woman, separated by ...",LillianGish RobertHarron MaeMarsh F.A.Turner
3,tt0006886,Judex (1916),Judex (1916),1916,300,Adventure Crime,Judex (1916),7.2,1117.0,A twelve part serial following the adventures ...,RenéCresté Musidora RenéPoyen ÉdouardMathé
4,tt0009968,Broken Blossoms (1919),Broken Blossoms or The Yellow Man and the Girl...,1919,90,Drama Romance,Le lys brisé (1919),7.2,11014.0,"A frail waif, abused by her brutal boxer fathe...",NormanSelby LillianGish RichardBarthelmess Don...
...,...,...,...,...,...,...,...,...,...,...,...
8582,tt9892338,Dare to Surf (2019),No Dorai (2019),2019,150,Drama,NaN,7.2,705.0,"In a small beach town in Bangladesh, fearless ...",SunerahBinteKamal SarifulRazz JosefineLindegaa...
8583,tt9894394,Upin & Ipin: Keris Siamang Tunggal (2019),Upin & Ipin: Keris siamang tunggal (2019),2019,100,Adventure Animation Comedy,NaN,7.3,829.0,"Upin, Ipin and their friends come across a mys...",AsyielaPutriBtAzhar MohdAmirAsyrafBinMohdNoorR...
8584,tt9900782,Kaithi (2019),Kaithi (2019),2019,145,Action Crime Drama,Kaithi (2019),8.4,42096.0,A recently released prisoner becomes involved ...,Karthi Narain ArjunDas GeorgeMaryan
8585,tt9905462,Pengalila (2019),Pengalila (2019),2019,111,Drama,NaN,7.6,680.0,An unusual bond between a sixty year old Dalit...,
8586,tt9911196,The Marriage Escape (2020),De beentjes van Sint-Hildegard (2020),2020,103,Comedy Drama,De Beentjes van Sint-Hildegard (2020),7.4,3306.0,A middle-aged veterinary surgeon believes his ...,HermanFinkers JohannaterSteege LeonieterBraak ...

In [35]:
# Convertir  les colonnes en chaînes de caractères
data_ml_modele2['description'] = data_ml_modele2['description'].astype(str)
data_ml_modele2['genres'] = data_ml_modele2['genres'].astype(str)
data_ml_modele2['primaryName'] = data_ml_modele2['primaryName'].astype(str)
data_ml_modele2['runtimeMinutes'] = data_ml_modele2['runtimeMinutes'] + 'min'
data_ml_modele2['startYear']=data_ml_modele2['startYear'].astype(str)
# Appliquer la transformation pour créer la colonne 'tags'
data_ml_modele2['tags'] = data_ml_modele2.apply(lambda row: ' '.join(row['description'].split()) + ' ' + ' '.join(row['genres'].split(',')) + ' ' + ' '.join(row['primaryName'].split(',')) + ' ' + row['runtimeMinutes'] + ' ' + row['startYear'], axis=1)

In [36]:
data_ml_modele2

,tconst,primaryTitle,originalTitle,startYear,runtimeMinutes,genres,French_Title,averageRating,numVotes,description,primaryName,tags
0,tt0003883,L'enfant de Paris (1913),L'enfant de Paris (1913),1913,124min,Crime Drama,L'Enfant de Paris (1913),7.2,446.0,The young daughter of an army captain missing ...,LéoncePerret LouisLeubas MauriceLagrenée Émile...,The young daughter of an army captain missing ...
1,tt0006206,Les vampires (1915),Les vampires (1915),1915,421min,Action Adventure Crime,Les vampires (1915),7.3,5398.0,An intrepid reporter and his loyal friend batt...,StaciaNapierkowska Musidora ÉdouardMathé Marce...,An intrepid reporter and his loyal friend batt...
2,tt0006864,Intolerance (1916),Intolerance: Love's Struggle Throughout the Ag...,1916,163min,Drama History,Intolérance (1916),7.7,16642.0,"The story of a poor young woman, separated by ...",LillianGish RobertHarron MaeMarsh F.A.Turner,"The story of a poor young woman, separated by ..."
3,tt0006886,Judex (1916),Judex (1916),1916,300min,Adventure Crime,Judex (1916),7.2,1117.0,A twelve part serial following the adventures ...,RenéCresté Musidora RenéPoyen ÉdouardMathé,A twelve part serial following the adventures ...
4,tt0009968,Broken Blossoms (1919),Broken Blossoms or The Yellow Man and the Girl...,1919,90min,Drama Romance,Le lys brisé (1919),7.2,11014.0,"A frail waif, abused by her brutal boxer fathe...",NormanSelby LillianGish RichardBarthelmess Don...,"A frail waif, abused by her brutal boxer fathe..."
...,...,...,...,...,...,...,...,...,...,...,...,...
8582,tt9892338,Dare to Surf (2019),No Dorai (2019),2019,150min,Drama,NaN,7.2,705.0,"In a small beach town in Bangladesh, fearless ...",SunerahBinteKamal SarifulRazz JosefineLindegaa...,"In a small beach town in Bangladesh, fearless ..."
8583,tt9894394,Upin & Ipin: Keris Siamang Tunggal (2019),Upin & Ipin: Keris siamang tunggal (2019),2019,100min,Adventure Animation Comedy,NaN,7.3,829.0,"Upin, Ipin and their friends come across a mys...",AsyielaPutriBtAzhar MohdAmirAsyrafBinMohdNoorR...,"Upin, Ipin and their friends come across a mys..."
8584,tt9900782,Kaithi (2019),Kaithi (2019),2019,145min,Action Crime Drama,Kaithi (2019),8.4,42096.0,A recently released prisoner becomes involved ...,Karthi Narain ArjunDas GeorgeMaryan,A recently released prisoner becomes involved ...
8585,tt9905462,Pengalila (2019),Pengalila (2019),2019,111min,Drama,NaN,7.6,680.0,An unusual bond between a sixty year old Dalit...,,An unusual bond between a sixty year old Dalit...
8586,tt9911196,The Marriage Escape (2020),De beentjes van Sint-Hildegard (2020),2020,103min,Comedy Drama,De Beentjes van Sint-Hildegard (2020),7.4,3306.0,A middle-aged veterinary surgeon believes his ...,HermanFinkers JohannaterSteege LeonieterBraak ...,A middle-aged veterinary surgeon believes his ...

In [37]:
data_ml_modele2.iloc[0]['tags']

'The young daughter of an army captain missing in action runs away from school and is kidnapped by Parisian lowlifes. When the kidnapper flees to Nice with the child, the kind-hearted employee of one of his accomplices sets off in pursuit. Crime Drama LéoncePerret LouisLeubas MauriceLagrenée ÉmileKeppens MarcGérard HenriDuval MarieDorly 124min 1913'

In [38]:
new_data=data_ml_modele2[['tconst','primaryTitle','originalTitle','French_Title','tags']]
new_data

,tconst,primaryTitle,originalTitle,French_Title,tags
0,tt0003883,L'enfant de Paris (1913),L'enfant de Paris (1913),L'Enfant de Paris (1913),The young daughter of an army captain missing ...
1,tt0006206,Les vampires (1915),Les vampires (1915),Les vampires (1915),An intrepid reporter and his loyal friend batt...
2,tt0006864,Intolerance (1916),Intolerance: Love's Struggle Throughout the Ag...,Intolérance (1916),"The story of a poor young woman, separated by ..."
3,tt0006886,Judex (1916),Judex (1916),Judex (1916),A twelve part serial following the adventures ...
4,tt0009968,Broken Blossoms (1919),Broken Blossoms or The Yellow Man and the Girl...,Le lys brisé (1919),"A frail waif, abused by her brutal boxer fathe..."
...,...,...,...,...,...
8582,tt9892338,Dare to Surf (2019),No Dorai (2019),NaN,"In a small beach town in Bangladesh, fearless ..."
8583,tt9894394,Upin & Ipin: Keris Siamang Tunggal (2019),Upin & Ipin: Keris siamang tunggal (2019),NaN,"Upin, Ipin and their friends come across a mys..."
8584,tt9900782,Kaithi (2019),Kaithi (2019),Kaithi (2019),A recently released prisoner becomes involved ...
8585,tt9905462,Pengalila (2019),Pengalila (2019),NaN,An unusual bond between a sixty year old Dalit...
8586,tt9911196,The Marriage Escape (2020),De beentjes van Sint-Hildegard (2020),De Beentjes van Sint-Hildegard (2020),A middle-aged veterinary surgeon believes his ...

In [39]:
#Transformer tags en lettre minuscules
new_data['tags']=new_data['tags'].apply(lambda x :x.lower())
new_data

C:\Users\user\AppData\Local\Temp\ipykernel_12184\3890256331.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_data['tags']=new_data['tags'].apply(lambda x :x.lower())

,tconst,primaryTitle,originalTitle,French_Title,tags
0,tt0003883,L'enfant de Paris (1913),L'enfant de Paris (1913),L'Enfant de Paris (1913),the young daughter of an army captain missing ...
1,tt0006206,Les vampires (1915),Les vampires (1915),Les vampires (1915),an intrepid reporter and his loyal friend batt...
2,tt0006864,Intolerance (1916),Intolerance: Love's Struggle Throughout the Ag...,Intolérance (1916),"the story of a poor young woman, separated by ..."
3,tt0006886,Judex (1916),Judex (1916),Judex (1916),a twelve part serial following the adventures ...
4,tt0009968,Broken Blossoms (1919),Broken Blossoms or The Yellow Man and the Girl...,Le lys brisé (1919),"a frail waif, abused by her brutal boxer fathe..."
...,...,...,...,...,...
8582,tt9892338,Dare to Surf (2019),No Dorai (2019),NaN,"in a small beach town in bangladesh, fearless ..."
8583,tt9894394,Upin & Ipin: Keris Siamang Tunggal (2019),Upin & Ipin: Keris siamang tunggal (2019),NaN,"upin, ipin and their friends come across a mys..."
8584,tt9900782,Kaithi (2019),Kaithi (2019),Kaithi (2019),a recently released prisoner becomes involved ...
8585,tt9905462,Pengalila (2019),Pengalila (2019),NaN,an unusual bond between a sixty year old dalit...
8586,tt9911196,The Marriage Escape (2020),De beentjes van Sint-Hildegard (2020),De Beentjes van Sint-Hildegard (2020),a middle-aged veterinary surgeon believes his ...

In [40]:
new_data.head()

,tconst,primaryTitle,originalTitle,French_Title,tags
0,tt0003883,L'enfant de Paris (1913),L'enfant de Paris (1913),L'Enfant de Paris (1913),the young daughter of an army captain missing ...
1,tt0006206,Les vampires (1915),Les vampires (1915),Les vampires (1915),an intrepid reporter and his loyal friend batt...
2,tt0006864,Intolerance (1916),Intolerance: Love's Struggle Throughout the Ag...,Intolérance (1916),"the story of a poor young woman, separated by ..."
3,tt0006886,Judex (1916),Judex (1916),Judex (1916),a twelve part serial following the adventures ...
4,tt0009968,Broken Blossoms (1919),Broken Blossoms or The Yellow Man and the Girl...,Le lys brisé (1919),"a frail waif, abused by her brutal boxer fathe..."

In [41]:
new_data.iloc[0]['tags']

'the young daughter of an army captain missing in action runs away from school and is kidnapped by parisian lowlifes. when the kidnapper flees to nice with the child, the kind-hearted employee of one of his accomplices sets off in pursuit. crime drama léonceperret louisleubas mauricelagrenée émilekeppens marcgérard henriduval mariedorly 124min 1913'

# Racinisation (ou stemming) des mots dans un texte donné

In [42]:
# Avec l'algorithme Snowball
from nltk.stem.snowball import SnowballStemmer
sb = SnowballStemmer(language='english') # initialisation avec la langue anglaise

In [43]:
def stem(text):
    L = []
    for i in text.split():
        L.append(sb.stem(i))
    string = " ".join(L)
    return string

In [44]:
new_data['tags'] = new_data['tags'].apply(stem)
new_data.head()

C:\Users\user\AppData\Local\Temp\ipykernel_12184\1595017137.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_data['tags'] = new_data['tags'].apply(stem)

,tconst,primaryTitle,originalTitle,French_Title,tags
0,tt0003883,L'enfant de Paris (1913),L'enfant de Paris (1913),L'Enfant de Paris (1913),the young daughter of an armi captain miss in ...
1,tt0006206,Les vampires (1915),Les vampires (1915),Les vampires (1915),an intrepid report and his loyal friend battl ...
2,tt0006864,Intolerance (1916),Intolerance: Love's Struggle Throughout the Ag...,Intolérance (1916),"the stori of a poor young woman, separ by prej..."
3,tt0006886,Judex (1916),Judex (1916),Judex (1916),a twelv part serial follow the adventur of the...
4,tt0009968,Broken Blossoms (1919),Broken Blossoms or The Yellow Man and the Girl...,Le lys brisé (1919),"a frail waif, abus by her brutal boxer father ..."

In [45]:
new_data.iloc[0]['tags']

'the young daughter of an armi captain miss in action run away from school and is kidnap by parisian lowlifes. when the kidnapp flee to nice with the child, the kind-heart employe of one of his accomplic set off in pursuit. crime drama léonceperret louisleuba mauricelagrené émilekeppen marcgérard henriduv mariedor 124min 1913'

In [46]:
#2nd methode de racinisation
#import nltk
#from nltk.stem import PorterStemmer
#ps = PorterStemmer()
#def stems(text):
#    T = []
    
#    for i in text.split():
#        T.append(ps.stem(i))
    
#    return " ".join(T)

# Construction du modèle

In [47]:
from sklearn.feature_extraction.text import CountVectorizer
#Création du modèle
model2 = CountVectorizer(max_features=30000, stop_words='english')
#Entrainer le modèle
vector_matrix = model2.fit_transform(new_data['tags'])
vector_matrix.shape

(8587, 30000)

In [48]:
print(model2.get_feature_names_out())  # Cette ligne affiche les noms des fonctionnalités (mots) après la vectorisation

['00' '000' '007' ... 'ünalgürel' 'üstünasutay' 'þorsteinnbachmann']

In [49]:
print(model2.vocabulary_)  # Cette ligne affiche le vocabulaire avec les indices correspondants après la vectorisation

{'young': 29406, 'daughter': 7568, 'armi': 3031, 'captain': 5128, 'miss': 15378, 'action': 814, 'run': 21685, 'away': 3461, 'school': 22572, 'kidnap': 13825, 'parisian': 17925, 'kidnapp': 13826, 'flee': 10994, 'nice': 16551, 'child': 5879, 'kind': 13868, 'heart': 12211, 'employe': 9722, 'accomplic': 774, 'set': 22993, 'pursuit': 19628, 'crime': 7055, 'drama': 8901, 'émilekeppen': 29957, '124min': 46, '1913': 227, 'intrepid': 12851, 'report': 20680, 'loyal': 14476, 'friend': 11452, 'battl': 3754, 'bizarr': 4131, 'secret': 22720, 'societi': 23999, 'crimin': 7059, 'known': 13920, 'vampires': 27683, 'adventur': 1024, 'stacianapierkowska': 24454, 'musidora': 15829, 'édouardmathé': 29952, 'fernandherrmann': 10778, '421min': 475, '1915': 229, 'stori': 24739, 'poor': 19051, 'woman': 28956, 'separ': 22882, 'prejudic': 19261, 'husband': 12530, 'baby': 3591, 'interwoven': 12846, 'tale': 25563, 'intoler': 12850, 'history': 12362, 'histori': 12360, 'lilliangish': 14309, 'robertharron': 21187, 'turn': 27034, '163min': 119, '1916': 230, 'twelv': 27057, 'serial': 22962, 'follow': 11090, 'mask': 14946, 'vigilant': 28026, 'fight': 10852, 'led': 14165, 'corrupt': 6903, 'banker': 3685, 'favrauxom': 10645, 'renécresté': 20650, 'renépoyen': 20661, '300min': 440, 'frail': 11193, 'waif': 28465, 'abus': 749, 'brutal': 4773, 'boxer': 4454, 'father': 10615, 'london': 14403, 'seedi': 22737, 'district': 8538, 'befriend': 3790, 'sensit': 22857, 'chines': 5904, 'immigr': 12646, 'tragic': 26727, 'consequences': 6743, 'romanc': 21404, 'normanselbi': 16968, 'richardbarthelmess': 20889, 'donaldcrisp': 8699, 'arthurhoward': 3102, 'edwardpeilsr': 9249, '90min': 551, '1919': 233, 'men': 15107, 'married': 14890, 'lover': 14468, 'wife': 28785, 'meet': 15061, 'trench': 26826, 'world': 29008, 'war': 28554, 'becom': 3782, 'horror': 12436, 'romualdjoubé': 21427, 'séverin': 25431, 'mar': 14754, 'angèleguy': 2366, '166min': 125, 'naiv': 16026, 'countri': 6949, 'girl': 11789, 'trick': 26861, 'sham': 23111, 'marriag': 14887, 'wealthi': 28633, 'womanizer': 28957, 'rebuild': 20346, 'life': 14284, 'despit': 8062, 'taint': 25499, 'born': 4398, 'wedlock': 28653, 'mrs': 15688, 'davidlandau': 7628, '145min': 86, '1920': 235, 'new': 16515, 'year': 29228, 'eve': 10188, 'driver': 8945, 'ghost': 11738, 'carriag': 5295, 'forc': 11118, 'drunken': 8963, 'man': 14698, 'reflect': 20438, 'selfish': 22793, 'wast': 28599, 'fantasi': 10534, 'einaraxelsson': 9324, 'victorsjöström': 27999, 'toresvennberg': 26617, 'astridholm': 3250, 'concordiaseland': 6668, 'torweijden': 26640, '107min': 21, '1921': 237, 'fiancé': 10829, 'disappears': 8417, 'death': 7717, 'chanc': 5567, 'save': 22481, 'fate': 10605, 'walterjanssen': 28527, '97min': 565, 'orphan': 17491, 'sister': 23790, 'caught': 5422, 'turmoil': 27033, 'french': 11427, 'revolution': 20816, 'encount': 9752, 'miseri': 15366, 'love': 14464, 'way': 28617, 'dorothygish': 8814, 'josephschildkraut': 13453, 'franklose': 11298, '150min': 97, 'vampir': 27681, 'count': 6940, 'orlok': 17486, 'express': 10363, 'resid': 20716, 'real': 20296, 'estat': 10073, 'agent': 1114, 'alexandergranach': 1604, '94min': 561, '1922': 238, 'mari': 14801, 'want': 28551, 'escap': 10036, 'job': 13320, 'paul': 18144, 'unemploy': 27296, 'drunk': 8960, 'dream': 8919, 'jean': 13172, 'dockworker': 8611, 'quarrel': 19696, 'ginamanè': 11766, 'edmondvandaël': 9196, 'claudebenedict': 6266, '87min': 542, '1923': 239, '15th': 110, 'centuri': 5497, 'paris': 17922, 'brother': 4727, 'archdeacon': 2924, 'plot': 18940, 'gypsi': 12019, 'king': 13873, 'foment': 11093, 'peasant': 18319, 'revolt': 20814, 'freakish': 11377, 'hunchback': 12512, 'fall': 10496, 'queen': 19704, 'lonchaney': 14401, 'patsyruthmil': 18134, 'normankerri': 16966, '133min': 59, 'sisif': 23787, 'railwayman': 19905, 'son': 24107, 'eli': 9426, 'beauti': 3775, 'norma': 16952, 'rescu': 20701, 'train': 26732, 'crash': 7020, 'babi': 3582, 'rais': 19922, 'results': 20760, 'origin': 17474, 'pierremagni': 18780, '417min': 472, 'shy': 23552, 'complet': 6621, 'incap': 12680, 'talk': 25576, 'women': 28958, 'decid': 7765, 'write': 29047, 'book': 4335, 'bachelor': 3600, 'girlfriend': 11790, 'comedi': 6551, 'haroldlloyd': 12148, 'jobynaralston': 13323, 'richarddaniel': 20905, 'carltongriffin': 5225, '1924': 240, 'bitter': 4126, 'clown': 6403, 'endeavor': 9764, 'lecher': 14163, 'onc': 17368, 'betray': 3878, 'thriller': 26217, 'normashear': 16969, 'johngilbert': 13373, 'ruthk': 21745, '95min': 562, 'clair': 6214, 'famous': 10516, 'lady': 14040, 'scientist': 22593, 'einar': 9323, 'norsen': 16972, 'mock': 15419, 'leav': 14158, 'hous': 12460, 'declar': 7771, 'intent': 12824, 'kill': 13839, 'mysteri': 15886, 'philippehériat': 18651, 'fredkellerman': 11401, '135min': 61, 'wit': 28915, 'murder': 15790, 'renegad': 20621, 'boy': 4457, 'grown': 11953, 'brandon': 4514, 'help': 12258, 'realiz': 20305, 'transcontinent': 26751, 'railway': 19904, 'georgeo': 11700, 'brien': 4640, 'madgebellami': 14587, 'charlesedwardbul': 5672, 'cyrilchadwick': 7233, 'age': 1109, 'doorman': 8763, 'prestigi': 19303, 'luxuri': 14541, 'hotel': 12454, 'face': 10436, 'scorn': 22608, 'friends': 11454, 'neighbour': 16427, 'society': 24001, 'emiljan': 9651, 'malydelschaft': 14689, 'emiliekurz': 9643, '88min': 544, 'siegfri': 23630, 'dead': 7696, 'kriemhild': 13950, 'marri': 14886, 'etzel': 10126, 'huns': 12520, 'birth': 4108, 'invit': 12872, 'party': 17991, 'tri': 26842, 'persuad': 18483, 'erwinbiswang': 10022, 'margareteschön': 14780, 'gertrudarnold': 11728, 'theodorloo': 26085, '129min': 51, 'siegfried': 23631, 'sigmund': 23643, 'hear': 12208, 'worms': 29016, 'dragon': 8896, 'treasure': 26807, 'paulricht': 18239, '143min': 83, 'past': 18043, 'live': 14362, 'pari': 17916, 'enidbennett': 9799, 'ramonnovarro': 20087, 'wallacebeeri': 28497, 'frankcurri': 11280, '81min': 535, 'group': 11950, 'oppress': 17425, 'factori': 10448, 'worker': 29000, 'strike': 24803, 'pre': 19218, 'revolutionari': 20817, 'russia': 21722, '82min': 536, '1925': 241, 'recalcitr': 20350, 'thief': 26117, 'vie': 28013, 'duplicit': 9021, 'mongol': 15473, 'ruler': 21676, 'hand': 12084, 'princess': 19342, 'famili': 10507, 'douglasfairbank': 8848, 'snitzedward': 23973, 'charlesbelch': 5657, '155min': 104, 'american': 1955, 'soldier': 24052, 'great': 11916, 'renéeadoré': 20652, 'clairemcdowel': 6224, '151min': 98, 'prospector': 19485, 'goe': 11829, 'search': 22689, 'gold': 11834, 'charleschaplin': 5665, 'tommurray': 26512, 'henrybergman': 12271, 'sudden': 24944, 'fortun': 11168, 'won': 28959, 'lotteri': 14439, 'fan': 10517, 'destruct': 8077, 'greed': 11921, 'ruin': 21665, 'peopl': 18395, 'involved': 12874, 'western': 28723, 'zasupitt': 29718, 'jeanhersholt': 13184, 'daleful': 7314, '140min': 76, 'believ': 3816, 'affair': 1060, 'misconcept': 15363, 'dire': 8390, 'person': 18472, 'consequ': 6742, 'irenerich': 12896, 'ronaldcolman': 21433, '120min': 42, 'steve': 24663, 'tuttle': 27047, 'titular': 26386, 'respons': 20740, 'fatherless': 10618, 'caus': 5423, 'scandal': 22526, 'small': 23927, 'town': 26689, 'mani': 14713, 'later': 14099, 'return': 20786, 'buckjon': 4802, 'virginiamarshal': 28201, 'edythechapman': 9257, '85min': 540, 'princ': 19340, 'woo': 28970, 'dancer': 7368, 'abandon': 617, 'order': 17451, 'money': 15471, 'economically': 9142, 'royd': 21604, 'arci': 2939, '137min': 66, 'mad': 14577, 'disfigur': 8468, 'compos': 6631, 'seek': 22739, 'opera': 17405, 'singer': 23749, 'maryphilbin': 14921, 'arthuredmundcarew': 3098, '93min': 559, 'stella': 24599, 'socialit': 23995, 'stephen': 24624, 'dallas': 7323, 'noth': 16991, 'common': 6583, 'thing': 26131, 'failure': 10469, 'laurel': 14114, 'dallases': 7324, 'alicejoyc': 1721, '110min': 26, 'sideshow': 23615, 'ventriloquist': 27869, 'strongman': 24821, 'form': 11148, 'conspiraci': 6753, 'unholi': 27329, 'commit': 6578, 'seri': 22961, 'robberies': 21140, 'victormclaglen': 27991, '86min': 541, 'prologue': 19443, 'boss': 4415, 'spent': 24319, 'prison': 19357, 'break': 4551, 'silenc': 23664, 'tell': 25877, 'warden': 28560, 'story': 24747, 'trapez': 26780, 'artist': 3119, 'cheap': 5757, 'warwickward': 28588, '104min': 16, 'die': 8267, 'remarries': 20574, 'previous': 19319, 'marriage': 14888, 'mother': 15621, 'deepli': 7804, 'terribly': 25974, 'victorvina': 28002, 'pierrettehouyez': 18791, 'laur': 14108, '114min': 30, 'starv': 24523, 'surviv': 25184, '1830s': 166, 'includ': 12688, 'seamstress': 22669, 'playwright': 18925, 'loves': 14470, '1926': 242, 'demon': 7923, 'wager': 28453, 'god': 11823, 'mortal': 15593, 'soul': 24228, 'göstaekman': 12032, 'camillahorn': 5054, 'fridarichard': 11445, 'childhood': 5882, 'torn': 26624, 'apart': 2820, 'fierc': 10846, 'loved': 14465, 'gretagarbo': 11931, 'larshanson': 14094, '112min': 28, 'landladi': 14064, 'suspect': 25229, 'lodger': 14391, 'madman': 14597, 'arthurchesney': 3096, '92min': 556, '1927': 243, 'protect': 19498, 'troublemakers': 26911, 'eventu': 10208, 'right': 21005, 'verabaranovskaya': 27878, 'nikolaybatalov': 16703, 'aleksandrchistyakov': 1522, 'annazemtsova': 2509, '89min': 546, 'futurist': 11565, 'citi': 6199, 'sharpli': 23201, 'divid': 8557, 'work': 28997, 'class': 6255, 'planners': 18901, 'mastermind': 14960, 'prophet': 19471, 'predict': 19235, 'come': 6548, 'savior': 22487, 'mediat': 15050, 'differences': 8290, 'sci': 22589, 'fi': 10825, 'brigittehelm': 4657, 'alfredabel': 1677, 'gustavfröhlich': 12004, 'rudolfklein': 21642, 'rogg': 21341, '153min': 101, 'puritan': 19616, 'pressur': 19299, 'reveal': 20798, 'walthal': 28535, '115min': 31, 'eldest': 9362, 'farm': 10574, 'hidden': 12305, 'deep': 7789, 'swamp': 25296, 'cruel': 7114, 'master': 14958, 'dispos': 8512, 'roystewart': 21611, 'gustavvonseyffertitz': 12006, '109min': 23, 'outlaw': 17608, 'aid': 1240, 'killed': 13840, 'oliveborden': 17289, 'tomsantschi': 26544, 'wild': 28791, 'jazz': 13168, 'lov': 14462, 'booz': 4356, 'roxi': 21590, 'boyfriend': 4462, 'cold': 6474, 'blood': 4197, 'phyllishav': 18710, 'victorvarconi': 28001, 'virginiabradford': 28193, 'robertedeson': 21172, '105min': 18, 'hapless': 12113, 'undergo': 27268, 'misadventur': 15355, 'avarici': 3422, 'clergy': 6344, 'tire': 26366, 'horse': 12438, 'walk': 28489, 'road': 21130, 'collectiv': 6501, 'happiness': 12119, 'pyotrzinovyev': 19648, 'yelenayegorova': 29246, '1935': 253, 'sheriff': 23292, 'milquetoast': 15297, 'prove': 19508, 'medicin': 15052, 'walterjam': 28526, 'jesus': 13264, 'christ': 6032, 'religi': 20557, 'polit': 18996, 'dure': 9023, 'ministri': 15321, 'day': 7681, 'befor': 3789, 'resurrection': 20766, 'biographi': 4074, 'warner': 28571, 'dorothycum': 8811, 'ernesttorr': 9984, '160min': 114, 'st': 24446, 'petersburg': 18560, 'unwit': 27457, 'arrest': 3065, 'old': 17232, 'labor': 14029, 'leader': 14145, 'sent': 22862, 'years': 29231, 'rebel': 20337, 'vladimirobolenski': 28318, 'crimea': 7056, 'red': 20397, 'white': 28752, 'aren': 2945, 'fighting': 10854, 'jeann': 13188, 'discov': 8452, 'bolshevik': 4292, 'penniless': 18387, 'édithjéhann': 29950, 'unohen': 27383, 'fritzrasp': 11469, 'film': 10882, 'general': 11660, 'youth': 29427, 'earli': 9096, 'militari': 15279, 'career': 5152, 'albertdieudonné': 1432, 'vladimirroudenko': 28324, 'alexandrekoubitzki': 1626, '330min': 449, 'large': 14084, 'scal': 22521, 'view': 28020, 'event': 10206, '1917': 231, 'overthrown': 17661, 'borislivanov': 4386, 'nikolaypopov': 16711, 'vasilinikandrov': 27769, '142min': 81, 'street': 24788, 'cleaner': 6328, 'pair': 17753, 'slowli': 23919, 'intervenes': 12842, 'janetgaynor': 13099, 'charlesfarrel': 5673, 'albertgran': 1435, 'cloistered': 6385, 'overprotect': 17652, 'austrian': 3389, 'earth': 9104, 'viennes': 28015, 'fairi': 10475, '106min': 20, 'allegor': 1801, 'good': 11847, 'evil': 10252, 'flesh': 10999, 'sophist': 24191, 'attract': 3322, 'bodilros': 4250, 'coupl': 6958, 'moscow': 15604, 'arriv': 3068, 'city': 6204, 'unabl': 27202, 'vladimirfogel': 28303, 'rich': 20880, 'middl': 15220, 'fighter': 10853, 'pilot': 18815, 'clarabow': 6240, 'charles': 5654, 'buddy': 4814, 'rog': 21321, 'richardarlen': 20886, '144min': 84, 'treacher': 26800, 'step': 24608, 'vagabond': 27584, 'dress': 8928, 'hop': 12421, 'freight': 11425, 'trains': 26738, 'steal': 24553, 'roscoekarn': 21514, 'louisebrook': 14450, 'bobperri': 4242, '84min': 539, '1928': 244, 'rise': 21056, 'inevit': 12726, 'amor': 2010, 'erotic': 10006, 'inspir': 12802, 'lust': 14538, 'violenc': 28168, 'fritzkortn': 11468, 'francisleder': 11251, 'carlgoetz': 5180, '1929': 245, 'saga': 21925, 'widow': 28774, 'germani': 11723, 'fourth': 11187, 'america': 1953, 'opponent': 17414, 'jameshal': 13059, 'margaretmann': 14785, 'charlesmorton': 5685, 'francisx': 11253, 'bushmanjr': 4925, '100min': 8, 'imperi': 12655, 'russian': 21723, 'cousin': 6981, 'czar': 7242, 'end': 9760, 'hollywood': 12388, 'extra': 10379, 'movi': 15673, 'direct': 8391, 'revolutionary': 20819, 'evelynbr': 10197, 'williampowel': 28846, 'proud': 19506, 'nobl': 16870, 'refus': 20446, 'kiss': 13896, 'despot': 8065, 'jame': 13040, '1690': 129, 'cruelli': 7115, 'execut': 10295, 'surgic': 25165, 'disfigured': 8469, 'conradveidt': 6729, 'olgabaclanova': 17264, 'spi': 24323, 'seduc': 22733, 'offic': 17186, 'import': 12659, 'plans': 18903, 'actual': 828, 'place': 18885, 'danger': 7378, 'situation': 23802, 'conradnagel': 6728, 'albertpollet': 1448, '96min': 563, '1431': 82, 'arc': 2912, 'trial': 26844, 'charg': 5643, 'ecclesiast': 9135, 'attempt': 3303, 'recant': 20351, 'claim': 6212, 'holi': 12383, 'visions': 28240, 'eugenesilvain': 10132, 'andréberley': 2276, 'prostitut': 19491, 'fresh': 11437, 'start': 24519, 'obsess': 17125, 'extremist': 10389, 'lionelbarrymor': 14335, 'blanchefriderici': 4163, 'charleslan': 5680, 'florencemidgley': 11035, 'ladi': 14039, 'georgia': 11708, 'hope': 12422, 'actress': 825, 'williamhain': 28838, 'dellhenderson': 7885, 'paulral': 18236, '83min': 537, 'harold': 12147, 'speedy': 24312, 'swift': 25332, 'annchristi': 2511, 'baberuth': 3580, 'ubiquit': 27118, 'oper': 17404, 'learn': 14155, 'employ': 9721, 'dash': 7556, 'govern': 11874, 'service': 22983, 'gerdamaurus': 11721, 'willyfritsch': 28871, 'law': 14129, 'catch': 5369, 'just': 13578, 'verg': 27898, 'true': 26929, 'nataliekingston': 16224, '102min': 14, 'working': 29002, 'underground': 27270, '1920s': 236, 'gentl': 11678, 'brash': 4535, 'brianahern': 4593, 'elissalandi': 9479, 'cyrilmclaglen': 7235, 'norahbar': 16932, 'impoverish': 12663, 'aristocrat': 2995, 'inn': 12779, 'erichvonstroheim': 9938, 'faywray': 10652, '113min': 29, 'east': 9112, 'west': 28722, 'tension': 25921, 'driven': 8944, 'montagulov': 15516, 'busi': 4927, 'tycoon': 27070, 'nicola': 16589, 'saccard': 21863, 'near': 16358, 'rival': 21100, 'capit': 5120, 'company': 6602, 'push': 19629, 'price': 19323, 'stock': 24712, 'plan': 18894, 'public': 19559, 'pierrealcov': 18749, 'yvetteguilbert': 29586, '195min': 282, 'joe': 13328, 'sensual': 22859, 'berlin': 3859, 'underworld': 27286, 'perfect': 18419, 'summat': 25049, 'german': 11722, 'filmmak': 10884, 'silent': 23666, 'era': 9904, 'dazzl': 7690, 'visual': 28248, 'style': 24860, 'psycholog': 19550, 'approach': 2871, 'albertsteinrück': 1453, 'elsehel': 9566, 'tenaci': 25906, 'blast': 4171, 'moon': 15539, '156min': 105, 'mary': 14913, 'tim': 26294, 'word': 28995, 'declared': 7772, 'enlist': 9804, 'battlefield': 3756, 'europe': 10146, 'wound': 29031, 'lose': 14430, 'use': 27522, 'bigboy': 3976, 'william': 28825, 'paulfix': 18181, 'mutter': 15862, 'kraus': 13949, 'children': 5886, 'poorer': 19053, 'section': 22726, 'wed': 28650, 'depict': 7995, 'cruelti': 7116, 'poverti': 19133, 'communism': 6590, 'reach': 20285, 'late': 14098, 'alexandraschmitt': 1622, '121min': 43, 'begin': 3796, 'industri': 12720, 'commune': 6587, 'establish': 10070, '1871': 189, 'powerful': 19142, 'violent': 28170, 'repress': 20684, 'remain': 20567, 'faith': 10480, 'davidgutman': 7611, 'yelenakuzmina': 29245, 'andreikostrichkin': 2210, 'sofiyamagaril': 24016, 'naïv': 16351, 'log': 14393, 'camp': 5065, 'besid': 3874, 'turbul': 27021, 'river': 21105, 'close': 6387, 'winter': 28898, 'opt': 17432, 'stay': 24545, 'experience': 10339, '100': 5, '000': 1, 'longer': 14411, 'soviet': 24253, 'state': 24531, 'progress': 19430, 'chang': 5600, 'village': 28095, 'vasilibuzenkov': 27763, 'pregnant': 19258, 'pharmacist': 18614, 'marry': 14891, 'thrown': 26224, 'home': 12394, 'strict': 24801, 'reform': 20439, 'edithmeinhard': 9187, 'climb': 6364, '12': 38, 'foot': 11106, 'mountain': 15653, 'lost': 14434, 'honeymoon': 12409, 'anoth': 2600, 'make': 14661, 'gustavdiessl': 12003, 'ernstpetersen': 9994, 'ernstudet': 9996, 'flapper': 10973, 'dubious': 8977, 'reput': 20693, 'enjoy': 9802, 'vivaci': 28272, 'night': 16647, 'danc': 7365, 'romant': 21418, 'link': 14331, 'music': 15823, 'colleenmoor': 6505, 'neilhamilton': 16435, 'poli': 18987, 'eager': 9091, 'enter': 9845, 'enthusiasm': 9852, 'wane': 28546, 'firsthand': 10939, 'lewayr': 14260, 'johnwray': 13411, 'arnoldluci': 3048, '152min': 99, '1930': 247, 'mayhem': 15021, 'zani': 29706, 'ensu': 9839, 'valuabl': 27669, 'paint': 17750, 'parti': 17976, 'honor': 12413, 'fame': 10505, 'african': 1082, 'explor': 10352, 'spaulding': 24287, 'grouchomarx': 11948, 'harpomarx': 12149, 'chicomarx': 5852, 'denise': 7943, 'uncl': 27234, 'store': 24737, 'glamor': 11799, 'depart': 7991, 'aux': 3411, 'bonheur': 4322, 'des': 8030, 'dame': 7333, 'crunch': 7123, 'littl': 14357, 'posit': 19100, 'ditaparlo': 8541, 'andréebrab': 2280, 'elder': 9361, 'professor': 19421, 'spin': 24331, 'control': 6808, 'nightclub': 16648, 'marlenedietrich': 14877, 'rosavaletti': 21510, 'barber': 3706, 'high': 12313, 'secur': 22728, 'flashback': 10976, 'lonely': 14407, 'dartmoor': 7547, 'anthonyasquith': 2631, 'mont': 15515, 'ray': 20244, 'oxford': 17684, 'join': 13412, 'royal': 21595, 'fli': 11003, 'corps': 6896, 'helen': 12246, 'monte': 15518, 'mission': 15381, 'arms': 3038, 'jeanharlow': 13183, '127min': 49, 'alcohol': 1462, 'ex': 10271, 'box': 4453, 'struggl': 24825, 'provid': 19513, 'sport': 24356, 'roscoeat': 21513, '1931': 249, 'pimp': 18819, 'exploit': 10349, 'painter': 17751, 'michelsimon': 15205, 'rogergaillard': 21329, '91min': 554, 'errat': 10008, 'tippler': 26365, 'dewy': 8152, 'ey': 10393, 'tramp': 26744, 'fallen': 10497, 'sightless': 23642, 'flower': 11057, 'accumul': 783, 'abl': 713, 'virginiacherril': 28195, 'florencele': 11033, 'century': 5499, 'bandit': 3675, 'knife': 13913, 'polli': 19005, 'knowledg': 13918, 'peachum': 18310, 'rudolfforst': 21639, 'lottelenya': 14438, 'carolaneh': 5260, 'reinholdschünzel': 20519, 'editor': 9191, 'sleazi': 23882, 'tabloid': 25458, 'journalist': 13479, 'ethic': 10114, 'resurrect': 20764, 'twenti': 27058, 'case': 5328, 'edwardg': 9239, 'robinson': 21262, 'anthonybushel': 2634, 'plea': 18928, 'friendship': 11455, 'peoples': 18397, 'miner': 15311, 'colleagu': 6497, 'firedamp': 10929, 'explosion': 10355, 'fritzkamp': 11467, 'ernstbusch': 9990, 'elisabethwendt': 9472, 'polic': 18988, 'murderer': 15792, 'manhunt': 14712, 'peterlorr': 18545, 'ellenwidmann': 9532, 'ottowernick': 17582, '117min': 33, 'marius': 14855, 'choic': 5959, 'fulfil': 11517, 'passion': 18035, 'sail': 21950, 'sea': 22662, 'raimu': 19908, 'pierrefresnay': 18774, 'fernandcharpin': 10775, 'alidarouff': 1732, '130min': 56, 'engag': 9783, 'race': 19768, 'recov': 20389, 'conceal': 6650, 'win': 28879, 'ticket': 26261, 'annabella': 2455, 'renélefèvr': 20660, 'paulollivi': 18227, 'unappreci': 27210, 'minist': 15319, 'dies': 8281, 'prompt': 19456, 'open': 17401, 'phoni': 18694, 'templ': 25894, 'blind': 4185, 'aviat': 3433, 'restor': 20753, 'barbarastanwyck': 3704, 'davidmann': 7632, 'samhardi': 22102, 'board': 4221, 'manuela': 14743, 'teacher': 25806, 'terrif': 25976, 'dorotheawieck': 8808, 'emiliaunda': 9641, 'hoodlum': 12417, 'rank': 20143, 'chicago': 5844, 'gangster': 11607, 'accident': 767, 'threaten': 26210, 'spark': 24278, 'bloodi': 4198, 'mob': 15416, 'jamescagney': 13046, 'edwardwood': 9251, 'joanblondel': 13305, 'bart': 3728, 'clerk': 6347, 'publish': 19561

In [50]:
#Cosine similarity
#Values: 0 to 1 (1 : most similar, 0 : not so similar)
from sklearn.metrics.pairwise import cosine_similarity

In [51]:
#Distance d'un film avec tous les autres films
similarity = cosine_similarity(vector_matrix)

In [52]:
similarity.shape

(8587, 8587)

In [53]:
#Première ligne de la matrice de similarité, qui représente la similarité cosinus entre le premier film et tous les autres films
similarity[0]

array([1.        , 0.0877058 , 0.08998425, ..., 0.15689291, 0.03140371,
       0.09245003])

In [54]:
#Cinquième film
similarity[4]

array([0.03922323, 0.        , 0.09176629, ..., 0.04      , 0.06405126,
       0.04714045])

In [55]:
similarity

array([[1.        , 0.0877058 , 0.08998425, ..., 0.15689291, 0.03140371,
        0.09245003],
       [0.0877058 , 1.        , 0.        , ..., 0.13416408, 0.        ,
        0.        ],
       [0.08998425, 0.        , 1.        , ..., 0.04588315, 0.03673592,
        0.05407381],
       ...,
       [0.15689291, 0.13416408, 0.04588315, ..., 1.        , 0.09607689,
        0.04714045],
       [0.03140371, 0.        , 0.03673592, ..., 0.09607689, 1.        ,
        0.03774257],
       [0.09245003, 0.        , 0.05407381, ..., 0.04714045, 0.03774257,
        1.        ]])

# Fonction de recommandation

In [56]:
def recommandation(movie):
    # Rechercher le film en fonction de primaryTitle, originalTitle ou frenchTitle
    movie_index = new_data[(new_data['primaryTitle'] == movie) | 
                           (new_data['originalTitle'] == movie) | 
                           (new_data['French_Title'] == movie)].index[0]
    # Extraire les distances du film donné avec tous les autres films
    distances = similarity[movie_index]
    # Trouver les 5 films les plus similaires excepté du film donné 
    movies_list = sorted(list(enumerate(distances)),reverse=True,key=lambda x:x[1])[1:6]
    # Afficher les titres des films recommandés
    for i in movies_list:
        title = new_data.iloc[i[0]]['primaryTitle']
        distance = i[1]
        print(f"Film: {title}, Similarity: {distance}")

In [57]:
recommandation('X-Men (2000)')

Film: X-Men: Days of Future Past (2014), Similarity: 0.3265986323710905
Film: X2 (2003), Similarity: 0.2919201796799047
Film: Logan (2017), Similarity: 0.2556038601690775
Film: The Lord of the Rings: The Return of the King (2003), Similarity: 0.2085144140570748
Film: Invention for Destruction (1958), Similarity: 0.20412414523193156

In [60]:
#Evaluation du modèle

Film: X-Men: Days of Future Past (2014), Similarity: 0.3265986323710905
Film: X2 (2003), Similarity: 0.2919201796799047
Film: Logan (2017), Similarity: 0.2556038601690775
Film: The Lord of the Rings: The Return of the King (2003), Similarity: 0.2085144140570748
Film: Invention for Destruction (1958), Similarity: 0.20412414523193156

TypeError: 'NoneType' object is not iterable