In [1]:
import pandas as pd
import numpy as np

# Fichier name.basics

In [2]:
#Importer le fichier 
pd.read_csv("name.basics.tsv.gz", sep = "\t", compression = "gzip")

,nconst,primaryName,birthYear,deathYear,primaryProfession,knownForTitles
0,nm0000001,Fred Astaire,1899,1987,"soundtrack,actor,miscellaneous","tt0053137,tt0072308,tt0027125,tt0050419"
1,nm0000002,Lauren Bacall,1924,2014,"actress,soundtrack","tt0038355,tt0037382,tt0075213,tt0117057"
2,nm0000003,Brigitte Bardot,1934,\N,"actress,soundtrack,music_department","tt0054452,tt0057345,tt0056404,tt0049189"
3,nm0000004,John Belushi,1949,1982,"actor,soundtrack,writer","tt0078723,tt0077975,tt0072562,tt0080455"
4,nm0000005,Ingmar Bergman,1918,2007,"writer,director,actor","tt0050986,tt0050976,tt0083922,tt0069467"
...,...,...,...,...,...,...
13339961,nm9993714,Romeo del Rosario,\N,\N,"animation_department,art_department","tt2455546,tt14069590,tt11657662"
13339962,nm9993716,Essias Loberg,\N,\N,NaN,\N
13339963,nm9993717,Harikrishnan Rajan,\N,\N,cinematographer,tt8736744
13339964,nm9993718,Aayush Nair,\N,\N,cinematographer,tt8736744
13339965,nm9993719,Andre Hill,\N,\N,NaN,\N

In [3]:
# Placer le fichier dans la variable data
data_name_basics = pd.read_csv("name.basics.tsv.gz", sep = "\t", compression = "gzip")

In [4]:
data_name_basics.head()

,nconst,primaryName,birthYear,deathYear,primaryProfession,knownForTitles
0,nm0000001,Fred Astaire,1899,1987,"soundtrack,actor,miscellaneous","tt0053137,tt0072308,tt0027125,tt0050419"
1,nm0000002,Lauren Bacall,1924,2014,"actress,soundtrack","tt0038355,tt0037382,tt0075213,tt0117057"
2,nm0000003,Brigitte Bardot,1934,\N,"actress,soundtrack,music_department","tt0054452,tt0057345,tt0056404,tt0049189"
3,nm0000004,John Belushi,1949,1982,"actor,soundtrack,writer","tt0078723,tt0077975,tt0072562,tt0080455"
4,nm0000005,Ingmar Bergman,1918,2007,"writer,director,actor","tt0050986,tt0050976,tt0083922,tt0069467"

In [5]:
data_name_basics.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13339966 entries, 0 to 13339965
Data columns (total 6 columns):
 #   Column             Dtype
---  ------             -----
 0   nconst             object
 1   primaryName        object
 2   birthYear          object
 3   deathYear          object
 4   primaryProfession  object
 5   knownForTitles     object
dtypes: object(6)
memory usage: 610.7+ MB

In [6]:
# Trouver les valeurs manquantes parmi toutes les colonnes
data_name_basics[data_name_basics.isna().any(axis=1)]

,nconst,primaryName,birthYear,deathYear,primaryProfession,knownForTitles
2648,nm0002652,Gary Rosen,\N,\N,NaN,"tt0268808,tt0358197"
3920,nm0003936,Eivind Fredagsvik Øyangen,1979,\N,NaN,\N
4326,nm0004346,Richard A. Roth,\N,\N,NaN,tt0110724
7212,nm0007243,Antonio 'El de Chipiona',\N,\N,NaN,tt0122520
7225,nm0007257,Izzy 'The Religious Nut',\N,\N,NaN,tt0111522
...,...,...,...,...,...,...
13339957,nm9993710,Nestor Rudnytskyy,\N,\N,NaN,\N
13339958,nm9993711,David Gluzman,\N,\N,NaN,\N
13339959,nm9993712,Corny O'Connell,\N,\N,NaN,\N
13339962,nm9993716,Essias Loberg,\N,\N,NaN,\N
13339965,nm9993719,Andre Hill,\N,\N,NaN,\N

In [7]:
#Remplacer les valeurs manquantes par nan
data_name_basics = data_name_basics.replace('\\N',np.nan)

In [8]:
# SUPPRIMER LES LIGNES OU IL Y A DES VALEURS NULLES DANS LES COLONNES 'PRIMARY NAME','PRIMARY PROFESSION','knownForTitles'
data_name_basics = data_name_basics.dropna(subset=["primaryProfession"])
data_name_basics = data_name_basics.dropna(subset=["knownForTitles"])
data_name_basics = data_name_basics.dropna(subset=["primaryName"])

In [9]:
# Supprimer les colonnes birthYear et deathYear
data_name_basics.drop(columns=['birthYear', 'deathYear'], inplace=True)

In [10]:
# Mettre la colonne 'nconst' en index
data_name_basics = data_name_basics.set_index('nconst')

In [11]:
data_name_basics

,primaryName,primaryProfession,knownForTitles
nconst,,,
nm0000001,Fred Astaire,"soundtrack,actor,miscellaneous","tt0053137,tt0072308,tt0027125,tt0050419"
nm0000002,Lauren Bacall,"actress,soundtrack","tt0038355,tt0037382,tt0075213,tt0117057"
nm0000003,Brigitte Bardot,"actress,soundtrack,music_department","tt0054452,tt0057345,tt0056404,tt0049189"
nm0000004,John Belushi,"actor,soundtrack,writer","tt0078723,tt0077975,tt0072562,tt0080455"
nm0000005,Ingmar Bergman,"writer,director,actor","tt0050986,tt0050976,tt0083922,tt0069467"
...,...,...,...
nm9993709,Lu Bevins,"producer,director,writer","tt11697102,tt11772812,tt17717854,tt11772904"
nm9993713,Sambit Mishra,"writer,producer","tt20319332,tt27191658,tt15134202,tt10709066"
nm9993714,Romeo del Rosario,"animation_department,art_department","tt2455546,tt14069590,tt11657662"
nm9993717,Harikrishnan Rajan,cinematographer,tt8736744
nm9993718,Aayush Nair,cinematographer,tt8736744

In [12]:
# AFFICHER TOUTES LES VALEURS UNIQUES DE LA COLONNE 'primaryProfession'
data_name_basics["primaryProfession"].unique()

array(['soundtrack,actor,miscellaneous', 'actress,soundtrack',
       'actress,soundtrack,music_department', ...,
       'director,soundtrack,editor',
       'costume_department,camera_department,location_management',
       'music_department,script_department,casting_department'],
      dtype=object)

In [13]:
# Récupérer les index ou il y a des mots actor ou actress ou producer dans la colonne "primary Profession"
data_name_basics_index = data_name_basics[data_name_basics["primaryProfession"].str.contains('actor|actress|director')].index
data_name_basics_index

Index(['nm0000001', 'nm0000002', 'nm0000003', 'nm0000004', 'nm0000005',
       'nm0000006', 'nm0000007', 'nm0000008', 'nm0000009', 'nm0000010',
       ...
       'nm9993694', 'nm9993696', 'nm9993697', 'nm9993698', 'nm9993699',
       'nm9993700', 'nm9993701', 'nm9993703', 'nm9993708', 'nm9993709'],
      dtype='object', name='nconst', length=5586396)

In [14]:
#Récupérer les lignes ou il y a des mots actor ou actress ou producer dans la colonne "primary Profession"
data_name_basics_purify = data_name_basics[data_name_basics["primaryProfession"].str.contains('actor|actress|director')]
data_name_basics_purify

,primaryName,primaryProfession,knownForTitles
nconst,,,
nm0000001,Fred Astaire,"soundtrack,actor,miscellaneous","tt0053137,tt0072308,tt0027125,tt0050419"
nm0000002,Lauren Bacall,"actress,soundtrack","tt0038355,tt0037382,tt0075213,tt0117057"
nm0000003,Brigitte Bardot,"actress,soundtrack,music_department","tt0054452,tt0057345,tt0056404,tt0049189"
nm0000004,John Belushi,"actor,soundtrack,writer","tt0078723,tt0077975,tt0072562,tt0080455"
nm0000005,Ingmar Bergman,"writer,director,actor","tt0050986,tt0050976,tt0083922,tt0069467"
...,...,...,...
nm9993700,Sexy Angel,actress,tt7523066
nm9993701,Sanjai Kuriakose,actor,tt8736744
nm9993703,James Craigmyle,actor,"tt6225166,tt11212278,tt6914160,tt10627062"
nm9993708,Eli Bevins,"producer,director,writer","tt11772904,tt14508814,tt11772858,tt11702702"
nm9993709,Lu Bevins,"producer,director,writer","tt11697102,tt11772812,tt17717854,tt11772904"

In [15]:
# AFFICHER  LES VALEURS UNIQUES DE LA COLONNE 'primaryProfession'
data_name_basics_purify["primaryProfession"].unique()

array(['soundtrack,actor,miscellaneous', 'actress,soundtrack',
       'actress,soundtrack,music_department', ...,
       'casting_director,production_manager,manager',
       'assistant,actor,miscellaneous', 'director,soundtrack,editor'],
      dtype=object)

In [16]:
# afficher uniquement les 5 premières lignes
data_name_basics_purify.head()

,primaryName,primaryProfession,knownForTitles
nconst,,,
nm0000001,Fred Astaire,"soundtrack,actor,miscellaneous","tt0053137,tt0072308,tt0027125,tt0050419"
nm0000002,Lauren Bacall,"actress,soundtrack","tt0038355,tt0037382,tt0075213,tt0117057"
nm0000003,Brigitte Bardot,"actress,soundtrack,music_department","tt0054452,tt0057345,tt0056404,tt0049189"
nm0000004,John Belushi,"actor,soundtrack,writer","tt0078723,tt0077975,tt0072562,tt0080455"
nm0000005,Ingmar Bergman,"writer,director,actor","tt0050986,tt0050976,tt0083922,tt0069467"

In [17]:
# Verifier s'il Y'a des valeurs manquantes parmi toutes les colonnes
data_name_basics_purify[data_name_basics_purify.isna().any(axis=1)]

Empty DataFrame
Columns: [primaryName, primaryProfession, knownForTitles]
Index: []

In [18]:
# Enregistrer le fichier corrigé sur l'ordi en tant NON COMPRESSE
data_name_basics_purify.to_csv(r"C:\Users\user\Downloads\Projet ML\Model1(KNN)\Données nettoyées\data_name_basics_purify.csv")

In [19]:
#Chargement du fichier
data_name_basics_purify = pd.read_csv(r"C:\Users\user\Downloads\Projet ML\Model1(KNN)\Données nettoyées\data_name_basics_purify.csv", sep = ",")
data_name_basics_purify

,nconst,primaryName,primaryProfession,knownForTitles
0,nm0000001,Fred Astaire,"soundtrack,actor,miscellaneous","tt0053137,tt0072308,tt0027125,tt0050419"
1,nm0000002,Lauren Bacall,"actress,soundtrack","tt0038355,tt0037382,tt0075213,tt0117057"
2,nm0000003,Brigitte Bardot,"actress,soundtrack,music_department","tt0054452,tt0057345,tt0056404,tt0049189"
3,nm0000004,John Belushi,"actor,soundtrack,writer","tt0078723,tt0077975,tt0072562,tt0080455"
4,nm0000005,Ingmar Bergman,"writer,director,actor","tt0050986,tt0050976,tt0083922,tt0069467"
...,...,...,...,...
5586391,nm9993700,Sexy Angel,actress,tt7523066
5586392,nm9993701,Sanjai Kuriakose,actor,tt8736744
5586393,nm9993703,James Craigmyle,actor,"tt6225166,tt11212278,tt6914160,tt10627062"
5586394,nm9993708,Eli Bevins,"producer,director,writer","tt11772904,tt14508814,tt11772858,tt11702702"
5586395,nm9993709,Lu Bevins,"producer,director,writer","tt11697102,tt11772812,tt17717854,tt11772904"

# Fichier title.rating

In [20]:
pd.read_csv(r"C:\Users\user\Downloads\Projet ML\Model1(KNN)\title.ratings.tsv.gz", sep = "\t", compression = "gzip")

            tconst  averageRating  numVotes
0        tt0000001            5.7      2034
1        tt0000002            5.7       272
2        tt0000003            6.5      1981
3        tt0000004            5.4       178
4        tt0000005            6.2      2739
...            ...            ...       ...
1413874  tt9916730            7.0        12
1413875  tt9916766            7.1        23
1413876  tt9916778            7.2        36
1413877  tt9916840            7.5         7
1413878  tt9916880            8.2         6

[1413879 rows x 3 columns]

In [21]:
data_title_rating=pd.read_csv(r"C:\Users\user\Downloads\Projet ML\Model1(KNN)\title.ratings.tsv.gz", sep = "\t", compression = "gzip")

In [22]:
# Trouver les valeurs manquantes parmi toutes les colonnes 
data_title_rating[data_title_rating.isna().any(axis=1)]

Empty DataFrame
Columns: [tconst, averageRating, numVotes]
Index: []

In [23]:
# Mettre la colonne 'tconst' comme index
data_title_rating = data_title_rating.set_index('tconst') 
data_title_rating

           averageRating  numVotes
tconst
tt0000001            5.7      2034
tt0000002            5.7       272
tt0000003            6.5      1981
tt0000004            5.4       178
tt0000005            6.2      2739
...                  ...       ...
tt9916730            7.0        12
tt9916766            7.1        23
tt9916778            7.2        36
tt9916840            7.5         7
tt9916880            8.2         6

[1413879 rows x 2 columns]

In [24]:
data_title_rating.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1413879 entries, tt0000001 to tt9916880
Data columns (total 2 columns):
 #   Column         Non-Null Count    Dtype
---  ------         --------------    -----
 0   averageRating  1413879 non-null  float64
 1   numVotes       1413879 non-null  int64
dtypes: float64(1), int64(1)
memory usage: 32.4+ MB

In [25]:
# Enregistrer fichier corrigé sur l'ordi en non compressé
data_title_rating.to_csv(r"C:\Users\user\Downloads\Projet ML\Model1(KNN)\Données nettoyées\data_title_rating_nettoye.csv")
data_title_rating_nettoye = pd.read_csv(r"C:\Users\user\Downloads\Projet ML\Model1(KNN)\Données nettoyées\data_title_rating_nettoye.csv", sep = ",")
data_title_rating_nettoye

            tconst  averageRating  numVotes
0        tt0000001            5.7      2034
1        tt0000002            5.7       272
2        tt0000003            6.5      1981
3        tt0000004            5.4       178
4        tt0000005            6.2      2739
...            ...            ...       ...
1413874  tt9916730            7.0        12
1413875  tt9916766            7.1        23
1413876  tt9916778            7.2        36
1413877  tt9916840            7.5         7
1413878  tt9916880            8.2         6

[1413879 rows x 3 columns]

# Fichier title.principal

In [26]:
pd.read_csv(r"C:\Users\user\Downloads\Projet ML\Model1(KNN)\title.principals.tsv.gz",sep="\t",compression="gzip")

,tconst,ordering,nconst,category,job,characters
0,tt0000001,1,nm1588970,self,\N,"[""Self""]"
1,tt0000001,2,nm0005690,director,\N,\N
2,tt0000001,3,nm0374658,cinematographer,director of photography,\N
3,tt0000002,1,nm0721526,director,\N,\N
4,tt0000002,2,nm1335271,composer,\N,\N
...,...,...,...,...,...,...
60892327,tt9916880,5,nm0584014,director,\N,\N
60892328,tt9916880,6,nm0996406,director,principal director,\N
60892329,tt9916880,7,nm1482639,writer,\N,\N
60892330,tt9916880,8,nm2586970,writer,books,\N
60892331,tt9916880,9,nm1594058,producer,producer,\N

In [27]:
data_title_principal=pd.read_csv(r"C:\Users\user\Downloads\Projet ML\Model1(KNN)\title.principals.tsv.gz",sep="\t",compression="gzip")

In [28]:
data_title_principal = data_title_principal.replace('\\N',np.nan)

In [29]:
# Trouver les valeurs manquantes parmi toutes les colonnes 
data_title_principal[data_title_principal.isna().any(axis=1)]

,tconst,ordering,nconst,category,job,characters
0,tt0000001,1,nm1588970,self,NaN,"[""Self""]"
1,tt0000001,2,nm0005690,director,NaN,NaN
2,tt0000001,3,nm0374658,cinematographer,director of photography,NaN
3,tt0000002,1,nm0721526,director,NaN,NaN
4,tt0000002,2,nm1335271,composer,NaN,NaN
...,...,...,...,...,...,...
60892327,tt9916880,5,nm0584014,director,NaN,NaN
60892328,tt9916880,6,nm0996406,director,principal director,NaN
60892329,tt9916880,7,nm1482639,writer,NaN,NaN
60892330,tt9916880,8,nm2586970,writer,books,NaN
60892331,tt9916880,9,nm1594058,producer,producer,NaN

In [30]:
# Mettre la colonne 'tconst' en index
data_title_principal = data_title_principal.set_index('tconst') 
data_title_principal

,ordering,nconst,category,job,characters
tconst,,,,,
tt0000001,1,nm1588970,self,NaN,"[""Self""]"
tt0000001,2,nm0005690,director,NaN,NaN
tt0000001,3,nm0374658,cinematographer,director of photography,NaN
tt0000002,1,nm0721526,director,NaN,NaN
tt0000002,2,nm1335271,composer,NaN,NaN
...,...,...,...,...,...
tt9916880,5,nm0584014,director,NaN,NaN
tt9916880,6,nm0996406,director,principal director,NaN
tt9916880,7,nm1482639,writer,NaN,NaN
tt9916880,8,nm2586970,writer,books,NaN
tt9916880,9,nm1594058,producer,producer,NaN

In [31]:
# AFFICHER TOUTES LES VALEURS UNIQUES DE LA COLONNE 'category'
data_title_principal["category"].unique()

array(['self', 'director', 'cinematographer', 'composer', 'producer',
       'editor', 'actor', 'actress', 'writer', 'production_designer',
       'archive_footage', 'archive_sound'], dtype=object)

In [32]:
# GARDER UNIQUEMENT LES CATEGORY SOUHAITEES 
data_title_principal = data_title_principal[data_title_principal["category"].str.contains('actor|actress|director')]                                             
data_title_principal

,ordering,nconst,category,job,characters
tconst,,,,,
tt0000001,2,nm0005690,director,NaN,NaN
tt0000002,1,nm0721526,director,NaN,NaN
tt0000003,1,nm0721526,director,NaN,NaN
tt0000004,1,nm0721526,director,NaN,NaN
tt0000005,1,nm0443482,actor,NaN,"[""Blacksmith""]"
...,...,...,...,...,...
tt9916880,2,nm1483166,actor,NaN,"[""Rude Ralph"",""Mischievous Mike"",""Jolly Josh""]"
tt9916880,3,nm0254176,actress,NaN,"[""Moody Margaret""]"
tt9916880,4,nm0286175,actor,NaN,"[""Dad"",""Aerobic Al"",""Nasty Nicola""]"
tt9916880,5,nm0584014,director,NaN,NaN
tt9916880,6,nm0996406,director,principal director,NaN

In [33]:
data_title_principal = data_title_principal.drop(['job', 'ordering'], axis=1)
data_title_principal

              nconst  category                                      characters
tconst
tt0000001  nm0005690  director                                             NaN
tt0000002  nm0721526  director                                             NaN
tt0000003  nm0721526  director                                             NaN
tt0000004  nm0721526  director                                             NaN
tt0000005  nm0443482     actor                                  ["Blacksmith"]
...              ...       ...                                             ...
tt9916880  nm1483166     actor  ["Rude Ralph","Mischievous Mike","Jolly Josh"]
tt9916880  nm0254176   actress                              ["Moody Margaret"]
tt9916880  nm0286175     actor             ["Dad","Aerobic Al","Nasty Nicola"]
tt9916880  nm0584014  director                                             NaN
tt9916880  nm0996406  director                                             NaN

[30980325 rows x 3 columns]

In [34]:
# Enregistrer fichier corrigé sur le pc en NON COMPRESSE
data_title_principal.to_csv(r"C:\Users\user\Downloads\Projet ML\Model1(KNN)\Données nettoyées\data_title_principal_nettoye.csv")
#Lire et afficher le fichier
data_title_principal_nettoye = pd.read_csv(r"C:\Users\user\Downloads\Projet ML\Model1(KNN)\Données nettoyées\data_title_principal_nettoye.csv", sep = ",")
data_title_principal_nettoye

,tconst,nconst,category,characters
0,tt0000001,nm0005690,director,NaN
1,tt0000002,nm0721526,director,NaN
2,tt0000003,nm0721526,director,NaN
3,tt0000004,nm0721526,director,NaN
4,tt0000005,nm0443482,actor,"[""Blacksmith""]"
...,...,...,...,...
30980320,tt9916880,nm1483166,actor,"[""Rude Ralph"",""Mischievous Mike"",""Jolly Josh""]"
30980321,tt9916880,nm0254176,actress,"[""Moody Margaret""]"
30980322,tt9916880,nm0286175,actor,"[""Dad"",""Aerobic Al"",""Nasty Nicola""]"
30980323,tt9916880,nm0584014,director,NaN
30980324,tt9916880,nm0996406,director,NaN

# Fichier title.basics

In [35]:
data_title_basics=pd.read_csv(r"C:\Users\user\Downloads\Projet ML\Model1(KNN)\title.basics.tsv.gz",sep="\t",compression="gzip")

C:\Users\user\AppData\Local\Temp\ipykernel_3940\255997175.py:1: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  data_title_basics=pd.read_csv(r"C:\Users\user\Downloads\Projet ML\Model1(KNN)\title.basics.tsv.gz",sep="\t",compression="gzip")

In [36]:
data_title_basics

,tconst,titleType,primaryTitle,originalTitle,isAdult,startYear,endYear,runtimeMinutes,genres
0,tt0000001,short,Carmencita,Carmencita,0,1894,\N,1,"Documentary,Short"
1,tt0000002,short,Le clown et ses chiens,Le clown et ses chiens,0,1892,\N,5,"Animation,Short"
2,tt0000003,short,Pauvre Pierrot,Pauvre Pierrot,0,1892,\N,4,"Animation,Comedy,Romance"
3,tt0000004,short,Un bon bock,Un bon bock,0,1892,\N,12,"Animation,Short"
4,tt0000005,short,Blacksmith Scene,Blacksmith Scene,0,1893,\N,1,"Comedy,Short"
...,...,...,...,...,...,...,...,...,...
10623907,tt9916848,tvEpisode,Episode #3.17,Episode #3.17,0,2009,\N,\N,"Action,Drama,Family"
10623908,tt9916850,tvEpisode,Episode #3.19,Episode #3.19,0,2010,\N,\N,"Action,Drama,Family"
10623909,tt9916852,tvEpisode,Episode #3.20,Episode #3.20,0,2010,\N,\N,"Action,Drama,Family"
10623910,tt9916856,short,The Wind,The Wind,0,2015,\N,27,Short
10623911,tt9916880,tvEpisode,Horrid Henry Knows It All,Horrid Henry Knows It All,0,2014,\N,10,"Adventure,Animation,Comedy"

In [37]:
data_title_basics = data_title_basics.replace('\\N',np.nan)
data_title_basics = data_title_basics.set_index('tconst') 
data_title_basics[data_title_basics.isna().any(axis=1)]

,titleType,primaryTitle,originalTitle,isAdult,startYear,endYear,runtimeMinutes,genres
tconst,,,,,,,,
tt0000001,short,Carmencita,Carmencita,0,1894,NaN,1,"Documentary,Short"
tt0000002,short,Le clown et ses chiens,Le clown et ses chiens,0,1892,NaN,5,"Animation,Short"
tt0000003,short,Pauvre Pierrot,Pauvre Pierrot,0,1892,NaN,4,"Animation,Comedy,Romance"
tt0000004,short,Un bon bock,Un bon bock,0,1892,NaN,12,"Animation,Short"
tt0000005,short,Blacksmith Scene,Blacksmith Scene,0,1893,NaN,1,"Comedy,Short"
...,...,...,...,...,...,...,...,...
tt9916848,tvEpisode,Episode #3.17,Episode #3.17,0,2009,NaN,NaN,"Action,Drama,Family"
tt9916850,tvEpisode,Episode #3.19,Episode #3.19,0,2010,NaN,NaN,"Action,Drama,Family"
tt9916852,tvEpisode,Episode #3.20,Episode #3.20,0,2010,NaN,NaN,"Action,Drama,Family"
tt9916856,short,The Wind,The Wind,0,2015,NaN,27,Short
tt9916880,tvEpisode,Horrid Henry Knows It All,Horrid Henry Knows It All,0,2014,NaN,10,"Adventure,Animation,Comedy"

In [38]:
# Afficher le dataframe
data_title_basics

,titleType,primaryTitle,originalTitle,isAdult,startYear,endYear,runtimeMinutes,genres
tconst,,,,,,,,
tt0000001,short,Carmencita,Carmencita,0,1894,NaN,1,"Documentary,Short"
tt0000002,short,Le clown et ses chiens,Le clown et ses chiens,0,1892,NaN,5,"Animation,Short"
tt0000003,short,Pauvre Pierrot,Pauvre Pierrot,0,1892,NaN,4,"Animation,Comedy,Romance"
tt0000004,short,Un bon bock,Un bon bock,0,1892,NaN,12,"Animation,Short"
tt0000005,short,Blacksmith Scene,Blacksmith Scene,0,1893,NaN,1,"Comedy,Short"
...,...,...,...,...,...,...,...,...
tt9916848,tvEpisode,Episode #3.17,Episode #3.17,0,2009,NaN,NaN,"Action,Drama,Family"
tt9916850,tvEpisode,Episode #3.19,Episode #3.19,0,2010,NaN,NaN,"Action,Drama,Family"
tt9916852,tvEpisode,Episode #3.20,Episode #3.20,0,2010,NaN,NaN,"Action,Drama,Family"
tt9916856,short,The Wind,The Wind,0,2015,NaN,27,Short
tt9916880,tvEpisode,Horrid Henry Knows It All,Horrid Henry Knows It All,0,2014,NaN,10,"Adventure,Animation,Comedy"

In [39]:
# Afficher toutes les valeurs présentes dans la colonne TitleType
data_title_basics.titleType.unique()

array(['short', 'movie', 'tvShort', 'tvMovie', 'tvSeries', 'tvEpisode',
       'tvMiniSeries', 'tvSpecial', 'video', 'videoGame', 'tvPilot'],
      dtype=object)

In [40]:
# Garder uniquement les lignes 'movie' 
data_title_basics = data_title_basics.loc[data_title_basics['titleType'].str.contains('movie')]

In [41]:
# Afficher toutes les valeurs présentes dans la colonne TitleType
data_title_basics.genres.unique()

array(['Romance', 'Documentary,News,Sport', nan, ...,
       'Music,Musical,Reality-TV', 'News,Sport,Talk-Show',
       'Biography,Fantasy,Musical'], dtype=object)

In [42]:
# Supprimer la colonnes endYear 
data_title_basics = data_title_basics.drop(['endYear'], axis=1) 
# Supprimer la colonnes isAdult 
data_title_basics = data_title_basics.drop(['isAdult'], axis=1)

In [43]:
data_title_basics

,titleType,primaryTitle,originalTitle,startYear,runtimeMinutes,genres
tconst,,,,,,
tt0000009,movie,Miss Jerry,Miss Jerry,1894,45,Romance
tt0000147,movie,The Corbett-Fitzsimmons Fight,The Corbett-Fitzsimmons Fight,1897,100,"Documentary,News,Sport"
tt0000502,movie,Bohemios,Bohemios,1905,100,NaN
tt0000574,movie,The Story of the Kelly Gang,The Story of the Kelly Gang,1906,70,"Action,Adventure,Biography"
tt0000591,movie,The Prodigal Son,L'enfant prodigue,1907,90,Drama
...,...,...,...,...,...,...
tt9916622,movie,Rodolpho Teóphilo - O Legado de um Pioneiro,Rodolpho Teóphilo - O Legado de um Pioneiro,2015,57,Documentary
tt9916680,movie,De la ilusión al desconcierto: cine colombiano...,De la ilusión al desconcierto: cine colombiano...,2007,100,Documentary
tt9916706,movie,Dankyavar Danka,Dankyavar Danka,2013,NaN,Comedy
tt9916730,movie,6 Gunn,6 Gunn,2017,116,Drama
tt9916754,movie,Chico Albuquerque - Revelações,Chico Albuquerque - Revelações,2013,49,Documentary

In [44]:
# Remplacer les valeurs nulles par 'Diver'
data_title_basics = data_title_basics.fillna({'genres': 'Divers'})

In [45]:
data_title_basics

,titleType,primaryTitle,originalTitle,startYear,runtimeMinutes,genres
tconst,,,,,,
tt0000009,movie,Miss Jerry,Miss Jerry,1894,45,Romance
tt0000147,movie,The Corbett-Fitzsimmons Fight,The Corbett-Fitzsimmons Fight,1897,100,"Documentary,News,Sport"
tt0000502,movie,Bohemios,Bohemios,1905,100,Divers
tt0000574,movie,The Story of the Kelly Gang,The Story of the Kelly Gang,1906,70,"Action,Adventure,Biography"
tt0000591,movie,The Prodigal Son,L'enfant prodigue,1907,90,Drama
...,...,...,...,...,...,...
tt9916622,movie,Rodolpho Teóphilo - O Legado de um Pioneiro,Rodolpho Teóphilo - O Legado de um Pioneiro,2015,57,Documentary
tt9916680,movie,De la ilusión al desconcierto: cine colombiano...,De la ilusión al desconcierto: cine colombiano...,2007,100,Documentary
tt9916706,movie,Dankyavar Danka,Dankyavar Danka,2013,NaN,Comedy
tt9916730,movie,6 Gunn,6 Gunn,2017,116,Drama
tt9916754,movie,Chico Albuquerque - Revelações,Chico Albuquerque - Revelações,2013,49,Documentary

In [46]:
#Trier par an
data_title_basics.sort_values(by='startYear', ascending = True)

,titleType,primaryTitle,originalTitle,startYear,runtimeMinutes,genres
tconst,,,,,,
tt0000009,movie,Miss Jerry,Miss Jerry,1894,45,Romance
tt2210499,movie,Birmingham,Birmingham,1896,61,Documentary
tt0000147,movie,The Corbett-Fitzsimmons Fight,The Corbett-Fitzsimmons Fight,1897,100,"Documentary,News,Sport"
tt0229676,movie,Reproduction of the Corbett and Fitzsimmons Fight,Reproduction of the Corbett and Fitzsimmons Fight,1897,NaN,"Documentary,News,Sport"
tt0236940,movie,69th Regiment Passing in Review,69th Regiment Passing in Review,1898,NaN,Documentary
...,...,...,...,...,...,...
tt9916100,movie,Inventing Robert Capa,Inventing Robert Capa,NaN,NaN,"Biography,Drama,War"
tt9916134,movie,The Thing in the Bag,The Thing in the Bag,NaN,78,Divers
tt9916178,movie,Yesterday's Dreams,Yesterday's Dreams,NaN,NaN,Divers
tt9916188,movie,Minotaur,Minotaur,NaN,NaN,Thriller
tt9916620,movie,The Copeland Case,The Copeland Case,NaN,NaN,Drama

In [47]:
# Enregistrer fichier corrigé sur l'ordi en format non compressé 
data_title_basics.to_csv(r"C:\Users\user\Downloads\Projet ML\Model1(KNN)\Données nettoyées\data_title_basics_nettoye.csv")
data_title_basics_nettoye = pd.read_csv(r"C:\Users\user\Downloads\Projet ML\Model1(KNN)\Données nettoyées\data_title_basics_nettoye.csv", sep = ",")
data_title_basics_nettoye

,tconst,titleType,primaryTitle,originalTitle,startYear,runtimeMinutes,genres
0,tt0000009,movie,Miss Jerry,Miss Jerry,1894.0,45.0,Romance
1,tt0000147,movie,The Corbett-Fitzsimmons Fight,The Corbett-Fitzsimmons Fight,1897.0,100.0,"Documentary,News,Sport"
2,tt0000502,movie,Bohemios,Bohemios,1905.0,100.0,Divers
3,tt0000574,movie,The Story of the Kelly Gang,The Story of the Kelly Gang,1906.0,70.0,"Action,Adventure,Biography"
4,tt0000591,movie,The Prodigal Son,L'enfant prodigue,1907.0,90.0,Drama
...,...,...,...,...,...,...,...
674547,tt9916622,movie,Rodolpho Teóphilo - O Legado de um Pioneiro,Rodolpho Teóphilo - O Legado de um Pioneiro,2015.0,57.0,Documentary
674548,tt9916680,movie,De la ilusión al desconcierto: cine colombiano...,De la ilusión al desconcierto: cine colombiano...,2007.0,100.0,Documentary
674549,tt9916706,movie,Dankyavar Danka,Dankyavar Danka,2013.0,NaN,Comedy
674550,tt9916730,movie,6 Gunn,6 Gunn,2017.0,116.0,Drama
674551,tt9916754,movie,Chico Albuquerque - Revelações,Chico Albuquerque - Revelações,2013.0,49.0,Documentary

# Fichier title.akas

In [48]:
data_title_akas = pd.read_csv(r"C:\Users\user\Downloads\Projet ML\Model1(KNN)\title.akas.tsv.gz", sep = "\t", compression = "gzip")
data_title_akas

C:\Users\user\AppData\Local\Temp\ipykernel_3940\1445213044.py:1: DtypeWarning: Columns (7) have mixed types. Specify dtype option on import or set low_memory=False.
  data_title_akas = pd.read_csv(r"C:\Users\user\Downloads\Projet ML\Model1(KNN)\title.akas.tsv.gz", sep = "\t", compression = "gzip")

,titleId,ordering,title,region,language,types,attributes,isOriginalTitle
0,tt0000001,1,Карменсіта,UA,\N,imdbDisplay,\N,0
1,tt0000001,2,Carmencita,DE,\N,\N,literal title,0
2,tt0000001,3,Carmencita - spanyol tánc,HU,\N,imdbDisplay,\N,0
3,tt0000001,4,Καρμενσίτα,GR,\N,imdbDisplay,\N,0
4,tt0000001,5,Карменсита,RU,\N,imdbDisplay,\N,0
...,...,...,...,...,...,...,...,...
38914764,tt9916852,5,Episódio #3.20,PT,pt,\N,\N,0
38914765,tt9916852,6,Episodio #3.20,IT,it,\N,\N,0
38914766,tt9916852,7,एपिसोड #3.20,IN,hi,\N,\N,0
38914767,tt9916856,1,The Wind,DE,\N,imdbDisplay,\N,0
38914768,tt9916856,2,The Wind,\N,\N,original,\N,1

In [49]:
data_title_akas =data_title_akas.replace('\\N',np.nan)
data_title_akas[data_title_akas.isna().any(axis=1)]

,titleId,ordering,title,region,language,types,attributes,isOriginalTitle
0,tt0000001,1,Карменсіта,UA,NaN,imdbDisplay,NaN,0
1,tt0000001,2,Carmencita,DE,NaN,NaN,literal title,0
2,tt0000001,3,Carmencita - spanyol tánc,HU,NaN,imdbDisplay,NaN,0
3,tt0000001,4,Καρμενσίτα,GR,NaN,imdbDisplay,NaN,0
4,tt0000001,5,Карменсита,RU,NaN,imdbDisplay,NaN,0
...,...,...,...,...,...,...,...,...
38914764,tt9916852,5,Episódio #3.20,PT,pt,NaN,NaN,0
38914765,tt9916852,6,Episodio #3.20,IT,it,NaN,NaN,0
38914766,tt9916852,7,एपिसोड #3.20,IN,hi,NaN,NaN,0
38914767,tt9916856,1,The Wind,DE,NaN,imdbDisplay,NaN,0
38914768,tt9916856,2,The Wind,NaN,NaN,original,NaN,1

In [50]:
data_title_akas

,titleId,ordering,title,region,language,types,attributes,isOriginalTitle
0,tt0000001,1,Карменсіта,UA,NaN,imdbDisplay,NaN,0
1,tt0000001,2,Carmencita,DE,NaN,NaN,literal title,0
2,tt0000001,3,Carmencita - spanyol tánc,HU,NaN,imdbDisplay,NaN,0
3,tt0000001,4,Καρμενσίτα,GR,NaN,imdbDisplay,NaN,0
4,tt0000001,5,Карменсита,RU,NaN,imdbDisplay,NaN,0
...,...,...,...,...,...,...,...,...
38914764,tt9916852,5,Episódio #3.20,PT,pt,NaN,NaN,0
38914765,tt9916852,6,Episodio #3.20,IT,it,NaN,NaN,0
38914766,tt9916852,7,एपिसोड #3.20,IN,hi,NaN,NaN,0
38914767,tt9916856,1,The Wind,DE,NaN,imdbDisplay,NaN,0
38914768,tt9916856,2,The Wind,NaN,NaN,original,NaN,1

In [51]:
#AFFICHER TOUTES LES VALEURS UNIQUES DE LA COLONNE 'region'
data_title_akas["region"].unique()

array(['UA', 'DE', 'HU', 'GR', 'RU', 'US', nan, 'JP', 'FR', 'RO', 'GB',
       'CA', 'PT', 'AU', 'ES', 'FI', 'PL', 'RS', 'AR', 'UY', 'IT', 'BR',
       'DK', 'TR', 'XWW', 'XEU', 'SK', 'CZ', 'SE', 'NZ', 'KZ', 'MX', 'NO',
       'XYU', 'AT', 'VE', 'CSHH', 'SI', 'SUHH', 'IN', 'HR', 'NL', 'LT',
       'CN', 'TW', 'CO', 'IR', 'BG', 'SG', 'BE', 'EC', 'VN', 'PH', 'DZ',
       'CH', 'BF', 'XWG', 'HK', 'XSA', 'EE', 'IS', 'PR', 'DDDE', 'IL',
       'EG', 'XKO', 'CL', 'IE', 'JM', 'KR', 'PE', 'GE', 'BY', 'BA', 'DO',
       'AE', 'PA', 'TH', 'ZA', 'TJ', 'XSI', 'MY', 'LV', 'ID', 'PK', 'BD',
       'CU', 'AL', 'BO', 'XAS', 'CR', 'PY', 'GT', 'SV', 'KP', 'UZ',
       'BUMM', 'MM', 'YUCS', 'XPI', 'BJ', 'AZ', 'NG', 'CM', 'MA', 'GL',
       'MN', 'LI', 'LU', 'MZ', 'MK', 'BM', 'MD', 'ME', 'LB', 'IQ', 'TM',
       'TN', 'HT', 'AM', 'LK', 'CG', 'CI', 'SY', 'NP', 'QA', 'TO', 'SN',
       'GH', 'JO', 'KG', 'NE', 'GN', 'VDVN', 'TD', 'SO', 'SD', 'MC', 'TT',
       'GA', 'BS', 'LY', 'AO', 'KH', 'MR', 'AF', 'MG', 'ML', 'GY', 'CY',
       'ET', 'GU', 'SR', 'MT', 'TG', 'PG', 'MU', 'BI', 'CF', 'NI', 'ZW',
       'ZM', 'GW', 'DJ', 'RW', 'TZ', 'GI', 'LA', 'SC', 'GP', 'XAU', 'FO',
       'PS', 'ZRCD', 'MO', 'AW', 'KW', 'CV', 'SL', 'SM', 'CD', 'BT', 'LS',
       'HN', 'KE', 'MQ', 'AD', 'ER', 'SA', 'CSXX', 'IM', 'XKV', 'BH',
       'BB', 'BZ', 'UG', 'AG', 'NU', 'OM', 'BW', 'LR', 'AN', 'MV', 'YE',
       'GM', 'KY', 'NC', 'DM', 'TL', 'MP', 'VA', 'GQ', 'FJ', 'SZ', 'RE',
       'EH', 'PF', 'VG', 'LC', 'MW', 'BN', 'ST', 'KM', 'FM', 'AI', 'GD',
       'VI', 'SB', 'GF', 'AQ', 'MH', 'CW', 'WS', 'VC', 'AS', 'XNA', 'MS',
       'VU', 'SH', 'KI', 'KN', 'CC', 'TC', 'TV', 'CK', 'PW', 'NR', 'JE'],
      dtype=object)

In [52]:
data_french_films = data_title_akas[data_title_akas['region'] == 'FR']
data_french_films

,titleId,ordering,title,region,language,types,attributes,isOriginalTitle
9,tt0000002,2,Le clown et ses chiens,FR,NaN,imdbDisplay,NaN,0
23,tt0000003,8,Pauvre Pierrot,FR,NaN,imdbDisplay,NaN,0
26,tt0000004,2,Un bon bock,FR,NaN,imdbDisplay,NaN,0
83,tt0000010,16,La sortie de l'usine Lumière,FR,NaN,alternative,NaN,0
85,tt0000010,18,La sortie des usines Lumière,FR,NaN,alternative,NaN,0
...,...,...,...,...,...,...,...,...
38914735,tt9916844,4,Épisode #3.15,FR,fr,NaN,NaN,0
38914739,tt9916846,1,Épisode #3.18,FR,fr,NaN,NaN,0
38914746,tt9916848,1,Épisode #3.17,FR,fr,NaN,NaN,0
38914755,tt9916850,3,Épisode #3.19,FR,fr,NaN,NaN,0
38914761,tt9916852,2,Épisode #3.20,FR,fr,NaN,NaN,0

In [53]:
#Supprimer les colonnes 'ordering', 'language', 'types', 'attributes', 'isOriginalTitle', 'region'
data_french_films = data_french_films.drop(['ordering', 'language', 'types', 'attributes', 'isOriginalTitle', 'region'], axis = 1)
#Renommer la colonne title par French_Title
data_french_films=data_french_films.rename(columns={"title": "French_Title"})
data_french_films

            titleId                  French_Title
9         tt0000002        Le clown et ses chiens
23        tt0000003                Pauvre Pierrot
26        tt0000004                   Un bon bock
83        tt0000010  La sortie de l'usine Lumière
85        tt0000010  La sortie des usines Lumière
...             ...                           ...
38914735  tt9916844                 Épisode #3.15
38914739  tt9916846                 Épisode #3.18
38914746  tt9916848                 Épisode #3.17
38914755  tt9916850                 Épisode #3.19
38914761  tt9916852                 Épisode #3.20

[4671546 rows x 2 columns]

In [54]:
#Enregistrer les deux fichiers
data_title_akas.to_csv(r"C:\Users\user\Downloads\Projet ML\Model1(KNN)\Données nettoyées\data_title_akas_nettoye.csv")
data_french_films.to_csv(r"C:\Users\user\Downloads\Projet ML\Model1(KNN)\Données nettoyées\data_title_akas_nettoye_FR.csv")

In [55]:
data_title_akas_nettoye = pd.read_csv('data_title_akas_nettoye.csv',sep=",")
data_title_akas_nettoye

C:\Users\user\AppData\Local\Temp\ipykernel_3940\162063834.py:1: DtypeWarning: Columns (7) have mixed types. Specify dtype option on import or set low_memory=False.
  data_title_akas_nettoye = pd.read_csv('data_title_akas_nettoye.csv',sep=",")

,Unnamed: 0,titleId,ordering,title,region,language,types,attributes,isOriginalTitle
0,0,tt0000001,1,Карменсіта,UA,NaN,imdbDisplay,NaN,0.0
1,1,tt0000001,2,Carmencita,DE,NaN,NaN,literal title,0.0
2,2,tt0000001,3,Carmencita - spanyol tánc,HU,NaN,imdbDisplay,NaN,0.0
3,3,tt0000001,4,Καρμενσίτα,GR,NaN,imdbDisplay,NaN,0.0
4,4,tt0000001,5,Карменсита,RU,NaN,imdbDisplay,NaN,0.0
...,...,...,...,...,...,...,...,...,...
38914764,38914764,tt9916852,5,Episódio #3.20,PT,pt,NaN,NaN,0.0
38914765,38914765,tt9916852,6,Episodio #3.20,IT,it,NaN,NaN,0.0
38914766,38914766,tt9916852,7,एपिसोड #3.20,IN,hi,NaN,NaN,0.0
38914767,38914767,tt9916856,1,The Wind,DE,NaN,imdbDisplay,NaN,0.0
38914768,38914768,tt9916856,2,The Wind,NaN,NaN,original,NaN,1.0

In [56]:
data_title_akas_nettoye_FR = pd.read_csv('data_title_akas_nettoye_FR.csv',sep=",")
data_title_akas_nettoye_FR

         Unnamed: 0    titleId                  French_Title
0                 9  tt0000002        Le clown et ses chiens
1                23  tt0000003                Pauvre Pierrot
2                26  tt0000004                   Un bon bock
3                83  tt0000010  La sortie de l'usine Lumière
4                85  tt0000010  La sortie des usines Lumière
...             ...        ...                           ...
4671541    38914735  tt9916844                 Épisode #3.15
4671542    38914739  tt9916846                 Épisode #3.18
4671543    38914746  tt9916848                 Épisode #3.17
4671544    38914755  tt9916850                 Épisode #3.19
4671545    38914761  tt9916852                 Épisode #3.20

[4671546 rows x 3 columns]

# FUSION title akas+basic

In [57]:
# Fusion du fichier title basics et title akas
import pandas as pd
import numpy as np
fusion_titlebasics_titleakas = pd.merge(data_title_basics_nettoye, data_title_akas_nettoye_FR, 
         how="left",     
         left_on='tconst',
         right_on='titleId')

In [58]:
fusion_titlebasics_titleakas = fusion_titlebasics_titleakas.drop('titleId', axis = 1)

In [59]:
fusion_titlebasics_titleakas

,tconst,titleType,primaryTitle,originalTitle,startYear,runtimeMinutes,genres,Unnamed: 0,French_Title
0,tt0000009,movie,Miss Jerry,Miss Jerry,1894.0,45.0,Romance,NaN,NaN
1,tt0000147,movie,The Corbett-Fitzsimmons Fight,The Corbett-Fitzsimmons Fight,1897.0,100.0,"Documentary,News,Sport",NaN,NaN
2,tt0000502,movie,Bohemios,Bohemios,1905.0,100.0,Divers,NaN,NaN
3,tt0000574,movie,The Story of the Kelly Gang,The Story of the Kelly Gang,1906.0,70.0,"Action,Adventure,Biography",NaN,NaN
4,tt0000591,movie,The Prodigal Son,L'enfant prodigue,1907.0,90.0,Drama,2356.0,L'enfant prodigue
...,...,...,...,...,...,...,...,...,...
684352,tt9916622,movie,Rodolpho Teóphilo - O Legado de um Pioneiro,Rodolpho Teóphilo - O Legado de um Pioneiro,2015.0,57.0,Documentary,NaN,NaN
684353,tt9916680,movie,De la ilusión al desconcierto: cine colombiano...,De la ilusión al desconcierto: cine colombiano...,2007.0,100.0,Documentary,NaN,NaN
684354,tt9916706,movie,Dankyavar Danka,Dankyavar Danka,2013.0,NaN,Comedy,NaN,NaN
684355,tt9916730,movie,6 Gunn,6 Gunn,2017.0,116.0,Drama,NaN,NaN
684356,tt9916754,movie,Chico Albuquerque - Revelações,Chico Albuquerque - Revelações,2013.0,49.0,Documentary,NaN,NaN

#  FUSION title akas+basic et title rating

In [60]:
#Fusion du fichier title basics,title akas et title rating
fusion_titlebasic_titlerating = pd.merge(fusion_titlebasics_titleakas, data_title_rating_nettoye, 
         how="left",     
         left_on='tconst',
         right_on='tconst')

In [61]:
fusion_titlebasic_titlerating

,tconst,titleType,primaryTitle,originalTitle,startYear,runtimeMinutes,genres,Unnamed: 0,French_Title,averageRating,numVotes
0,tt0000009,movie,Miss Jerry,Miss Jerry,1894.0,45.0,Romance,NaN,NaN,5.3,209.0
1,tt0000147,movie,The Corbett-Fitzsimmons Fight,The Corbett-Fitzsimmons Fight,1897.0,100.0,"Documentary,News,Sport",NaN,NaN,5.2,506.0
2,tt0000502,movie,Bohemios,Bohemios,1905.0,100.0,Divers,NaN,NaN,4.1,15.0
3,tt0000574,movie,The Story of the Kelly Gang,The Story of the Kelly Gang,1906.0,70.0,"Action,Adventure,Biography",NaN,NaN,6.0,876.0
4,tt0000591,movie,The Prodigal Son,L'enfant prodigue,1907.0,90.0,Drama,2356.0,L'enfant prodigue,5.5,23.0
...,...,...,...,...,...,...,...,...,...,...,...
684352,tt9916622,movie,Rodolpho Teóphilo - O Legado de um Pioneiro,Rodolpho Teóphilo - O Legado de um Pioneiro,2015.0,57.0,Documentary,NaN,NaN,NaN,NaN
684353,tt9916680,movie,De la ilusión al desconcierto: cine colombiano...,De la ilusión al desconcierto: cine colombiano...,2007.0,100.0,Documentary,NaN,NaN,NaN,NaN
684354,tt9916706,movie,Dankyavar Danka,Dankyavar Danka,2013.0,NaN,Comedy,NaN,NaN,7.6,5.0
684355,tt9916730,movie,6 Gunn,6 Gunn,2017.0,116.0,Drama,NaN,NaN,7.0,12.0
684356,tt9916754,movie,Chico Albuquerque - Revelações,Chico Albuquerque - Revelações,2013.0,49.0,Documentary,NaN,NaN,NaN,NaN

In [62]:
#affiche l'ensemble des données statistiques de la colonne numVotes
fusion_titlebasic_titlerating.numVotes.describe()

count    3.149670e+05
mean     3.888512e+03
std      3.735877e+04
min      5.000000e+00
25%      1.900000e+01
50%      6.400000e+01
75%      3.400000e+02
max      2.870332e+06
Name: numVotes, dtype: float64

In [63]:
#affiche l'ensemble des données statistiques de la colonne averageRating
fusion_titlebasic_titlerating.averageRating.describe()

count    314967.000000
mean          6.165456
std           1.369830
min           1.000000
25%           5.300000
50%           6.300000
75%           7.100000
max          10.000000
Name: averageRating, dtype: float64

In [64]:
#affiche l'ensemble des données statistiques de la colonne runtimeMinutes
fusion_titlebasic_titlerating.runtimeMinutes.describe()

count    433790.000000
mean         89.876039
std         144.877857
min           1.000000
25%          73.000000
50%          89.000000
75%         100.000000
max       54321.000000
Name: runtimeMinutes, dtype: float64

# On garde uniquement les films > 80 min, les films avec des notes > 7.1, les films avec plus de 318 votes

In [65]:
fusion_titlebasic_titlerating = fusion_titlebasic_titlerating [
                        (fusion_titlebasic_titlerating['runtimeMinutes']>80) & 
                        (fusion_titlebasic_titlerating['averageRating']>7.1) &
                        (fusion_titlebasic_titlerating['numVotes']>318) ]

In [66]:
#On transforme la colonne startyear en integer
fusion_titlebasic_titlerating = fusion_titlebasic_titlerating.astype({'startYear' : 'int'})
fusion_titlebasic_titlerating

,tconst,titleType,primaryTitle,originalTitle,startYear,runtimeMinutes,genres,Unnamed: 0,French_Title,averageRating,numVotes
480,tt0003883,movie,L'enfant de Paris,L'enfant de Paris,1913,124.0,"Crime,Drama",11535.0,L'Enfant de Paris,7.2,446.0
1499,tt0006206,movie,Les vampires,Les vampires,1915,421.0,"Action,Adventure,Crime",18854.0,Les vampires,7.3,5398.0
1877,tt0006864,movie,Intolerance,Intolerance: Love's Struggle Throughout the Ages,1916,163.0,"Drama,History",21087.0,Intolérance,7.7,16642.0
1893,tt0006886,movie,Judex,Judex,1916,300.0,"Adventure,Crime",21159.0,Judex,7.2,1117.0
4117,tt0009968,movie,Broken Blossoms,Broken Blossoms or The Yellow Man and the Girl,1919,90.0,"Drama,Romance",32134.0,Le lys brisé,7.2,11014.0
...,...,...,...,...,...,...,...,...,...,...,...
684084,tt9900782,movie,Kaithi,Kaithi,2019,145.0,"Action,Crime,Drama",38883269.0,Kaithi,8.4,42096.0
684148,tt9904844,movie,Ott Tänak: The Movie,Ott Tänak: The Movie,2019,125.0,"Documentary,Sport",NaN,NaN,8.1,501.0
684158,tt9905462,movie,Pengalila,Pengalila,2019,111.0,Drama,NaN,NaN,7.6,680.0
684274,tt9911196,movie,The Marriage Escape,De beentjes van Sint-Hildegard,2020,103.0,"Comedy,Drama",38903533.0,De Beentjes van Sint-Hildegard,7.4,3306.0
684278,tt9911774,movie,Padmavyuhathile Abhimanyu,Padmavyuhathile Abhimanyu,2019,130.0,Drama,NaN,NaN,8.5,380.0

In [67]:
fusion_titlebasic_titlerating.info()

<class 'pandas.core.frame.DataFrame'>
Index: 13094 entries, 480 to 684278
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   tconst          13094 non-null  object
 1   titleType       13094 non-null  object
 2   primaryTitle    13094 non-null  object
 3   originalTitle   13094 non-null  object
 4   startYear       13094 non-null  int32
 5   runtimeMinutes  13094 non-null  float64
 6   genres          13094 non-null  object
 7   Unnamed: 0      7523 non-null   float64
 8   French_Title    7523 non-null   object
 9   averageRating   13094 non-null  float64
 10  numVotes        13094 non-null  float64
dtypes: float64(4), int32(1), object(6)
memory usage: 1.1+ MB

# Travail sur les genres

In [68]:
# regrouper les genres par catégorie, les compter et les classer du plus grand au plus petit : en affichant uniquement les 60 premières catégories
fusion_titlebasic_titlerating.groupby(by = 'genres')['genres'].count().sort_values(ascending = False)[:60]

genres
Drama                            1938
Documentary                       887
Drama,Romance                     696
Comedy,Drama                      678
Comedy                            392
Comedy,Drama,Romance              384
Documentary,Music                 235
Crime,Drama                       230
Action,Crime,Drama                221
Crime,Drama,Thriller              199
Drama,War                         191
Comedy,Romance                    173
Biography,Documentary             165
Biography,Drama,History           160
Drama,Thriller                    158
Crime,Drama,Mystery               137
Action,Adventure,Drama            123
Biography,Drama                   119
Action,Adventure,Animation        112
Drama,History                     110
Biography,Documentary,Music       105
Comedy,Crime,Drama                104
Documentary,Sport                 104
Action,Drama                      100
Biography,Documentary,History      98
Documentary,History                92
Adventure,Animation,Comedy         88
Action,Crime,Thriller              87
Comedy,Drama,Family                86
Crime,Drama,Film-Noir              85
Drama,Family                       83
Drama,Romance,War                  79
Crime,Drama,Romance                75
Biography,Crime,Drama              69
Action,Drama,History               69
Adventure,Comedy,Drama             66
Comedy,Drama,Fantasy               65
Comedy,Drama,Music                 64
Action,Comedy,Drama                56
Drama,History,War                  56
Drama,Mystery,Thriller             56
Action,Comedy,Crime                55
Action,Drama,Thriller              54
Biography,Comedy,Drama             53
Drama,Music                        53
Drama,Musical,Romance              53
Thriller                           52
Biography,Documentary,Sport        51
Comedy,Drama,Musical               46
Comedy,Crime                       46
Action,Adventure,Comedy            46
Drama,Mystery                      45
Romance                            45
Crime,Documentary                  44
Adventure,Drama                    44
Drama,History,Romance              43
Drama,Sport                        43
Documentary,Drama                  41
Biography,Drama,Music              41
Action,Drama,Romance               41
Name: genres, dtype: int64

In [69]:
# Enregistrer le fichier corrigé sur l'ordi sous format non compressé
fusion_titlebasic_titlerating.to_csv(r"C:\Users\user\Downloads\Projet ML\Model1(KNN)\Données nettoyées\fusion_titlebasic_titlerating.csv", index= False )

In [70]:
fusion_titlebasic_titlerating =pd.read_csv(r"C:\Users\user\Downloads\Projet ML\Model1(KNN)\Données nettoyées\fusion_titlebasic_titlerating.csv", sep = ",")
fusion_titlebasic_titlerating

,tconst,titleType,primaryTitle,originalTitle,startYear,runtimeMinutes,genres,Unnamed: 0,French_Title,averageRating,numVotes
0,tt0003883,movie,L'enfant de Paris,L'enfant de Paris,1913,124.0,"Crime,Drama",11535.0,L'Enfant de Paris,7.2,446.0
1,tt0006206,movie,Les vampires,Les vampires,1915,421.0,"Action,Adventure,Crime",18854.0,Les vampires,7.3,5398.0
2,tt0006864,movie,Intolerance,Intolerance: Love's Struggle Throughout the Ages,1916,163.0,"Drama,History",21087.0,Intolérance,7.7,16642.0
3,tt0006886,movie,Judex,Judex,1916,300.0,"Adventure,Crime",21159.0,Judex,7.2,1117.0
4,tt0009968,movie,Broken Blossoms,Broken Blossoms or The Yellow Man and the Girl,1919,90.0,"Drama,Romance",32134.0,Le lys brisé,7.2,11014.0
...,...,...,...,...,...,...,...,...,...,...,...
13089,tt9900782,movie,Kaithi,Kaithi,2019,145.0,"Action,Crime,Drama",38883269.0,Kaithi,8.4,42096.0
13090,tt9904844,movie,Ott Tänak: The Movie,Ott Tänak: The Movie,2019,125.0,"Documentary,Sport",NaN,NaN,8.1,501.0
13091,tt9905462,movie,Pengalila,Pengalila,2019,111.0,Drama,NaN,NaN,7.6,680.0
13092,tt9911196,movie,The Marriage Escape,De beentjes van Sint-Hildegard,2020,103.0,"Comedy,Drama",38903533.0,De Beentjes van Sint-Hildegard,7.4,3306.0
13093,tt9911774,movie,Padmavyuhathile Abhimanyu,Padmavyuhathile Abhimanyu,2019,130.0,Drama,NaN,NaN,8.5,380.0

In [71]:
# Trouver les valeurs manquantes parmi toutes les colonnes
fusion_titlebasic_titlerating[fusion_titlebasic_titlerating.isna().any(axis=1)]

,tconst,titleType,primaryTitle,originalTitle,startYear,runtimeMinutes,genres,Unnamed: 0,French_Title,averageRating,numVotes
33,tt0015268,movie,The Red Lily,The Red Lily,1924,81.0,Drama,NaN,NaN,7.2,498.0
59,tt0017750,movie,Chicago,Chicago,1927,105.0,"Comedy,Crime,Drama",NaN,NaN,7.3,532.0
105,tt0020585,movie,Why Be Good?,Why Be Good?,1929,84.0,"Comedy,Drama,Musical",NaN,NaN,7.2,532.0
118,tt0021873,movie,Five Star Final,Five Star Final,1931,89.0,"Crime,Drama",NaN,NaN,7.3,2496.0
127,tt0022360,movie,Seed,Seed,1931,96.0,Drama,NaN,NaN,7.3,604.0
...,...,...,...,...,...,...,...,...,...,...,...
13087,tt9894394,movie,Upin & Ipin: Keris Siamang Tunggal,Upin & Ipin: Keris siamang tunggal,2019,100.0,"Adventure,Animation,Comedy",NaN,NaN,7.3,829.0
13088,tt9896252,movie,Killing Patient Zero,Killing Patient Zero,2019,100.0,"Documentary,History",NaN,NaN,7.5,319.0
13090,tt9904844,movie,Ott Tänak: The Movie,Ott Tänak: The Movie,2019,125.0,"Documentary,Sport",NaN,NaN,8.1,501.0
13091,tt9905462,movie,Pengalila,Pengalila,2019,111.0,Drama,NaN,NaN,7.6,680.0
13093,tt9911774,movie,Padmavyuhathile Abhimanyu,Padmavyuhathile Abhimanyu,2019,130.0,Drama,NaN,NaN,8.5,380.0

# FUSION name basic et title principal

In [72]:
# FUSION de name_basics et title_principal dans fusion_titlebasic_titlerating
fusion_namebasic_titleprincipal = pd.merge(data_title_principal_nettoye, data_name_basics_purify, 
         how="left",     
         left_on='nconst',
         right_on='nconst')
fusion_namebasic_titleprincipal

,tconst,nconst,category,characters,primaryName,primaryProfession,knownForTitles
0,tt0000001,nm0005690,director,NaN,William K.L. Dickson,"cinematographer,director,producer","tt0308254,tt0219560,tt1496763,tt1428455"
1,tt0000002,nm0721526,director,NaN,Émile Reynaud,"director,animation_department,producer","tt16763674,tt16763740,tt13125956,tt0000003"
2,tt0000003,nm0721526,director,NaN,Émile Reynaud,"director,animation_department,producer","tt16763674,tt16763740,tt13125956,tt0000003"
3,tt0000004,nm0721526,director,NaN,Émile Reynaud,"director,animation_department,producer","tt16763674,tt16763740,tt13125956,tt0000003"
4,tt0000005,nm0443482,actor,"[""Blacksmith""]",NaN,NaN,NaN
...,...,...,...,...,...,...,...
30980320,tt9916880,nm1483166,actor,"[""Rude Ralph"",""Mischievous Mike"",""Jolly Josh""]",Aidan Cook,"actor,miscellaneous,special_effects","tt2527338,tt2488496,tt3748528,tt3778644"
30980321,tt9916880,nm0254176,actress,"[""Moody Margaret""]",Sue Elliott-Nichols,actress,"tt0985991,tt6941630,tt6217830,tt1983079"
30980322,tt9916880,nm0286175,actor,"[""Dad"",""Aerobic Al"",""Nasty Nicola""]",Wayne Forester,"actor,sound_department,special_effects","tt1710626,tt0453557,tt1699440,tt1135081"
30980323,tt9916880,nm0584014,director,NaN,Kevin Micallef,"animation_department,director,art_department","tt0181739,tt0275847,tt2130507,tt0901176"
30980324,tt9916880,nm0996406,director,NaN,Hilary Audus,"director,animation_department,art_department","tt0286490,tt2560206,tt0090315,tt0082509"

In [73]:
#Supprimer les valeurs manquantes
fusion_namebasic_titleprincipal1 = fusion_namebasic_titleprincipal.dropna()
fusion_namebasic_titleprincipal1 = fusion_namebasic_titleprincipal1.groupby(['tconst']).agg({'primaryName': ','.join})
fusion_namebasic_titleprincipal1 = fusion_namebasic_titleprincipal1.reset_index()
fusion_namebasic_titleprincipal1

            tconst                                        primaryName
0        tt0000008                                           Fred Ott
1        tt0000009   Blanche Bayliss,William Courtenay,Chauncey Depew
2        tt0000014                        François Clerc,Benoît Duval
3        tt0000018                                           Delaware
4        tt0000026                     Antoine Féraud,Félicien Trewey
...            ...                                                ...
4620986  tt9916848   Pelin Akil,Sarp Akkaya,Ilter Akçebe,Zeynep Alkan
4620987  tt9916850   Pelin Akil,Sarp Akkaya,Ilter Akçebe,Zeynep Alkan
4620988  tt9916852   Pelin Akil,Sarp Akkaya,Ilter Akçebe,Zeynep Alkan
4620989  tt9916856  Leni Wesselman,Anna Fitoussi,Andreas Demmel,Ka...
4620990  tt9916880  Lizzie Waterworth,Aidan Cook,Sue Elliott-Nicho...

[4620991 rows x 2 columns]

In [74]:
# Enregistrer le fichier corrigé sur l'ordi en non compressé
fusion_namebasic_titleprincipal1.to_csv(r"C:\Users\user\Downloads\Projet ML\Model1(KNN)\Données nettoyées\fusion_namebasic_titleprincipal1.csv", index= False)

In [75]:
#Charger le fichier
fusion_namebasic_titleprincipal1 = pd.read_csv(r"C:\Users\user\Downloads\Projet ML\Model1(KNN)\Données nettoyées\fusion_namebasic_titleprincipal1.csv", sep = ",")
fusion_namebasic_titleprincipal1

            tconst                                        primaryName
0        tt0000008                                           Fred Ott
1        tt0000009   Blanche Bayliss,William Courtenay,Chauncey Depew
2        tt0000014                        François Clerc,Benoît Duval
3        tt0000018                                           Delaware
4        tt0000026                     Antoine Féraud,Félicien Trewey
...            ...                                                ...
4620986  tt9916848   Pelin Akil,Sarp Akkaya,Ilter Akçebe,Zeynep Alkan
4620987  tt9916850   Pelin Akil,Sarp Akkaya,Ilter Akçebe,Zeynep Alkan
4620988  tt9916852   Pelin Akil,Sarp Akkaya,Ilter Akçebe,Zeynep Alkan
4620989  tt9916856  Leni Wesselman,Anna Fitoussi,Andreas Demmel,Ka...
4620990  tt9916880  Lizzie Waterworth,Aidan Cook,Sue Elliott-Nicho...

[4620991 rows x 2 columns]

In [76]:
#les valeurs manquantes parmi toutes les colonnes
fusion_namebasic_titleprincipal[fusion_namebasic_titleprincipal.isna().any(axis=1)]

,tconst,nconst,category,characters,primaryName,primaryProfession,knownForTitles
0,tt0000001,nm0005690,director,NaN,William K.L. Dickson,"cinematographer,director,producer","tt0308254,tt0219560,tt1496763,tt1428455"
1,tt0000002,nm0721526,director,NaN,Émile Reynaud,"director,animation_department,producer","tt16763674,tt16763740,tt13125956,tt0000003"
2,tt0000003,nm0721526,director,NaN,Émile Reynaud,"director,animation_department,producer","tt16763674,tt16763740,tt13125956,tt0000003"
3,tt0000004,nm0721526,director,NaN,Émile Reynaud,"director,animation_department,producer","tt16763674,tt16763740,tt13125956,tt0000003"
4,tt0000005,nm0443482,actor,"[""Blacksmith""]",NaN,NaN,NaN
...,...,...,...,...,...,...,...
30980308,tt9916850,nm1485677,director,NaN,Hamdi Alkan,"director,actor,producer","tt1289683,tt1134549,tt8586316,tt7230418"
30980313,tt9916852,nm1485677,director,NaN,Hamdi Alkan,"director,actor,producer","tt1289683,tt1134549,tt8586316,tt7230418"
30980318,tt9916856,nm10538645,director,NaN,Johan Planefeldt,director,tt9916856
30980323,tt9916880,nm0584014,director,NaN,Kevin Micallef,"animation_department,director,art_department","tt0181739,tt0275847,tt2130507,tt0901176"
30980324,tt9916880,nm0996406,director,NaN,Hilary Audus,"director,animation_department,art_department","tt0286490,tt2560206,tt0090315,tt0082509"

# FUSION de nos deux fusions : title_basics, title_rating, name_basics,title_principal

In [77]:
# Fusionner fusion_titlebasic_titlerating and fusion_titleprincipals_namebasic1 dans fusion_final

fusion_final = pd.merge(fusion_titlebasic_titlerating, fusion_namebasic_titleprincipal1, 
         how="left",     
         left_on='tconst',
         right_on='tconst')

In [78]:
fusion_final

,tconst,titleType,primaryTitle,originalTitle,startYear,runtimeMinutes,genres,Unnamed: 0,French_Title,averageRating,numVotes,primaryName
0,tt0003883,movie,L'enfant de Paris,L'enfant de Paris,1913,124.0,"Crime,Drama",11535.0,L'Enfant de Paris,7.2,446.0,"Léonce Perret,Louis Leubas,Maurice Lagrenée,Ém..."
1,tt0006206,movie,Les vampires,Les vampires,1915,421.0,"Action,Adventure,Crime",18854.0,Les vampires,7.3,5398.0,"Stacia Napierkowska,Musidora,Édouard Mathé,Mar..."
2,tt0006864,movie,Intolerance,Intolerance: Love's Struggle Throughout the Ages,1916,163.0,"Drama,History",21087.0,Intolérance,7.7,16642.0,"Lillian Gish,Robert Harron,Mae Marsh,F.A. Turner"
3,tt0006886,movie,Judex,Judex,1916,300.0,"Adventure,Crime",21159.0,Judex,7.2,1117.0,"René Cresté,Musidora,René Poyen,Édouard Mathé"
4,tt0009968,movie,Broken Blossoms,Broken Blossoms or The Yellow Man and the Girl,1919,90.0,"Drama,Romance",32134.0,Le lys brisé,7.2,11014.0,"Norman Selby,Lillian Gish,Richard Barthelmess,..."
...,...,...,...,...,...,...,...,...,...,...,...,...
13089,tt9900782,movie,Kaithi,Kaithi,2019,145.0,"Action,Crime,Drama",38883269.0,Kaithi,8.4,42096.0,"Karthi,Narain,Arjun Das,George Maryan"
13090,tt9904844,movie,Ott Tänak: The Movie,Ott Tänak: The Movie,2019,125.0,"Documentary,Sport",NaN,NaN,8.1,501.0,NaN
13091,tt9905462,movie,Pengalila,Pengalila,2019,111.0,Drama,NaN,NaN,7.6,680.0,NaN
13092,tt9911196,movie,The Marriage Escape,De beentjes van Sint-Hildegard,2020,103.0,"Comedy,Drama",38903533.0,De Beentjes van Sint-Hildegard,7.4,3306.0,"Herman Finkers,Johanna ter Steege,Leonie ter B..."
13093,tt9911774,movie,Padmavyuhathile Abhimanyu,Padmavyuhathile Abhimanyu,2019,130.0,Drama,NaN,NaN,8.5,380.0,NaN

In [88]:
fusion_final.drop('Unnamed: 0',axis=1)

,tconst,titleType,primaryTitle,originalTitle,startYear,runtimeMinutes,genres,French_Title,averageRating,numVotes,primaryName
0,tt0003883,movie,L'enfant de Paris,L'enfant de Paris,1913,124.0,"Crime,Drama",L'Enfant de Paris,7.2,446.0,"Léonce Perret,Louis Leubas,Maurice Lagrenée,Ém..."
1,tt0006206,movie,Les vampires,Les vampires,1915,421.0,"Action,Adventure,Crime",Les vampires,7.3,5398.0,"Stacia Napierkowska,Musidora,Édouard Mathé,Mar..."
2,tt0006864,movie,Intolerance,Intolerance: Love's Struggle Throughout the Ages,1916,163.0,"Drama,History",Intolérance,7.7,16642.0,"Lillian Gish,Robert Harron,Mae Marsh,F.A. Turner"
3,tt0006886,movie,Judex,Judex,1916,300.0,"Adventure,Crime",Judex,7.2,1117.0,"René Cresté,Musidora,René Poyen,Édouard Mathé"
4,tt0009968,movie,Broken Blossoms,Broken Blossoms or The Yellow Man and the Girl,1919,90.0,"Drama,Romance",Le lys brisé,7.2,11014.0,"Norman Selby,Lillian Gish,Richard Barthelmess,..."
...,...,...,...,...,...,...,...,...,...,...,...
13089,tt9900782,movie,Kaithi,Kaithi,2019,145.0,"Action,Crime,Drama",Kaithi,8.4,42096.0,"Karthi,Narain,Arjun Das,George Maryan"
13090,tt9904844,movie,Ott Tänak: The Movie,Ott Tänak: The Movie,2019,125.0,"Documentary,Sport",NaN,8.1,501.0,NaN
13091,tt9905462,movie,Pengalila,Pengalila,2019,111.0,Drama,NaN,7.6,680.0,NaN
13092,tt9911196,movie,The Marriage Escape,De beentjes van Sint-Hildegard,2020,103.0,"Comedy,Drama",De Beentjes van Sint-Hildegard,7.4,3306.0,"Herman Finkers,Johanna ter Steege,Leonie ter B..."
13093,tt9911774,movie,Padmavyuhathile Abhimanyu,Padmavyuhathile Abhimanyu,2019,130.0,Drama,NaN,8.5,380.0,NaN

In [89]:
fusion_final.to_csv(r"C:\Users\user\Downloads\Projet ML\Model1(KNN)\Données nettoyées\fusion_final.csv")

# FUSION name basic et title principal

In [80]:
# Fusion name_basics et title_principal dans fusion_namebasic_titleprincipal
fusion_namebasic_titleprincipal = pd.merge(data_title_principal_nettoye, data_name_basics_purify, 
         how="left",     
         left_on='nconst',
         right_on='nconst')

In [81]:
fusion_namebasic_titleprincipal

,tconst,nconst,category,characters,primaryName,primaryProfession,knownForTitles
0,tt0000001,nm0005690,director,NaN,William K.L. Dickson,"cinematographer,director,producer","tt0308254,tt0219560,tt1496763,tt1428455"
1,tt0000002,nm0721526,director,NaN,Émile Reynaud,"director,animation_department,producer","tt16763674,tt16763740,tt13125956,tt0000003"
2,tt0000003,nm0721526,director,NaN,Émile Reynaud,"director,animation_department,producer","tt16763674,tt16763740,tt13125956,tt0000003"
3,tt0000004,nm0721526,director,NaN,Émile Reynaud,"director,animation_department,producer","tt16763674,tt16763740,tt13125956,tt0000003"
4,tt0000005,nm0443482,actor,"[""Blacksmith""]",NaN,NaN,NaN
...,...,...,...,...,...,...,...
30980320,tt9916880,nm1483166,actor,"[""Rude Ralph"",""Mischievous Mike"",""Jolly Josh""]",Aidan Cook,"actor,miscellaneous,special_effects","tt2527338,tt2488496,tt3748528,tt3778644"
30980321,tt9916880,nm0254176,actress,"[""Moody Margaret""]",Sue Elliott-Nichols,actress,"tt0985991,tt6941630,tt6217830,tt1983079"
30980322,tt9916880,nm0286175,actor,"[""Dad"",""Aerobic Al"",""Nasty Nicola""]",Wayne Forester,"actor,sound_department,special_effects","tt1710626,tt0453557,tt1699440,tt1135081"
30980323,tt9916880,nm0584014,director,NaN,Kevin Micallef,"animation_department,director,art_department","tt0181739,tt0275847,tt2130507,tt0901176"
30980324,tt9916880,nm0996406,director,NaN,Hilary Audus,"director,animation_department,art_department","tt0286490,tt2560206,tt0090315,tt0082509"

In [82]:
fusion_namebasic_titleprincipal1 = fusion_namebasic_titleprincipal.dropna()

In [83]:
fusion_namebasic_titleprincipal1 = fusion_namebasic_titleprincipal1.groupby(['tconst']).agg({'primaryName': ','.join})

In [84]:
fusion_namebasic_titleprincipal1 = fusion_namebasic_titleprincipal1.reset_index()
fusion_namebasic_titleprincipal1

            tconst                                        primaryName
0        tt0000008                                           Fred Ott
1        tt0000009   Blanche Bayliss,William Courtenay,Chauncey Depew
2        tt0000014                        François Clerc,Benoît Duval
3        tt0000018                                           Delaware
4        tt0000026                     Antoine Féraud,Félicien Trewey
...            ...                                                ...
4620986  tt9916848   Pelin Akil,Sarp Akkaya,Ilter Akçebe,Zeynep Alkan
4620987  tt9916850   Pelin Akil,Sarp Akkaya,Ilter Akçebe,Zeynep Alkan
4620988  tt9916852   Pelin Akil,Sarp Akkaya,Ilter Akçebe,Zeynep Alkan
4620989  tt9916856  Leni Wesselman,Anna Fitoussi,Andreas Demmel,Ka...
4620990  tt9916880  Lizzie Waterworth,Aidan Cook,Sue Elliott-Nicho...

[4620991 rows x 2 columns]

In [85]:
# Enregistrer le fichier corrigé 
fusion_namebasic_titleprincipal1.to_csv(r"C:\Users\user\Downloads\Projet ML\Model1(KNN)\Données nettoyées\fusion_namebasic_titleprincipal1.csv", index= False)
fusion_namebasic_titleprincipal1 = pd.read_csv(r"C:\Users\user\Downloads\Projet ML\Model1(KNN)\Données nettoyées\fusion_namebasic_titleprincipal1.csv", sep = ",")
fusion_namebasic_titleprincipal1

            tconst                                        primaryName
0        tt0000008                                           Fred Ott
1        tt0000009   Blanche Bayliss,William Courtenay,Chauncey Depew
2        tt0000014                        François Clerc,Benoît Duval
3        tt0000018                                           Delaware
4        tt0000026                     Antoine Féraud,Félicien Trewey
...            ...                                                ...
4620986  tt9916848   Pelin Akil,Sarp Akkaya,Ilter Akçebe,Zeynep Alkan
4620987  tt9916850   Pelin Akil,Sarp Akkaya,Ilter Akçebe,Zeynep Alkan
4620988  tt9916852   Pelin Akil,Sarp Akkaya,Ilter Akçebe,Zeynep Alkan
4620989  tt9916856  Leni Wesselman,Anna Fitoussi,Andreas Demmel,Ka...
4620990  tt9916880  Lizzie Waterworth,Aidan Cook,Sue Elliott-Nicho...

[4620991 rows x 2 columns]

In [90]:
# Fusion fusion_titlebasic_titlerating and fusion_namebasic_titleprincipal into fusion_final1
fusion_final1 = pd.merge(fusion_titlebasic_titlerating, fusion_namebasic_titleprincipal1, 
         how="left",     
         left_on='tconst',
         right_on='tconst')
fusion_final1

,tconst,titleType,primaryTitle,originalTitle,startYear,runtimeMinutes,genres,Unnamed: 0,French_Title,averageRating,numVotes,primaryName
0,tt0003883,movie,L'enfant de Paris,L'enfant de Paris,1913,124.0,"Crime,Drama",11535.0,L'Enfant de Paris,7.2,446.0,"Léonce Perret,Louis Leubas,Maurice Lagrenée,Ém..."
1,tt0006206,movie,Les vampires,Les vampires,1915,421.0,"Action,Adventure,Crime",18854.0,Les vampires,7.3,5398.0,"Stacia Napierkowska,Musidora,Édouard Mathé,Mar..."
2,tt0006864,movie,Intolerance,Intolerance: Love's Struggle Throughout the Ages,1916,163.0,"Drama,History",21087.0,Intolérance,7.7,16642.0,"Lillian Gish,Robert Harron,Mae Marsh,F.A. Turner"
3,tt0006886,movie,Judex,Judex,1916,300.0,"Adventure,Crime",21159.0,Judex,7.2,1117.0,"René Cresté,Musidora,René Poyen,Édouard Mathé"
4,tt0009968,movie,Broken Blossoms,Broken Blossoms or The Yellow Man and the Girl,1919,90.0,"Drama,Romance",32134.0,Le lys brisé,7.2,11014.0,"Norman Selby,Lillian Gish,Richard Barthelmess,..."
...,...,...,...,...,...,...,...,...,...,...,...,...
13089,tt9900782,movie,Kaithi,Kaithi,2019,145.0,"Action,Crime,Drama",38883269.0,Kaithi,8.4,42096.0,"Karthi,Narain,Arjun Das,George Maryan"
13090,tt9904844,movie,Ott Tänak: The Movie,Ott Tänak: The Movie,2019,125.0,"Documentary,Sport",NaN,NaN,8.1,501.0,NaN
13091,tt9905462,movie,Pengalila,Pengalila,2019,111.0,Drama,NaN,NaN,7.6,680.0,NaN
13092,tt9911196,movie,The Marriage Escape,De beentjes van Sint-Hildegard,2020,103.0,"Comedy,Drama",38903533.0,De Beentjes van Sint-Hildegard,7.4,3306.0,"Herman Finkers,Johanna ter Steege,Leonie ter B..."
13093,tt9911774,movie,Padmavyuhathile Abhimanyu,Padmavyuhathile Abhimanyu,2019,130.0,Drama,NaN,NaN,8.5,380.0,NaN

In [91]:
# Supprimer les colonnes titleType et characters
fusion_final1 = fusion_final1.drop(['titleType','Unnamed: 0'], axis=1) 
fusion_final1

,tconst,primaryTitle,originalTitle,startYear,runtimeMinutes,genres,French_Title,averageRating,numVotes,primaryName
0,tt0003883,L'enfant de Paris,L'enfant de Paris,1913,124.0,"Crime,Drama",L'Enfant de Paris,7.2,446.0,"Léonce Perret,Louis Leubas,Maurice Lagrenée,Ém..."
1,tt0006206,Les vampires,Les vampires,1915,421.0,"Action,Adventure,Crime",Les vampires,7.3,5398.0,"Stacia Napierkowska,Musidora,Édouard Mathé,Mar..."
2,tt0006864,Intolerance,Intolerance: Love's Struggle Throughout the Ages,1916,163.0,"Drama,History",Intolérance,7.7,16642.0,"Lillian Gish,Robert Harron,Mae Marsh,F.A. Turner"
3,tt0006886,Judex,Judex,1916,300.0,"Adventure,Crime",Judex,7.2,1117.0,"René Cresté,Musidora,René Poyen,Édouard Mathé"
4,tt0009968,Broken Blossoms,Broken Blossoms or The Yellow Man and the Girl,1919,90.0,"Drama,Romance",Le lys brisé,7.2,11014.0,"Norman Selby,Lillian Gish,Richard Barthelmess,..."
...,...,...,...,...,...,...,...,...,...,...
13089,tt9900782,Kaithi,Kaithi,2019,145.0,"Action,Crime,Drama",Kaithi,8.4,42096.0,"Karthi,Narain,Arjun Das,George Maryan"
13090,tt9904844,Ott Tänak: The Movie,Ott Tänak: The Movie,2019,125.0,"Documentary,Sport",NaN,8.1,501.0,NaN
13091,tt9905462,Pengalila,Pengalila,2019,111.0,Drama,NaN,7.6,680.0,NaN
13092,tt9911196,The Marriage Escape,De beentjes van Sint-Hildegard,2020,103.0,"Comedy,Drama",De Beentjes van Sint-Hildegard,7.4,3306.0,"Herman Finkers,Johanna ter Steege,Leonie ter B..."
13093,tt9911774,Padmavyuhathile Abhimanyu,Padmavyuhathile Abhimanyu,2019,130.0,Drama,NaN,8.5,380.0,NaN

In [93]:
# Enregistrer le fichier corrigé
fusion_final1.to_csv(r"C:\Users\user\Downloads\Projet ML\Model1(KNN)\Données nettoyées\fusion_final1.csv", index= False)

In [98]:
#Charger le fichier
fusion_final1=pd.read_csv(r"C:\Users\user\Downloads\Projet ML\Model1(KNN)\Données nettoyées\fusion_final1.csv",sep=",")
fusion_final1

,tconst,primaryTitle,originalTitle,startYear,runtimeMinutes,genres,French_Title,averageRating,numVotes,primaryName
0,tt0003883,L'enfant de Paris,L'enfant de Paris,1913,124.0,"Crime,Drama",L'Enfant de Paris,7.2,446.0,"Léonce Perret,Louis Leubas,Maurice Lagrenée,Ém..."
1,tt0006206,Les vampires,Les vampires,1915,421.0,"Action,Adventure,Crime",Les vampires,7.3,5398.0,"Stacia Napierkowska,Musidora,Édouard Mathé,Mar..."
2,tt0006864,Intolerance,Intolerance: Love's Struggle Throughout the Ages,1916,163.0,"Drama,History",Intolérance,7.7,16642.0,"Lillian Gish,Robert Harron,Mae Marsh,F.A. Turner"
3,tt0006886,Judex,Judex,1916,300.0,"Adventure,Crime",Judex,7.2,1117.0,"René Cresté,Musidora,René Poyen,Édouard Mathé"
4,tt0009968,Broken Blossoms,Broken Blossoms or The Yellow Man and the Girl,1919,90.0,"Drama,Romance",Le lys brisé,7.2,11014.0,"Norman Selby,Lillian Gish,Richard Barthelmess,..."
...,...,...,...,...,...,...,...,...,...,...
13089,tt9900782,Kaithi,Kaithi,2019,145.0,"Action,Crime,Drama",Kaithi,8.4,42096.0,"Karthi,Narain,Arjun Das,George Maryan"
13090,tt9904844,Ott Tänak: The Movie,Ott Tänak: The Movie,2019,125.0,"Documentary,Sport",NaN,8.1,501.0,NaN
13091,tt9905462,Pengalila,Pengalila,2019,111.0,Drama,NaN,7.6,680.0,NaN
13092,tt9911196,The Marriage Escape,De beentjes van Sint-Hildegard,2020,103.0,"Comedy,Drama",De Beentjes van Sint-Hildegard,7.4,3306.0,"Herman Finkers,Johanna ter Steege,Leonie ter B..."
13093,tt9911774,Padmavyuhathile Abhimanyu,Padmavyuhathile Abhimanyu,2019,130.0,Drama,NaN,8.5,380.0,NaN

In [105]:
# Fonction pour traiter chaque ligne du dataframe fusion_final1 et créer de nouvelles lignes
def expand_primary_name(row):
    if isinstance(row['primaryName'], str):
        primary_names = row['primaryName'].split(',')
        rows = []
        for name in primary_names:
            new_row = row.copy()
            new_row['primaryName'] = name
            rows.append(new_row)
        return pd.DataFrame(rows)
    else:
        return row

# Appliquer la fonction sur chaque ligne du dataframe  et concaténer les résultats
fusion_final1nettoye = pd.concat([expand_primary_name(row) for _, row in fusion_final1.iterrows()], ignore_index=True)

In [106]:
fusion_final1nettoye

,tconst,primaryTitle,originalTitle,startYear,runtimeMinutes,genres,French_Title,averageRating,numVotes,primaryName,0
0,tt0003883,L'enfant de Paris,L'enfant de Paris,1913.0,124.0,"Crime,Drama",L'Enfant de Paris,7.2,446.0,Léonce Perret,NaN
1,tt0003883,L'enfant de Paris,L'enfant de Paris,1913.0,124.0,"Crime,Drama",L'Enfant de Paris,7.2,446.0,Louis Leubas,NaN
2,tt0003883,L'enfant de Paris,L'enfant de Paris,1913.0,124.0,"Crime,Drama",L'Enfant de Paris,7.2,446.0,Maurice Lagrenée,NaN
3,tt0003883,L'enfant de Paris,L'enfant de Paris,1913.0,124.0,"Crime,Drama",L'Enfant de Paris,7.2,446.0,Émile Keppens,NaN
4,tt0003883,L'enfant de Paris,L'enfant de Paris,1913.0,124.0,"Crime,Drama",L'Enfant de Paris,7.2,446.0,Marc Gérard,NaN
...,...,...,...,...,...,...,...,...,...,...,...
281633,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
281634,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
281635,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
281636,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
281637,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [111]:
fusion_final1nettoye=fusion_final1nettoye.dropna(subset=['tconst'])

In [112]:
fusion_final1nettoye

,tconst,primaryTitle,originalTitle,startYear,runtimeMinutes,genres,French_Title,averageRating,numVotes,primaryName,0
0,tt0003883,L'enfant de Paris,L'enfant de Paris,1913.0,124.0,"Crime,Drama",L'Enfant de Paris,7.2,446.0,Léonce Perret,NaN
1,tt0003883,L'enfant de Paris,L'enfant de Paris,1913.0,124.0,"Crime,Drama",L'Enfant de Paris,7.2,446.0,Louis Leubas,NaN
2,tt0003883,L'enfant de Paris,L'enfant de Paris,1913.0,124.0,"Crime,Drama",L'Enfant de Paris,7.2,446.0,Maurice Lagrenée,NaN
3,tt0003883,L'enfant de Paris,L'enfant de Paris,1913.0,124.0,"Crime,Drama",L'Enfant de Paris,7.2,446.0,Émile Keppens,NaN
4,tt0003883,L'enfant de Paris,L'enfant de Paris,1913.0,124.0,"Crime,Drama",L'Enfant de Paris,7.2,446.0,Marc Gérard,NaN
...,...,...,...,...,...,...,...,...,...,...,...
281303,tt9900782,Kaithi,Kaithi,2019.0,145.0,"Action,Crime,Drama",Kaithi,8.4,42096.0,George Maryan,NaN
281524,tt9911196,The Marriage Escape,De beentjes van Sint-Hildegard,2020.0,103.0,"Comedy,Drama",De Beentjes van Sint-Hildegard,7.4,3306.0,Herman Finkers,NaN
281525,tt9911196,The Marriage Escape,De beentjes van Sint-Hildegard,2020.0,103.0,"Comedy,Drama",De Beentjes van Sint-Hildegard,7.4,3306.0,Johanna ter Steege,NaN
281526,tt9911196,The Marriage Escape,De beentjes van Sint-Hildegard,2020.0,103.0,"Comedy,Drama",De Beentjes van Sint-Hildegard,7.4,3306.0,Leonie ter Braak,NaN
281527,tt9911196,The Marriage Escape,De beentjes van Sint-Hildegard,2020.0,103.0,"Comedy,Drama",De Beentjes van Sint-Hildegard,7.4,3306.0,Ferdi Stofmeel,NaN

In [113]:
# Enregistrer le fichier corrigé
fusion_final1nettoye.to_csv(r"C:\Users\user\Downloads\Projet ML\Model1(KNN)\Données nettoyées\fusion_final1nettoye.csv", index= False)