In [1]:
import pandas as pd
import numpy as np

In [2]:
data_machine_learning = pd.read_pickle(r"C:\Users\user\Downloads\Projet ML\Model1(KNN)\Données nettoyées\data_machine_learning.pkl.gz")
data_machine_learning

,tconst,titleType,primaryTitle,originalTitle,startYear,French_Title,averageRating,numVotes,Action,Adult,...,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
0,tt0003883,movie,L'enfant de Paris (1913),L'enfant de Paris (1913),1913,L'Enfant de Paris (1913),7.2,446.0,False,False,...,False,False,False,False,False,False,False,False,False,False
1,tt0006206,movie,Les vampires (1915),Les vampires (1915),1915,Les vampires (1915),7.3,5398.0,True,False,...,False,False,False,False,False,False,False,False,False,False
2,tt0006864,movie,Intolerance (1916),Intolerance: Love's Struggle Throughout the Ag...,1916,Intolérance (1916),7.7,16642.0,False,False,...,False,False,False,False,False,False,False,False,False,False
3,tt0006886,movie,Judex (1916),Judex (1916),1916,Judex (1916),7.2,1117.0,False,False,...,False,False,False,False,False,False,False,False,False,False
4,tt0009968,movie,Broken Blossoms (1919),Broken Blossoms or The Yellow Man and the Girl...,1919,Le lys brisé (1919),7.2,11014.0,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13089,tt9900782,movie,Kaithi (2019),Kaithi (2019),2019,Kaithi (2019),8.4,42096.0,True,False,...,False,False,False,False,True,False,False,False,False,False
13090,tt9904844,movie,Ott Tänak: The Movie (2019),Ott Tänak: The Movie (2019),2019,NaN,8.1,501.0,False,False,...,False,False,False,False,True,False,False,False,False,False
13091,tt9905462,movie,Pengalila (2019),Pengalila (2019),2019,NaN,7.6,680.0,False,False,...,False,False,False,False,True,False,False,False,False,False
13092,tt9911196,movie,The Marriage Escape (2020),De beentjes van Sint-Hildegard (2020),2020,De Beentjes van Sint-Hildegard (2020),7.4,3306.0,False,False,...,False,False,False,False,False,True,False,False,False,False
13093,tt9911774,movie,Padmavyuhathile Abhimanyu (2019),Padmavyuhathile Abhimanyu (2019),2019,NaN,8.5,380.0,False,False,...,False,False,False,False,True,False,False,False,False,False

In [3]:
data_machine_learning.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13094 entries, 0 to 13093
Columns: 22871 entries, tconst to 2024
dtypes: bool(22863), float64(2), int64(1), object(5)
memory usage: 286.3+ MB

# Liste des films

In [4]:
# colonne "primarytitle" en  DF
primarytitle = data_machine_learning[['tconst', 'primaryTitle']]
primarytitle.head()

      tconst              primaryTitle
0  tt0003883  L'enfant de Paris (1913)
1  tt0006206       Les vampires (1915)
2  tt0006864        Intolerance (1916)
3  tt0006886              Judex (1916)
4  tt0009968    Broken Blossoms (1919)

In [5]:
# la colonne "originaltitle" en  df
originaltitle = data_machine_learning[["tconst", "originalTitle"]]

In [6]:
#Changement du nom de la colonne "originalTitle" en "primaryTitle"
originaltitle = originaltitle.rename(columns = {"originalTitle" : "primaryTitle"})
originaltitle.head()

      tconst                                       primaryTitle
0  tt0003883                           L'enfant de Paris (1913)
1  tt0006206                                Les vampires (1915)
2  tt0006864  Intolerance: Love's Struggle Throughout the Ag...
3  tt0006886                                       Judex (1916)
4  tt0009968  Broken Blossoms or The Yellow Man and the Girl...

In [7]:
French_Title = data_machine_learning[["tconst", "French_Title"]]
French_Title = French_Title.rename(columns = {"French_Title" : "primaryTitle"})
French_Title.head()

      tconst               primaryTitle
0  tt0003883  L'Enfant de Paris (1913)
1  tt0006206       Les vampires (1915)
2  tt0006864        Intolérance (1916)
3  tt0006886              Judex (1916)
4  tt0009968       Le lys brisé (1919)

In [8]:
#Création d'un dataframe avec les dataframes créés ci-dessus
liste_films = pd.concat([primarytitle, originaltitle, French_Title])

In [9]:
liste_films.sort_values(['tconst'])

          tconst                           primaryTitle
0      tt0003883               L'enfant de Paris (1913)
0      tt0003883               L'enfant de Paris (1913)
0      tt0003883              L'Enfant de Paris (1913)
1      tt0006206                    Les vampires (1915)
1      tt0006206                    Les vampires (1915)
...          ...                                    ...
13092  tt9911196             The Marriage Escape (2020)
13092  tt9911196  De beentjes van Sint-Hildegard (2020)
13093  tt9911774       Padmavyuhathile Abhimanyu (2019)
13093  tt9911774       Padmavyuhathile Abhimanyu (2019)
13093  tt9911774                                    NaN

[39282 rows x 2 columns]

In [10]:
liste_films[liste_films['tconst'] == 'tt9900782']

          tconst    primaryTitle
13089  tt9900782   Kaithi (2019)
13089  tt9900782   Kaithi (2019)
13089  tt9900782  Kaithi (2019)

In [11]:
#Suppression des données en double
liste_films = liste_films.drop_duplicates()
liste_films = liste_films.dropna()
len(liste_films["tconst"].unique())

12322

In [12]:
liste_films

          tconst                            primaryTitle
0      tt0003883                L'enfant de Paris (1913)
1      tt0006206                     Les vampires (1915)
2      tt0006864                      Intolerance (1916)
3      tt0006886                            Judex (1916)
4      tt0009968                  Broken Blossoms (1919)
...          ...                                     ...
13083  tt9860350                La famille Asada (2020)
13084  tt9882084          Le bonheur à tout prix (2019)
13085  tt9883832                Moonage Daydream (2022)
13089  tt9900782                          Kaithi (2019)
13092  tt9911196  De Beentjes van Sint-Hildegard (2020)

[24217 rows x 2 columns]

In [13]:
liste_films[liste_films['tconst'] == 'tt9900782']

          tconst    primaryTitle
13089  tt9900782   Kaithi (2019)
13089  tt9900782  Kaithi (2019)

In [14]:
data=liste_films['primaryTitle'].unique()

In [15]:
len(data)

24210

In [16]:
liste_films[liste_films.nunique(axis = 1) > 2 ]

Empty DataFrame
Columns: [tconst, primaryTitle]
Index: []

In [17]:
# Enregistrer le fichier corrigé sur le pc en pickle
liste_films.to_pickle(r"C:\Users\user\Downloads\Projet ML\Model1(KNN)\Données nettoyées\liste_films.pkl.gz", compression = "gzip")

# Listes des genres

In [18]:
fusion_final1 = pd.read_csv(r"C:\Users\user\Downloads\Projet ML\Model1(KNN)\Données nettoyées\fusion_final1.csv")
fusion_final1

,tconst,primaryTitle,originalTitle,startYear,runtimeMinutes,genres,French_Title,averageRating,numVotes,primaryName
0,tt0003883,L'enfant de Paris,L'enfant de Paris,1913,124.0,"Crime,Drama",L'Enfant de Paris,7.2,446.0,"Léonce Perret,Louis Leubas,Maurice Lagrenée,Ém..."
1,tt0006206,Les vampires,Les vampires,1915,421.0,"Action,Adventure,Crime",Les vampires,7.3,5398.0,"Stacia Napierkowska,Musidora,Édouard Mathé,Mar..."
2,tt0006864,Intolerance,Intolerance: Love's Struggle Throughout the Ages,1916,163.0,"Drama,History",Intolérance,7.7,16642.0,"Lillian Gish,Robert Harron,Mae Marsh,F.A. Turner"
3,tt0006886,Judex,Judex,1916,300.0,"Adventure,Crime",Judex,7.2,1117.0,"René Cresté,Musidora,René Poyen,Édouard Mathé"
4,tt0009968,Broken Blossoms,Broken Blossoms or The Yellow Man and the Girl,1919,90.0,"Drama,Romance",Le lys brisé,7.2,11014.0,"Norman Selby,Lillian Gish,Richard Barthelmess,..."
...,...,...,...,...,...,...,...,...,...,...
13089,tt9900782,Kaithi,Kaithi,2019,145.0,"Action,Crime,Drama",Kaithi,8.4,42096.0,"Karthi,Narain,Arjun Das,George Maryan"
13090,tt9904844,Ott Tänak: The Movie,Ott Tänak: The Movie,2019,125.0,"Documentary,Sport",NaN,8.1,501.0,NaN
13091,tt9905462,Pengalila,Pengalila,2019,111.0,Drama,NaN,7.6,680.0,NaN
13092,tt9911196,The Marriage Escape,De beentjes van Sint-Hildegard,2020,103.0,"Comedy,Drama",De Beentjes van Sint-Hildegard,7.4,3306.0,"Herman Finkers,Johanna ter Steege,Leonie ter B..."
13093,tt9911774,Padmavyuhathile Abhimanyu,Padmavyuhathile Abhimanyu,2019,130.0,Drama,NaN,8.5,380.0,NaN

In [22]:
#récupération des données de la colonne "genres" en un Dataframe
liste_genres = fusion_final1.groupby(["genres"]).count().reset_index().sort_values(by = "tconst", ascending = False).iloc[:,:2]
liste_genres

                            genres  tconst
392                          Drama    1938
350                    Documentary     887
452                  Drama,Romance     696
252                   Comedy,Drama     678
229                         Comedy     392
..                             ...     ...
85                    Adult,Comedy       1
401               Drama,Family,War       1
402           Drama,Family,Western       1
251         Comedy,Documentary,War       1
121  Adventure,Documentary,Western       1

[525 rows x 2 columns]

In [23]:
# get dummies pour séparer les genres
liste_genres = liste_genres["genres"].str.get_dummies(sep=',').astype(bool)
liste_genres

,Action,Adult,Adventure,Animation,Biography,Comedy,Crime,Divers,Documentary,Drama,...,Mystery,News,Reality-TV,Romance,Sci-Fi,Sport,Talk-Show,Thriller,War,Western
392,False,False,False,False,False,False,False,False,False,True,...,False,False,False,False,False,False,False,False,False,False
350,False,False,False,False,False,False,False,False,True,False,...,False,False,False,False,False,False,False,False,False,False
452,False,False,False,False,False,False,False,False,False,True,...,False,False,False,True,False,False,False,False,False,False
252,False,False,False,False,False,True,False,False,False,True,...,False,False,False,False,False,False,False,False,False,False
229,False,False,False,False,False,True,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
85,False,True,False,False,False,True,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
401,False,False,False,False,False,False,False,False,False,True,...,False,False,False,False,False,False,False,False,True,False
402,False,False,False,False,False,False,False,False,False,True,...,False,False,False,False,False,False,False,False,False,True
251,False,False,False,False,False,True,False,False,True,False,...,False,False,False,False,False,False,False,False,True,False
121,False,False,True,False,False,False,False,False,True,False,...,False,False,False,False,False,False,False,False,False,True

In [24]:
# récupérer le titre de chaque colonne 
columns = liste_genres.columns
columns

Index(['Action', 'Adult', 'Adventure', 'Animation', 'Biography', 'Comedy',
       'Crime', 'Divers', 'Documentary', 'Drama', 'Family', 'Fantasy',
       'Film-Noir', 'History', 'Horror', 'Music', 'Musical', 'Mystery', 'News',
       'Reality-TV', 'Romance', 'Sci-Fi', 'Sport', 'Talk-Show', 'Thriller',
       'War', 'Western'],
      dtype='object')

In [25]:
# On stocke les genres dans un nouveau dataframe
liste_genres = pd.DataFrame({"genres" : columns})
liste_genres

         genres
0        Action
1         Adult
2     Adventure
3     Animation
4     Biography
5        Comedy
6         Crime
7        Divers
8   Documentary
9         Drama
10       Family
11      Fantasy
12    Film-Noir
13      History
14       Horror
15        Music
16      Musical
17      Mystery
18         News
19   Reality-TV
20      Romance
21       Sci-Fi
22        Sport
23    Talk-Show
24     Thriller
25          War
26      Western

In [26]:
#Enregistrer les genres
liste_genres.to_pickle(r"C:\Users\user\Downloads\Projet ML\Model1(KNN)\Données nettoyées\liste_genres.pkl.gz", compression = "gzip")

# Liste des acteurs

In [27]:
fusion_final1nettoye = pd.read_csv(r"C:\Users\user\Downloads\Projet ML\Model1(KNN)\Données nettoyées\fusion_final1nettoye.csv")
fusion_final1nettoye

,tconst,primaryTitle,originalTitle,startYear,runtimeMinutes,genres,French_Title,averageRating,numVotes,primaryName,0
0,tt0003883,L'enfant de Paris,L'enfant de Paris,1913.0,124.0,"Crime,Drama",L'Enfant de Paris,7.2,446.0,Léonce Perret,NaN
1,tt0003883,L'enfant de Paris,L'enfant de Paris,1913.0,124.0,"Crime,Drama",L'Enfant de Paris,7.2,446.0,Louis Leubas,NaN
2,tt0003883,L'enfant de Paris,L'enfant de Paris,1913.0,124.0,"Crime,Drama",L'Enfant de Paris,7.2,446.0,Maurice Lagrenée,NaN
3,tt0003883,L'enfant de Paris,L'enfant de Paris,1913.0,124.0,"Crime,Drama",L'Enfant de Paris,7.2,446.0,Émile Keppens,NaN
4,tt0003883,L'enfant de Paris,L'enfant de Paris,1913.0,124.0,"Crime,Drama",L'Enfant de Paris,7.2,446.0,Marc Gérard,NaN
...,...,...,...,...,...,...,...,...,...,...,...
42493,tt9900782,Kaithi,Kaithi,2019.0,145.0,"Action,Crime,Drama",Kaithi,8.4,42096.0,George Maryan,NaN
42494,tt9911196,The Marriage Escape,De beentjes van Sint-Hildegard,2020.0,103.0,"Comedy,Drama",De Beentjes van Sint-Hildegard,7.4,3306.0,Herman Finkers,NaN
42495,tt9911196,The Marriage Escape,De beentjes van Sint-Hildegard,2020.0,103.0,"Comedy,Drama",De Beentjes van Sint-Hildegard,7.4,3306.0,Johanna ter Steege,NaN
42496,tt9911196,The Marriage Escape,De beentjes van Sint-Hildegard,2020.0,103.0,"Comedy,Drama",De Beentjes van Sint-Hildegard,7.4,3306.0,Leonie ter Braak,NaN
42497,tt9911196,The Marriage Escape,De beentjes van Sint-Hildegard,2020.0,103.0,"Comedy,Drama",De Beentjes van Sint-Hildegard,7.4,3306.0,Ferdi Stofmeel,NaN

In [28]:
#récupération des données de la colonne "ACTEURS" en un DF
liste_acteurs = fusion_final1nettoye.groupby(["primaryName"]).count().reset_index().sort_values(by = "tconst", ascending = False).iloc[:,:2]
liste_acteurs

                primaryName  tconst
14267              Mohanlal      79
12517             Mammootty      54
10318          Kamal Haasan      45
16370           Prakash Raj      40
20676        Toshirô Mifune      36
...                     ...     ...
8833          Janette Scott       1
8834              Janez Cuk       1
8835              Janez Rus       1
8836          Janez Vrhovec       1
22510  Þórhallur Sigurðsson       1

[22511 rows x 2 columns]

In [29]:
#Enregistrer fichier corrigé sur le pc en pickle
liste_acteurs.to_pickle(r"C:\Users\user\Downloads\Projet ML\Model1(KNN)\Données nettoyées\liste_acteurs.pkl.gz", compression = "gzip")

# Liste des années

In [30]:
data_annee = fusion_final1nettoye[["startYear", "tconst"]]
data_annee['startYear'] = data_annee['startYear'].astype(int)
data_annee = data_annee.sort_values(by ='startYear', ascending = True).drop_duplicates()

C:\Users\user\AppData\Local\Temp\ipykernel_21796\3982747896.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_annee['startYear'] = data_annee['startYear'].astype(int)

In [31]:
data_annee

       startYear      tconst
0           1913   tt0003883
7           1915   tt0006206
20          1916   tt0006886
15          1916   tt0006864
26          1919   tt0009968
...          ...         ...
28196       2024  tt11216522
31289       2024  tt15554466
31202       2024  tt15433956
35727       2024  tt28266209
31168       2024  tt15392282

[10195 rows x 2 columns]

In [32]:
#Enregistrer le fichier de la liste des années
data_annee.to_pickle(r"C:\Users\user\Downloads\Projet ML\Model1(KNN)\Données nettoyées\liste_annees.pkl.gz", compression = "gzip")