In [1]:
import pandas as pd
from sklearn.neighbors import KNeighborsClassifier
from sklearn.neighbors import NearestNeighbors

In [2]:
data1=pd.read_pickle(r"C:\Users\user\Downloads\Projet ML\Model1(KNN)\Données nettoyées\data_machine_learning_clean.pkl.gz")

In [3]:
data1

,tconst,titleType,primaryTitle,originalTitle,startYear,French_Title,averageRating,numVotes,Action,Adventure,...,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
0,tt0003883,movie,L'enfant de Paris (1913),L'enfant de Paris (1913),1913,L'Enfant de Paris (1913),7.2,446.0,False,False,...,False,False,False,False,False,False,False,False,False,False
1,tt0006206,movie,Les vampires (1915),Les vampires (1915),1915,Les vampires (1915),7.3,5398.0,True,True,...,False,False,False,False,False,False,False,False,False,False
2,tt0006864,movie,Intolerance (1916),Intolerance: Love's Struggle Throughout the Ag...,1916,Intolérance (1916),7.7,16642.0,False,False,...,False,False,False,False,False,False,False,False,False,False
3,tt0006886,movie,Judex (1916),Judex (1916),1916,Judex (1916),7.2,1117.0,False,True,...,False,False,False,False,False,False,False,False,False,False
4,tt0009968,movie,Broken Blossoms (1919),Broken Blossoms or The Yellow Man and the Girl...,1919,Le lys brisé (1919),7.2,11014.0,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13089,tt9900782,movie,Kaithi (2019),Kaithi (2019),2019,Kaithi (2019),8.4,42096.0,True,False,...,False,False,False,False,True,False,False,False,False,False
13090,tt9904844,movie,Ott Tänak: The Movie (2019),Ott Tänak: The Movie (2019),2019,NaN,8.1,501.0,False,False,...,False,False,False,False,True,False,False,False,False,False
13091,tt9905462,movie,Pengalila (2019),Pengalila (2019),2019,NaN,7.6,680.0,False,False,...,False,False,False,False,True,False,False,False,False,False
13092,tt9911196,movie,The Marriage Escape (2020),De beentjes van Sint-Hildegard (2020),2020,De Beentjes van Sint-Hildegard (2020),7.4,3306.0,False,False,...,False,False,False,False,False,True,False,False,False,False
13093,tt9911774,movie,Padmavyuhathile Abhimanyu (2019),Padmavyuhathile Abhimanyu (2019),2019,NaN,8.5,380.0,False,False,...,False,False,False,False,True,False,False,False,False,False

In [4]:
data2=pd.read_csv(r"C:\Users\user\Downloads\Projet ML\Model2 textvectorclassificator(countvectorizer)\Dataset2\fusion.csv")

In [5]:
data2

,Unnamed: 0,tconst,primaryTitle,originalTitle,startYear,runtimeMinutes,genres,French_Title,averageRating,numVotes,description,primaryName
0,0,tt0003883,L'enfant de Paris (1913),L'enfant de Paris (1913),1913,124.0,"Crime,Drama",L'Enfant de Paris (1913),7.2,446.0,The young daughter of an army captain missing ...,"Léonce Perret,Louis Leubas,Maurice Lagrenée,Ém..."
1,1,tt0006206,Les vampires (1915),Les vampires (1915),1915,421.0,"Action,Adventure,Crime",Les vampires (1915),7.3,5398.0,An intrepid reporter and his loyal friend batt...,"Stacia Napierkowska,Musidora,Édouard Mathé,Mar..."
2,2,tt0006864,Intolerance (1916),Intolerance: Love's Struggle Throughout the Ag...,1916,163.0,"Drama,History",Intolérance (1916),7.7,16642.0,"The story of a poor young woman, separated by ...","Lillian Gish,Robert Harron,Mae Marsh,F.A. Turner"
3,3,tt0006886,Judex (1916),Judex (1916),1916,300.0,"Adventure,Crime",Judex (1916),7.2,1117.0,A twelve part serial following the adventures ...,"René Cresté,Musidora,René Poyen,Édouard Mathé"
4,4,tt0009968,Broken Blossoms (1919),Broken Blossoms or The Yellow Man and the Girl...,1919,90.0,"Drama,Romance",Le lys brisé (1919),7.2,11014.0,"A frail waif, abused by her brutal boxer fathe...","Norman Selby,Lillian Gish,Richard Barthelmess,..."
...,...,...,...,...,...,...,...,...,...,...,...,...
9239,13086,tt9892338,Dare to Surf (2019),No Dorai (2019),2019,150.0,Drama,NaN,7.2,705.0,"In a small beach town in Bangladesh, fearless ...","Sunerah Binte Kamal,Sariful Razz,Josefine Lind..."
9240,13087,tt9894394,Upin & Ipin: Keris Siamang Tunggal (2019),Upin & Ipin: Keris siamang tunggal (2019),2019,100.0,"Adventure,Animation,Comedy",NaN,7.3,829.0,"Upin, Ipin and their friends come across a mys...","Asyiela Putri Bt Azhar,Mohd Amir Asyraf Bin Mo..."
9241,13089,tt9900782,Kaithi (2019),Kaithi (2019),2019,145.0,"Action,Crime,Drama",Kaithi (2019),8.4,42096.0,A recently released prisoner becomes involved ...,"Karthi,Narain,Arjun Das,George Maryan"
9242,13091,tt9905462,Pengalila (2019),Pengalila (2019),2019,111.0,Drama,NaN,7.6,680.0,An unusual bond between a sixty year old Dalit...,NaN
9243,13092,tt9911196,The Marriage Escape (2020),De beentjes van Sint-Hildegard (2020),2020,103.0,"Comedy,Drama",De Beentjes van Sint-Hildegard (2020),7.4,3306.0,A middle-aged veterinary surgeon believes his ...,"Herman Finkers,Johanna ter Steege,Leonie ter B..."

In [6]:
data2=data2.drop('Unnamed: 0',axis=1)

In [7]:
data2

,tconst,primaryTitle,originalTitle,startYear,runtimeMinutes,genres,French_Title,averageRating,numVotes,description,primaryName
0,tt0003883,L'enfant de Paris (1913),L'enfant de Paris (1913),1913,124.0,"Crime,Drama",L'Enfant de Paris (1913),7.2,446.0,The young daughter of an army captain missing ...,"Léonce Perret,Louis Leubas,Maurice Lagrenée,Ém..."
1,tt0006206,Les vampires (1915),Les vampires (1915),1915,421.0,"Action,Adventure,Crime",Les vampires (1915),7.3,5398.0,An intrepid reporter and his loyal friend batt...,"Stacia Napierkowska,Musidora,Édouard Mathé,Mar..."
2,tt0006864,Intolerance (1916),Intolerance: Love's Struggle Throughout the Ag...,1916,163.0,"Drama,History",Intolérance (1916),7.7,16642.0,"The story of a poor young woman, separated by ...","Lillian Gish,Robert Harron,Mae Marsh,F.A. Turner"
3,tt0006886,Judex (1916),Judex (1916),1916,300.0,"Adventure,Crime",Judex (1916),7.2,1117.0,A twelve part serial following the adventures ...,"René Cresté,Musidora,René Poyen,Édouard Mathé"
4,tt0009968,Broken Blossoms (1919),Broken Blossoms or The Yellow Man and the Girl...,1919,90.0,"Drama,Romance",Le lys brisé (1919),7.2,11014.0,"A frail waif, abused by her brutal boxer fathe...","Norman Selby,Lillian Gish,Richard Barthelmess,..."
...,...,...,...,...,...,...,...,...,...,...,...
9239,tt9892338,Dare to Surf (2019),No Dorai (2019),2019,150.0,Drama,NaN,7.2,705.0,"In a small beach town in Bangladesh, fearless ...","Sunerah Binte Kamal,Sariful Razz,Josefine Lind..."
9240,tt9894394,Upin & Ipin: Keris Siamang Tunggal (2019),Upin & Ipin: Keris siamang tunggal (2019),2019,100.0,"Adventure,Animation,Comedy",NaN,7.3,829.0,"Upin, Ipin and their friends come across a mys...","Asyiela Putri Bt Azhar,Mohd Amir Asyraf Bin Mo..."
9241,tt9900782,Kaithi (2019),Kaithi (2019),2019,145.0,"Action,Crime,Drama",Kaithi (2019),8.4,42096.0,A recently released prisoner becomes involved ...,"Karthi,Narain,Arjun Das,George Maryan"
9242,tt9905462,Pengalila (2019),Pengalila (2019),2019,111.0,Drama,NaN,7.6,680.0,An unusual bond between a sixty year old Dalit...,NaN
9243,tt9911196,The Marriage Escape (2020),De beentjes van Sint-Hildegard (2020),2020,103.0,"Comedy,Drama",De Beentjes van Sint-Hildegard (2020),7.4,3306.0,A middle-aged veterinary surgeon believes his ...,"Herman Finkers,Johanna ter Steege,Leonie ter B..."

In [8]:
data2=data2.drop(['primaryTitle','originalTitle','startYear','runtimeMinutes','genres','French_Title','averageRating','numVotes','primaryName'],axis=1)

In [9]:
data2

         tconst                                        description
0     tt0003883  The young daughter of an army captain missing ...
1     tt0006206  An intrepid reporter and his loyal friend batt...
2     tt0006864  The story of a poor young woman, separated by ...
3     tt0006886  A twelve part serial following the adventures ...
4     tt0009968  A frail waif, abused by her brutal boxer fathe...
...         ...                                                ...
9239  tt9892338  In a small beach town in Bangladesh, fearless ...
9240  tt9894394  Upin, Ipin and their friends come across a mys...
9241  tt9900782  A recently released prisoner becomes involved ...
9242  tt9905462  An unusual bond between a sixty year old Dalit...
9243  tt9911196  A middle-aged veterinary surgeon believes his ...

[9244 rows x 2 columns]

In [10]:
data=pd.merge(data1,data2,left_on='tconst',right_on='tconst',how='right')

In [11]:
data

,tconst,titleType,primaryTitle,originalTitle,startYear,French_Title,averageRating,numVotes,Action,Adventure,...,2016,2017,2018,2019,2020,2021,2022,2023,2024,description
0,tt0003883,movie,L'enfant de Paris (1913),L'enfant de Paris (1913),1913,L'Enfant de Paris (1913),7.2,446.0,False,False,...,False,False,False,False,False,False,False,False,False,The young daughter of an army captain missing ...
1,tt0006206,movie,Les vampires (1915),Les vampires (1915),1915,Les vampires (1915),7.3,5398.0,True,True,...,False,False,False,False,False,False,False,False,False,An intrepid reporter and his loyal friend batt...
2,tt0006864,movie,Intolerance (1916),Intolerance: Love's Struggle Throughout the Ag...,1916,Intolérance (1916),7.7,16642.0,False,False,...,False,False,False,False,False,False,False,False,False,"The story of a poor young woman, separated by ..."
3,tt0006886,movie,Judex (1916),Judex (1916),1916,Judex (1916),7.2,1117.0,False,True,...,False,False,False,False,False,False,False,False,False,A twelve part serial following the adventures ...
4,tt0009968,movie,Broken Blossoms (1919),Broken Blossoms or The Yellow Man and the Girl...,1919,Le lys brisé (1919),7.2,11014.0,False,False,...,False,False,False,False,False,False,False,False,False,"A frail waif, abused by her brutal boxer fathe..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10789,tt9892338,movie,Dare to Surf (2019),No Dorai (2019),2019,NaN,7.2,705.0,False,False,...,False,False,False,True,False,False,False,False,False,"In a small beach town in Bangladesh, fearless ..."
10790,tt9894394,movie,Upin & Ipin: Keris Siamang Tunggal (2019),Upin & Ipin: Keris siamang tunggal (2019),2019,NaN,7.3,829.0,False,True,...,False,False,False,True,False,False,False,False,False,"Upin, Ipin and their friends come across a mys..."
10791,tt9900782,movie,Kaithi (2019),Kaithi (2019),2019,Kaithi (2019),8.4,42096.0,True,False,...,False,False,False,True,False,False,False,False,False,A recently released prisoner becomes involved ...
10792,tt9905462,movie,Pengalila (2019),Pengalila (2019),2019,NaN,7.6,680.0,False,False,...,False,False,False,True,False,False,False,False,False,An unusual bond between a sixty year old Dalit...
10793,tt9911196,movie,The Marriage Escape (2020),De beentjes van Sint-Hildegard (2020),2020,De Beentjes van Sint-Hildegard (2020),7.4,3306.0,False,False,...,False,False,False,False,True,False,False,False,False,A middle-aged veterinary surgeon believes his ...

In [12]:
data.duplicated().sum()

1557

In [13]:
#Supprimer ces valeurs en double
data = data.drop_duplicates(subset = "tconst")

In [14]:
# Réindexer le DataFrame après la suppression des doublons
data = data.reset_index(drop=True)

In [15]:
data

,tconst,titleType,primaryTitle,originalTitle,startYear,French_Title,averageRating,numVotes,Action,Adventure,...,2016,2017,2018,2019,2020,2021,2022,2023,2024,description
0,tt0003883,movie,L'enfant de Paris (1913),L'enfant de Paris (1913),1913,L'Enfant de Paris (1913),7.2,446.0,False,False,...,False,False,False,False,False,False,False,False,False,The young daughter of an army captain missing ...
1,tt0006206,movie,Les vampires (1915),Les vampires (1915),1915,Les vampires (1915),7.3,5398.0,True,True,...,False,False,False,False,False,False,False,False,False,An intrepid reporter and his loyal friend batt...
2,tt0006864,movie,Intolerance (1916),Intolerance: Love's Struggle Throughout the Ag...,1916,Intolérance (1916),7.7,16642.0,False,False,...,False,False,False,False,False,False,False,False,False,"The story of a poor young woman, separated by ..."
3,tt0006886,movie,Judex (1916),Judex (1916),1916,Judex (1916),7.2,1117.0,False,True,...,False,False,False,False,False,False,False,False,False,A twelve part serial following the adventures ...
4,tt0009968,movie,Broken Blossoms (1919),Broken Blossoms or The Yellow Man and the Girl...,1919,Le lys brisé (1919),7.2,11014.0,False,False,...,False,False,False,False,False,False,False,False,False,"A frail waif, abused by her brutal boxer fathe..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8582,tt9892338,movie,Dare to Surf (2019),No Dorai (2019),2019,NaN,7.2,705.0,False,False,...,False,False,False,True,False,False,False,False,False,"In a small beach town in Bangladesh, fearless ..."
8583,tt9894394,movie,Upin & Ipin: Keris Siamang Tunggal (2019),Upin & Ipin: Keris siamang tunggal (2019),2019,NaN,7.3,829.0,False,True,...,False,False,False,True,False,False,False,False,False,"Upin, Ipin and their friends come across a mys..."
8584,tt9900782,movie,Kaithi (2019),Kaithi (2019),2019,Kaithi (2019),8.4,42096.0,True,False,...,False,False,False,True,False,False,False,False,False,A recently released prisoner becomes involved ...
8585,tt9905462,movie,Pengalila (2019),Pengalila (2019),2019,NaN,7.6,680.0,False,False,...,False,False,False,True,False,False,False,False,False,An unusual bond between a sixty year old Dalit...
8586,tt9911196,movie,The Marriage Escape (2020),De beentjes van Sint-Hildegard (2020),2020,De Beentjes van Sint-Hildegard (2020),7.4,3306.0,False,False,...,False,False,False,False,True,False,False,False,False,A middle-aged veterinary surgeon believes his ...

In [16]:
data.isnull().sum()

tconst           0
titleType        0
primaryTitle     0
originalTitle    0
startYear        0
                ..
2021             0
2022             0
2023             0
2024             0
description      0
Length: 7383, dtype: int64

In [17]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8587 entries, 0 to 8586
Columns: 7383 entries, tconst to description
dtypes: bool(7374), float64(2), int64(1), object(6)
memory usage: 61.0+ MB

In [18]:
data.head()

,tconst,titleType,primaryTitle,originalTitle,startYear,French_Title,averageRating,numVotes,Action,Adventure,...,2016,2017,2018,2019,2020,2021,2022,2023,2024,description
0,tt0003883,movie,L'enfant de Paris (1913),L'enfant de Paris (1913),1913,L'Enfant de Paris (1913),7.2,446.0,False,False,...,False,False,False,False,False,False,False,False,False,The young daughter of an army captain missing ...
1,tt0006206,movie,Les vampires (1915),Les vampires (1915),1915,Les vampires (1915),7.3,5398.0,True,True,...,False,False,False,False,False,False,False,False,False,An intrepid reporter and his loyal friend batt...
2,tt0006864,movie,Intolerance (1916),Intolerance: Love's Struggle Throughout the Ag...,1916,Intolérance (1916),7.7,16642.0,False,False,...,False,False,False,False,False,False,False,False,False,"The story of a poor young woman, separated by ..."
3,tt0006886,movie,Judex (1916),Judex (1916),1916,Judex (1916),7.2,1117.0,False,True,...,False,False,False,False,False,False,False,False,False,A twelve part serial following the adventures ...
4,tt0009968,movie,Broken Blossoms (1919),Broken Blossoms or The Yellow Man and the Girl...,1919,Le lys brisé (1919),7.2,11014.0,False,False,...,False,False,False,False,False,False,False,False,False,"A frail waif, abused by her brutal boxer fathe..."

In [19]:
X=data.iloc[:,8:-1]
X

,Action,Adventure,Animation,Biography,Comedy,Crime,Divers,Documentary,Drama,Family,...,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
0,False,False,False,False,False,True,False,False,True,False,...,False,False,False,False,False,False,False,False,False,False
1,True,True,False,False,False,True,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,True,False,...,False,False,False,False,False,False,False,False,False,False
3,False,True,False,False,False,True,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,True,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8582,False,False,False,False,False,False,False,False,True,False,...,False,False,False,False,True,False,False,False,False,False
8583,False,True,True,False,True,False,False,False,False,False,...,False,False,False,False,True,False,False,False,False,False
8584,True,False,False,False,False,True,False,False,True,False,...,False,False,False,False,True,False,False,False,False,False
8585,False,False,False,False,False,False,False,False,True,False,...,False,False,False,False,True,False,False,False,False,False
8586,False,False,False,False,True,False,False,False,True,False,...,False,False,False,False,False,True,False,False,False,False

In [20]:
#Entrainer notre modèle: le nombre des k-voisins les plus proches est 5
model1=NearestNeighbors(n_neighbors = 5, metric = "cosine", algorithm = "brute").fit(X)

In [21]:
#trouver le tconst d'un film,case permet au titre du film d'être sensible à la case
movie=data[data.primaryTitle.str.contains('X-Men',case=False)]
movie

,tconst,titleType,primaryTitle,originalTitle,startYear,French_Title,averageRating,numVotes,Action,Adventure,...,2016,2017,2018,2019,2020,2021,2022,2023,2024,description
3801,tt0120903,movie,X-Men (2000),X-Men (2000),2000,X-Men (2000),7.3,643607.0,True,True,...,False,False,False,False,False,False,False,False,False,In a world where mutants (evolved super-powere...
6281,tt1270798,movie,X-Men: First Class (2011),X: First Class (2011),2011,X-Men : Le Commencement (2011),7.7,720951.0,True,False,...,False,False,False,False,False,False,False,False,False,"In the 1960s, superpowered humans Charles Xavi..."
6760,tt1877832,movie,X-Men: Days of Future Past (2014),X-Men: Days of Future Past (2014),2014,X-Men: Days of Future Past (2014),7.9,742384.0,True,True,...,False,False,False,False,False,False,False,False,False,The X-Men send Wolverine to the past in a desp...

In [22]:
#tester avec un film
films = "X-Men (2000)"
data_film_choisi = data[ (data["primaryTitle"] == films) | (data["originalTitle"] == films) | (data["French_Title"] == films) ]
data_film_choisi

,tconst,titleType,primaryTitle,originalTitle,startYear,French_Title,averageRating,numVotes,Action,Adventure,...,2016,2017,2018,2019,2020,2021,2022,2023,2024,description
3801,tt0120903,movie,X-Men (2000),X-Men (2000),2000,X-Men (2000),7.3,643607.0,True,True,...,False,False,False,False,False,False,False,False,False,In a world where mutants (evolved super-powere...

In [23]:
film_choisi = data_film_choisi.iloc[:, 8:-1]
film_choisi

,Action,Adventure,Animation,Biography,Comedy,Crime,Divers,Documentary,Drama,Family,...,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
3801,True,True,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [24]:
#Les cinq voisins les plus proches du film choisi : distance et indices
distance, indice = model1.kneighbors(film_choisi)

In [25]:
distance, indice

(array([[0.        , 0.33333333, 0.44444444, 0.49604737, 0.5527864 ]]),
 array([[3801, 6760, 4850, 7339, 3759]], dtype=int64))

In [26]:
pd.DataFrame(indice)

      0     1     2     3     4
0  3801  6760  4850  7339  3759

In [27]:
pd.DataFrame(indice[0])

      0
0  3801
1  6760
2  4850
3  7339
4  3759

In [28]:
indices=indice[0,1:]
indices

array([6760, 4850, 7339, 3759], dtype=int64)

In [29]:
# On affiche les 4 plus proches voisins 
print("On peut remplacer", films, "par :", data.iloc[indice[0,1:]]['primaryTitle'].values)

On peut remplacer X-Men (2000) par : ['X-Men: Days of Future Past (2014)' 'X2 (2003)' 'Logan (2017)'
 'Starship Troopers (1997)']

In [30]:
# le dataframe des suggestions 
suggestion = data.iloc[indice[0,1:]]
suggestion

,tconst,titleType,primaryTitle,originalTitle,startYear,French_Title,averageRating,numVotes,Action,Adventure,...,2016,2017,2018,2019,2020,2021,2022,2023,2024,description
6760,tt1877832,movie,X-Men: Days of Future Past (2014),X-Men: Days of Future Past (2014),2014,X-Men: Days of Future Past (2014),7.9,742384.0,True,True,...,False,False,False,False,False,False,False,False,False,The X-Men send Wolverine to the past in a desp...
4850,tt0290334,movie,X2 (2003),X2 (2003),2003,X-Men 2 (2003),7.4,573774.0,True,False,...,False,False,False,False,False,False,False,False,False,When anti-mutant Colonel William Stryker kidna...
7339,tt3315342,movie,Logan (2017),Logan (2017),2017,Logan (2017),8.1,825356.0,True,False,...,False,True,False,False,False,False,False,False,False,"In a future where mutants are nearly extinct, ..."
3759,tt0120201,movie,Starship Troopers (1997),Starship Troopers (1997),1997,Starship Troopers (1997),7.3,318611.0,True,True,...,False,False,False,False,False,False,False,False,False,"Humans in a fascist, militaristic future wage ..."

In [31]:
# Evaluation du modèle 
from sklearn.metrics.pairwise import cosine_similarity

# Calculer la similarité cosinus entre le film choisi et ses voisins recommandés
similarities = cosine_similarity(film_choisi, X.iloc[indices])

# Afficher les similarités pour chaque voisin recommandé
for i, sim in enumerate(similarities[0]):
    print(f"Similarité avec le voisin {i + 1}: {sim}")

Similarité avec le voisin 1: 0.6666666666666667
Similarité avec le voisin 2: 0.5555555555555556
Similarité avec le voisin 3: 0.5039526306789696
Similarité avec le voisin 4: 0.44721359549995787