In [39]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.neighbors import KNeighborsClassifier
from sklearn.neighbors import NearestNeighbors

In [40]:
data=pd.read_pickle(r"C:\Users\user\Downloads\Projet ML\Model1(KNN)\Données nettoyées\data_machine_learning_clean.pkl.gz")
data

,tconst,titleType,primaryTitle,originalTitle,startYear,French_Title,averageRating,numVotes,Action,Adventure,...,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
0,tt0003883,movie,L'enfant de Paris (1913),L'enfant de Paris (1913),1913,L'Enfant de Paris (1913),7.2,446.0,False,False,...,False,False,False,False,False,False,False,False,False,False
1,tt0006206,movie,Les vampires (1915),Les vampires (1915),1915,Les vampires (1915),7.3,5398.0,True,True,...,False,False,False,False,False,False,False,False,False,False
2,tt0006864,movie,Intolerance (1916),Intolerance: Love's Struggle Throughout the Ag...,1916,Intolérance (1916),7.7,16642.0,False,False,...,False,False,False,False,False,False,False,False,False,False
3,tt0006886,movie,Judex (1916),Judex (1916),1916,Judex (1916),7.2,1117.0,False,True,...,False,False,False,False,False,False,False,False,False,False
4,tt0009968,movie,Broken Blossoms (1919),Broken Blossoms or The Yellow Man and the Girl...,1919,Le lys brisé (1919),7.2,11014.0,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13089,tt9900782,movie,Kaithi (2019),Kaithi (2019),2019,Kaithi (2019),8.4,42096.0,True,False,...,False,False,False,False,True,False,False,False,False,False
13090,tt9904844,movie,Ott Tänak: The Movie (2019),Ott Tänak: The Movie (2019),2019,NaN,8.1,501.0,False,False,...,False,False,False,False,True,False,False,False,False,False
13091,tt9905462,movie,Pengalila (2019),Pengalila (2019),2019,NaN,7.6,680.0,False,False,...,False,False,False,False,True,False,False,False,False,False
13092,tt9911196,movie,The Marriage Escape (2020),De beentjes van Sint-Hildegard (2020),2020,De Beentjes van Sint-Hildegard (2020),7.4,3306.0,False,False,...,False,False,False,False,False,True,False,False,False,False
13093,tt9911774,movie,Padmavyuhathile Abhimanyu (2019),Padmavyuhathile Abhimanyu (2019),2019,NaN,8.5,380.0,False,False,...,False,False,False,False,True,False,False,False,False,False

In [41]:
data[data['primaryTitle'].str.contains('2024', na=False)]

,tconst,titleType,primaryTitle,originalTitle,startYear,French_Title,averageRating,numVotes,Action,Adventure,...,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
7764,tt11216522,movie,Joshua: Imai Pol Kaka (2024),Joshua: Imai Pol Kaka (2024),2024,Joshua: the protector (2024),7.7,385.0,True,False,...,False,False,False,False,False,False,False,False,False,True
7765,tt11216522,movie,Joshua: Imai Pol Kaka (2024),Joshua: Imai Pol Kaka (2024),2024,Joshua: Imai Pol Kaka (2024),7.7,385.0,True,False,...,False,False,False,False,False,False,False,False,False,True
8501,tt13885428,movie,Anweshippin Kandethum (2024),Anweshippin Kandethum (2024),2024,Anweshippin Kandethum (2024),7.6,3694.0,False,False,...,False,False,False,False,False,False,False,False,False,True
8541,tt14045080,movie,KTM (2024),KTM (2024),2024,NaN,9.3,2069.0,False,False,...,False,False,False,False,False,False,False,False,False,True
8614,tt14351082,movie,Cabrini (2024),Cabrini (2024),2024,Cabrini (2024),8.1,1585.0,False,False,...,False,False,False,False,False,False,False,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10866,tt31410930,movie,You Are Not Alone: Fighting the Wolf Pack (2024),No estás sola (2024),2024,No estás sola: Ensemble face à la meute (2024),7.4,426.0,False,False,...,False,False,False,False,False,False,False,False,False,True
10867,tt31410956,movie,Nalla Perai Vaanga Vendum Pillaigale (2024),Nalla Perai Vaanga Vendum Pillaigale (2024),2024,NaN,9.1,550.0,False,False,...,False,False,False,False,False,False,False,False,False,True
10868,tt31414473,movie,Babu (No.1 Bullshit Guy) (2024),Babu (No.1 Bullshit Guy) (2024),2024,NaN,8.4,2029.0,False,False,...,False,False,False,False,False,False,False,False,False,True
10870,tt31435295,movie,Purushothamana Prasanga (2024),Purushothamana Prasanga (2024),2024,NaN,9.4,1146.0,False,False,...,False,False,False,False,False,False,False,False,False,True
11609,tt4996328,movie,Ordinary Angels (2024),Ordinary Angels (2024),2024,Ordinary Angels (2024),7.8,1453.0,False,False,...,False,False,False,False,False,False,False,False,False,True

In [42]:
#Nombre de valeurs en double
data['tconst'].duplicated().sum()

772

In [43]:
#Supprimer ces valeurs en double
data = data.drop_duplicates(subset = "tconst")

In [44]:
# Réindexer le DataFrame après la suppression des doublons
data = data.reset_index(drop=True)

In [45]:
data

,tconst,titleType,primaryTitle,originalTitle,startYear,French_Title,averageRating,numVotes,Action,Adventure,...,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
0,tt0003883,movie,L'enfant de Paris (1913),L'enfant de Paris (1913),1913,L'Enfant de Paris (1913),7.2,446.0,False,False,...,False,False,False,False,False,False,False,False,False,False
1,tt0006206,movie,Les vampires (1915),Les vampires (1915),1915,Les vampires (1915),7.3,5398.0,True,True,...,False,False,False,False,False,False,False,False,False,False
2,tt0006864,movie,Intolerance (1916),Intolerance: Love's Struggle Throughout the Ag...,1916,Intolérance (1916),7.7,16642.0,False,False,...,False,False,False,False,False,False,False,False,False,False
3,tt0006886,movie,Judex (1916),Judex (1916),1916,Judex (1916),7.2,1117.0,False,True,...,False,False,False,False,False,False,False,False,False,False
4,tt0009968,movie,Broken Blossoms (1919),Broken Blossoms or The Yellow Man and the Girl...,1919,Le lys brisé (1919),7.2,11014.0,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12317,tt9900782,movie,Kaithi (2019),Kaithi (2019),2019,Kaithi (2019),8.4,42096.0,True,False,...,False,False,False,False,True,False,False,False,False,False
12318,tt9904844,movie,Ott Tänak: The Movie (2019),Ott Tänak: The Movie (2019),2019,NaN,8.1,501.0,False,False,...,False,False,False,False,True,False,False,False,False,False
12319,tt9905462,movie,Pengalila (2019),Pengalila (2019),2019,NaN,7.6,680.0,False,False,...,False,False,False,False,True,False,False,False,False,False
12320,tt9911196,movie,The Marriage Escape (2020),De beentjes van Sint-Hildegard (2020),2020,De Beentjes van Sint-Hildegard (2020),7.4,3306.0,False,False,...,False,False,False,False,False,True,False,False,False,False
12321,tt9911774,movie,Padmavyuhathile Abhimanyu (2019),Padmavyuhathile Abhimanyu (2019),2019,NaN,8.5,380.0,False,False,...,False,False,False,False,True,False,False,False,False,False

In [46]:
#Definir la variable X : les features qui ne contiennent que des booléens
X=data.iloc[:,8:]
X

,Action,Adventure,Animation,Biography,Comedy,Crime,Divers,Documentary,Drama,Family,...,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
0,False,False,False,False,False,True,False,False,True,False,...,False,False,False,False,False,False,False,False,False,False
1,True,True,False,False,False,True,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,True,False,...,False,False,False,False,False,False,False,False,False,False
3,False,True,False,False,False,True,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,True,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12317,True,False,False,False,False,True,False,False,True,False,...,False,False,False,False,True,False,False,False,False,False
12318,False,False,False,False,False,False,False,True,False,False,...,False,False,False,False,True,False,False,False,False,False
12319,False,False,False,False,False,False,False,False,True,False,...,False,False,False,False,True,False,False,False,False,False
12320,False,False,False,False,True,False,False,False,True,False,...,False,False,False,False,False,True,False,False,False,False
12321,False,False,False,False,False,False,False,False,True,False,...,False,False,False,False,True,False,False,False,False,False

#  Entrée 1: le nom du film préferé

In [47]:
#Entrainer notre modèle: le nombre des k-voisins les plus proches est 5
model1=NearestNeighbors(n_neighbors = 5, metric = "cosine", algorithm = "brute").fit(X)

Recommandation d'un film

In [48]:
#trouver le tconst d'un film insensible à la case
movie=data[data.primaryTitle.str.contains('X-Men',case=False)]
movie

,tconst,titleType,primaryTitle,originalTitle,startYear,French_Title,averageRating,numVotes,Action,Adventure,...,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
4125,tt0120903,movie,X-Men (2000),X-Men (2000),2000,X-Men (2000),7.3,643607.0,True,True,...,False,False,False,False,False,False,False,False,False,False
7558,tt1270798,movie,X-Men: First Class (2011),X: First Class (2011),2011,X-Men : Le Commencement (2011),7.7,720951.0,True,False,...,False,False,False,False,False,False,False,False,False,False
8812,tt1877832,movie,X-Men: Days of Future Past (2014),X-Men: Days of Future Past (2014),2014,X-Men: Days of Future Past (2014),7.9,742384.0,True,True,...,False,False,False,False,False,False,False,False,False,False

In [49]:
#tester avec un film
films = "X-Men (2000)"
data_film_choisi = data[ (data["primaryTitle"] == films) | (data["originalTitle"] == films) | (data["French_Title"] == films) ]
data_film_choisi

,tconst,titleType,primaryTitle,originalTitle,startYear,French_Title,averageRating,numVotes,Action,Adventure,...,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
4125,tt0120903,movie,X-Men (2000),X-Men (2000),2000,X-Men (2000),7.3,643607.0,True,True,...,False,False,False,False,False,False,False,False,False,False

In [50]:
film_choisi = data_film_choisi.iloc[:, 8:]
film_choisi

,Action,Adventure,Animation,Biography,Comedy,Crime,Divers,Documentary,Drama,Family,...,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
4125,True,True,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [51]:
#Les cinq voisins les plus proches du film choisi : distance et indices
distance, indice = model1.kneighbors(film_choisi)

In [52]:
distance, indice

(array([[0.        , 0.33333333, 0.44444444, 0.49604737, 0.5527864 ]]),
 array([[ 4125,  8812,  5302, 10270,  4080]], dtype=int64))

In [53]:
pd.DataFrame(indice)

      0     1     2      3     4
0  4125  8812  5302  10270  4080

In [54]:
pd.DataFrame(indice[0])

       0
0   4125
1   8812
2   5302
3  10270
4   4080

In [55]:
indices=indice[0,1:]
indices

array([ 8812,  5302, 10270,  4080], dtype=int64)

In [56]:
# On affiche les 4 plus proches voisins 
print("On peut remplacer", films, "par :", data.iloc[indice[0,1:]]['primaryTitle'].values)

On peut remplacer X-Men (2000) par : ['X-Men: Days of Future Past (2014)' 'X2 (2003)' 'Logan (2017)'
 'Starship Troopers (1997)']

In [57]:
# le dataframe des suggestions 
suggestion = data.iloc[indice[0,1:]]
suggestion

,tconst,titleType,primaryTitle,originalTitle,startYear,French_Title,averageRating,numVotes,Action,Adventure,...,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
8812,tt1877832,movie,X-Men: Days of Future Past (2014),X-Men: Days of Future Past (2014),2014,X-Men: Days of Future Past (2014),7.9,742384.0,True,True,...,False,False,False,False,False,False,False,False,False,False
5302,tt0290334,movie,X2 (2003),X2 (2003),2003,X-Men 2 (2003),7.4,573774.0,True,False,...,False,False,False,False,False,False,False,False,False,False
10270,tt3315342,movie,Logan (2017),Logan (2017),2017,Logan (2017),8.1,825356.0,True,False,...,False,False,True,False,False,False,False,False,False,False
4080,tt0120201,movie,Starship Troopers (1997),Starship Troopers (1997),1997,Starship Troopers (1997),7.3,318611.0,True,True,...,False,False,False,False,False,False,False,False,False,False

In [58]:
# Evaluation du modèle 
from sklearn.metrics.pairwise import cosine_similarity

# Calculer la similarité cosinus entre le film choisi et ses voisins recommandés
similarities = cosine_similarity(film_choisi, X.iloc[indices])

# Afficher les similarités pour chaque voisin recommandé
for i, sim in enumerate(similarities[0]):
    print(f"Similarité avec le voisin {i + 1}: {sim}")

Similarité avec le voisin 1: 0.6666666666666667
Similarité avec le voisin 2: 0.5555555555555556
Similarité avec le voisin 3: 0.5039526306789696
Similarité avec le voisin 4: 0.44721359549995787

In [59]:
#Evaluation du modèle

In [22]:
#Evaluation du modèle

# Entrée 2: FILTRES ACTEURS, ANNEES, GENRE

Choix renseignés par l'utilisateur

In [23]:
genre_choisi = 'Adventure'
liste_genres_choisi = ['Comedy', 'Adventure','Documentary']
start_year = 1981
end_year = 2003
acteur_choisi = "Amitabh Bachchan"

In [24]:
data1 = data[(data[acteur_choisi] == True) & (data["startYear"] > start_year) & (data["startYear"] < end_year)]
data1 = data1.sort_values(by ='averageRating' , ascending = False)
data1

,tconst,titleType,primaryTitle,originalTitle,startYear,French_Title,averageRating,numVotes,Action,Adventure,...,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
2791,tt0084667,movie,Shakti (1982),Shakti (1982),1982,NaN,7.6,2351.0,True,False,...,False,False,False,False,False,False,False,False,False,False
3368,tt0098999,movie,Agneepath (1990),Agneepath (1990),1990,NaN,7.6,9429.0,True,False,...,False,False,False,False,False,False,False,False,False,False
4965,tt0248126,movie,Kabhi Khushi Kabhie Gham... (2001),Kabhi Khushi Kabhie Gham... (2001),2001,La famille indienne (2001),7.4,55287.0,False,False,...,False,False,False,False,False,False,False,False,False,False
5404,tt0306434,movie,Aankhen (2002),Aankhen (2002),2002,Eyes - Aankhen (2002),7.4,13912.0,False,False,...,False,False,False,False,False,False,False,False,False,False
2959,tt0088099,movie,Sharaabi (1984),Sharaabi (1984),1984,NaN,7.3,3102.0,False,False,...,False,False,False,False,False,False,False,False,False,False
3332,tt0097812,movie,Main Azaad Hoon (1989),Main Azaad Hoon (1989),1989,NaN,7.3,782.0,False,False,...,False,False,False,False,False,False,False,False,False,False
2767,tt0084385,movie,Namak Halaal (1982),Namak Halaal (1982),1982,NaN,7.2,2804.0,True,False,...,False,False,False,False,False,False,False,False,False,False
2787,tt0084630,movie,Satte Pe Satta (1982),Satte Pe Satta (1982),1982,NaN,7.2,3605.0,True,False,...,False,False,False,False,False,False,False,False,False,False

first proposition avec l'acteur

In [25]:
data1["startYear"].unique()

array([1982, 1990, 2001, 2002, 1984, 1989], dtype=int64)

In [26]:
# TOP 5 des films acteurs classés par note
data_top5_acteur_choisi = data1.head()
data_top5_acteur_choisi

,tconst,titleType,primaryTitle,originalTitle,startYear,French_Title,averageRating,numVotes,Action,Adventure,...,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
2791,tt0084667,movie,Shakti (1982),Shakti (1982),1982,NaN,7.6,2351.0,True,False,...,False,False,False,False,False,False,False,False,False,False
3368,tt0098999,movie,Agneepath (1990),Agneepath (1990),1990,NaN,7.6,9429.0,True,False,...,False,False,False,False,False,False,False,False,False,False
4965,tt0248126,movie,Kabhi Khushi Kabhie Gham... (2001),Kabhi Khushi Kabhie Gham... (2001),2001,La famille indienne (2001),7.4,55287.0,False,False,...,False,False,False,False,False,False,False,False,False,False
5404,tt0306434,movie,Aankhen (2002),Aankhen (2002),2002,Eyes - Aankhen (2002),7.4,13912.0,False,False,...,False,False,False,False,False,False,False,False,False,False
2959,tt0088099,movie,Sharaabi (1984),Sharaabi (1984),1984,NaN,7.3,3102.0,False,False,...,False,False,False,False,False,False,False,False,False,False

In [27]:
# On récupère seulement les codes des films tconst 
tconst_acteur = data_top5_acteur_choisi.iloc[:,:]['tconst'].values
tconst_acteur

array(['tt0084667', 'tt0098999', 'tt0248126', 'tt0306434', 'tt0088099'],
      dtype=object)

In [28]:
# On récupère seulement le nom des films
suggestion_acteur = data_top5_acteur_choisi.iloc[:,:]['primaryTitle'].values
suggestion_acteur

array(['Shakti (1982)', 'Agneepath (1990)',
       'Kabhi Khushi Kabhie Gham... (2001)', 'Aankhen (2002)',
       'Sharaabi (1984)'], dtype=object)

# Deuxieme proposition : le genre et l'année

Un seul genre

In [29]:
data2 = data[(data[genre_choisi] == True)&(data["startYear"] >= start_year)&(data["startYear"] <= end_year)]
data2.head()

,tconst,titleType,primaryTitle,originalTitle,startYear,French_Title,averageRating,numVotes,Action,Adventure,...,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
2606,tt0080494,movie,Mercenaries' Trap (1981),Capcana mercenarilor (1981),1981,NaN,7.8,438.0,False,True,...,False,False,False,False,False,False,False,False,False,False
2662,tt0082183,movie,La Chèvre (1981),La chèvre (1981),1981,La Chèvre (1981),7.3,10537.0,False,True,...,False,False,False,False,False,False,False,False,False,False
2675,tt0082348,movie,Excalibur (1981),Excalibur (1981),1981,Excalibur (1981),7.3,66792.0,False,True,...,False,False,False,False,False,False,False,False,False,False
2678,tt0082406,movie,The Fox and the Hound (1981),The Fox and the Hound (1981),1981,Rox et Rouky (1981),7.2,101292.0,False,True,...,False,False,False,False,False,False,False,False,False,False
2679,tt0082432,movie,Gallipoli (1981),Gallipoli (1981),1981,Gallipoli (1981),7.4,41811.0,False,True,...,False,False,False,False,False,False,False,False,False,False

In [30]:
# Classer dans l'ordre decroissant  averageRating
data2 = data2.sort_values(by ='averageRating' , ascending = False)
data2

,tconst,titleType,primaryTitle,originalTitle,startYear,French_Title,averageRating,numVotes,Action,Adventure,...,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
5076,tt0259534,movie,Ramayana: The Legend of Prince Rama (1993),Ramayana: The Legend of Prince Rama (1993),1993,Ramayana: The Legend of Prince Rama (1993),9.2,14375.0,True,True,...,False,False,False,False,False,False,False,False,False,False
4466,tt0167260,movie,The Lord of the Rings: The Return of the King ...,The Lord of the Rings: The Return of the King ...,2003,Le Seigneur des anneaux : Le Retour du roi (20...,9.0,1966577.0,True,True,...,False,False,False,False,False,False,False,False,False,False
4114,tt0120737,movie,The Lord of the Rings: The Fellowship of the R...,The Lord of the Rings: The Fellowship of the R...,2001,Le Seigneur des anneaux : La Communauté de l'a...,8.9,1994593.0,True,True,...,False,False,False,False,False,False,False,False,False,False
8860,tt1935109,movie,Dipu Number 2 (1996),Dipu Number 2 (1996),1996,NaN,8.9,2564.0,False,True,...,False,False,False,False,False,False,False,False,False,False
4467,tt0167261,movie,The Lord of the Rings: The Two Towers (2002),The Lord of the Rings: The Two Towers (2002),2002,Le Seigneur des anneaux : Les Deux Tours (2002),8.8,1772915.0,True,True,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3498,tt0102975,movie,Star Trek VI: The Undiscovered Country (1991),Star Trek VI: The Undiscovered Country (1991),1991,Star Trek VI : Terre inconnue (1991),7.2,80606.0,True,True,...,False,False,False,False,False,False,False,False,False,False
5341,tt0293416,movie,Metropolis (2001),Metoroporisu (2001),2001,Metropolis (2001),7.2,22527.0,False,True,...,False,False,False,False,False,False,False,False,False,False
3183,tt0093668,movie,Pathfinder (1987),Ofelas (1987),1987,Le passeur (1987),7.2,5567.0,True,True,...,False,False,False,False,False,False,False,False,False,False
2757,tt0084296,movie,The Man from Snowy River (1982),The Man from Snowy River (1982),1982,L'homme de la rivière d'argent (1982),7.2,9954.0,False,True,...,False,False,False,False,False,False,False,False,False,False
4243,tt0133930,movie,Lapitch the Little Shoemaker (1997),Cudnovate zgode segrta Hlapica (1997),1997,NaN,7.2,630.0,False,True,...,False,False,False,False,False,False,False,False,False,False

In [31]:
data2["startYear"].unique()

array([1993, 2003, 2001, 1996, 2002, 1991, 1994, 2000, 1985, 1981, 1986,
       1983, 1997, 1995, 1988, 1998, 1989, 1999, 1984, 1990, 1987, 1992,
       1982], dtype=int64)

In [32]:
# TOP 5 des films GENRES classés par note
data_top5_genre_choisi = data2.head()
data_top5_genre_choisi

,tconst,titleType,primaryTitle,originalTitle,startYear,French_Title,averageRating,numVotes,Action,Adventure,...,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
5076,tt0259534,movie,Ramayana: The Legend of Prince Rama (1993),Ramayana: The Legend of Prince Rama (1993),1993,Ramayana: The Legend of Prince Rama (1993),9.2,14375.0,True,True,...,False,False,False,False,False,False,False,False,False,False
4466,tt0167260,movie,The Lord of the Rings: The Return of the King ...,The Lord of the Rings: The Return of the King ...,2003,Le Seigneur des anneaux : Le Retour du roi (20...,9.0,1966577.0,True,True,...,False,False,False,False,False,False,False,False,False,False
4114,tt0120737,movie,The Lord of the Rings: The Fellowship of the R...,The Lord of the Rings: The Fellowship of the R...,2001,Le Seigneur des anneaux : La Communauté de l'a...,8.9,1994593.0,True,True,...,False,False,False,False,False,False,False,False,False,False
8860,tt1935109,movie,Dipu Number 2 (1996),Dipu Number 2 (1996),1996,NaN,8.9,2564.0,False,True,...,False,False,False,False,False,False,False,False,False,False
4467,tt0167261,movie,The Lord of the Rings: The Two Towers (2002),The Lord of the Rings: The Two Towers (2002),2002,Le Seigneur des anneaux : Les Deux Tours (2002),8.8,1772915.0,True,True,...,False,False,False,False,False,False,False,False,False,False

In [33]:
# On récupère uniquement les codes films tconst 
tconst_genre =data_top5_genre_choisi.iloc[:,:]['tconst'].values
tconst_genre

array(['tt0259534', 'tt0167260', 'tt0120737', 'tt1935109', 'tt0167261'],
      dtype=object)

In [34]:
# On récupère seulement le nom des films  
suggestion_genre = data_top5_genre_choisi.iloc[:,:]['primaryTitle'].values
suggestion_genre

array(['Ramayana: The Legend of Prince Rama (1993)',
       'The Lord of the Rings: The Return of the King (2003)',
       'The Lord of the Rings: The Fellowship of the Ring (2001)',
       'Dipu Number 2 (1996)',
       'The Lord of the Rings: The Two Towers (2002)'], dtype=object)

Plusieurs genres

In [35]:
#Créer un DF filtré SUR LA PERIODE ET LES GENRES renseignés par l'utilisateur

data3 = pd.DataFrame()
for genre in liste_genres_choisi : 
    data_genre= data[ (data[genre] == True) & (data["startYear"] >= start_year)&(data["startYear"] <= end_year) ]
    data3 = pd.concat([data3 ,data_genre])
                                 
data3.head()

,tconst,titleType,primaryTitle,originalTitle,startYear,French_Title,averageRating,numVotes,Action,Adventure,...,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
2616,tt0080728,movie,The Aviator's Wife (1981),La femme de l'aviateur (1981),1981,La femme de l'aviateur (1981),7.5,5134.0,False,False,...,False,False,False,False,False,False,False,False,False,False
2636,tt0081349,movie,A Pogány Madonna (1981),A Pogány Madonna (1981),1981,NaN,7.4,1713.0,False,False,...,False,False,False,False,False,False,False,False,False,False
2637,tt0081363,movie,Cutting it Short (1981),Postriziny (1981),1981,Une blonde émoustillante (1981),7.6,2697.0,False,False,...,False,False,False,False,False,False,False,False,False,False
2640,tt0081427,movie,Ricomincio da tre (1981),Ricomincio da tre (1981),1981,NaN,7.4,2915.0,False,False,...,False,False,False,False,False,False,False,False,False,False
2648,tt0081730,movie,"Run, Waiter, Run! (1981)","Vrchní, prchni! (1981)",1981,NaN,7.9,2242.0,False,False,...,False,False,False,False,False,False,False,False,False,False

In [36]:
data3["startYear"].unique()

array([1981, 1982, 1983, 1984, 1985, 1986, 1987, 1988, 1989, 1990, 1991,
       1992, 1993, 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002,
       2003], dtype=int64)

In [37]:
# Classer dans l'ordre decroissant averageRating
data3 = data3.sort_values(by ='averageRating' , ascending = False)

In [38]:
# TOP 5 des films GENRES classés par note
data_top5_genre_choisi_2 = data3.head()
data_top5_genre_choisi_2

,tconst,titleType,primaryTitle,originalTitle,startYear,French_Title,averageRating,numVotes,Action,Adventure,...,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
8780,tt1852112,movie,Svet Koji Nestaje (1987),Svet Koji Nestaje (1987),1987,NaN,9.5,365.0,False,False,...,False,False,False,False,False,False,False,False,False,False
5076,tt0259534,movie,Ramayana: The Legend of Prince Rama (1993),Ramayana: The Legend of Prince Rama (1993),1993,Ramayana: The Legend of Prince Rama (1993),9.2,14375.0,True,True,...,False,False,False,False,False,False,False,False,False,False
5637,tt0353975,movie,Sandesham (1991),Sandesham (1991),1991,NaN,9.0,5086.0,False,False,...,False,False,False,False,False,False,False,False,False,False
4983,tt0249336,movie,Aha Naa Pellanta (1987),Aha Naa Pellanta (1987),1987,NaN,9.0,3280.0,False,False,...,False,False,False,False,False,False,False,False,False,False
4466,tt0167260,movie,The Lord of the Rings: The Return of the King ...,The Lord of the Rings: The Return of the King ...,2003,Le Seigneur des anneaux : Le Retour du roi (20...,9.0,1966577.0,True,True,...,False,False,False,False,False,False,False,False,False,False