In [31]:
import pandas as pd
import numpy as np

In [32]:
fusion_final =pd.read_csv(r"C:\Users\user\Downloads\Projet ML\Model1(KNN)\Données nettoyées\fusion_final.csv", sep = ",")

In [33]:
# Ajouter l'année après le nom du film pour éviter la confusion s'il y'a plusieurs films avec le même titre
fusion_final['primaryTitle'] = fusion_final['primaryTitle']+ ' (' + fusion_final['startYear'].map(str) + ')'
fusion_final['originalTitle'] = fusion_final['originalTitle']+ ' (' + fusion_final['startYear'].map(str) + ')'
fusion_final['French_Title'] = fusion_final['French_Title']+ ' (' + fusion_final['startYear'].map(str) + ') '

In [34]:
fusion_final

,Unnamed: 0.1,tconst,titleType,primaryTitle,originalTitle,startYear,runtimeMinutes,genres,Unnamed: 0,French_Title,averageRating,numVotes,primaryName
0,0,tt0003883,movie,L'enfant de Paris (1913),L'enfant de Paris (1913),1913,124.0,"Crime,Drama",11535.0,L'Enfant de Paris (1913),7.2,446.0,"Léonce Perret,Louis Leubas,Maurice Lagrenée,Ém..."
1,1,tt0006206,movie,Les vampires (1915),Les vampires (1915),1915,421.0,"Action,Adventure,Crime",18854.0,Les vampires (1915),7.3,5398.0,"Stacia Napierkowska,Musidora,Édouard Mathé,Mar..."
2,2,tt0006864,movie,Intolerance (1916),Intolerance: Love's Struggle Throughout the Ag...,1916,163.0,"Drama,History",21087.0,Intolérance (1916),7.7,16642.0,"Lillian Gish,Robert Harron,Mae Marsh,F.A. Turner"
3,3,tt0006886,movie,Judex (1916),Judex (1916),1916,300.0,"Adventure,Crime",21159.0,Judex (1916),7.2,1117.0,"René Cresté,Musidora,René Poyen,Édouard Mathé"
4,4,tt0009968,movie,Broken Blossoms (1919),Broken Blossoms or The Yellow Man and the Girl...,1919,90.0,"Drama,Romance",32134.0,Le lys brisé (1919),7.2,11014.0,"Norman Selby,Lillian Gish,Richard Barthelmess,..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...
13089,13089,tt9900782,movie,Kaithi (2019),Kaithi (2019),2019,145.0,"Action,Crime,Drama",38883269.0,Kaithi (2019),8.4,42096.0,"Karthi,Narain,Arjun Das,George Maryan"
13090,13090,tt9904844,movie,Ott Tänak: The Movie (2019),Ott Tänak: The Movie (2019),2019,125.0,"Documentary,Sport",NaN,NaN,8.1,501.0,NaN
13091,13091,tt9905462,movie,Pengalila (2019),Pengalila (2019),2019,111.0,Drama,NaN,NaN,7.6,680.0,NaN
13092,13092,tt9911196,movie,The Marriage Escape (2020),De beentjes van Sint-Hildegard (2020),2020,103.0,"Comedy,Drama",38903533.0,De Beentjes van Sint-Hildegard (2020),7.4,3306.0,"Herman Finkers,Johanna ter Steege,Leonie ter B..."
13093,13093,tt9911774,movie,Padmavyuhathile Abhimanyu (2019),Padmavyuhathile Abhimanyu (2019),2019,130.0,Drama,NaN,NaN,8.5,380.0,NaN

In [35]:
fusion_final=fusion_final.drop(['Unnamed: 0.1','Unnamed: 0'],axis=1)
fusion_final

,tconst,titleType,primaryTitle,originalTitle,startYear,runtimeMinutes,genres,French_Title,averageRating,numVotes,primaryName
0,tt0003883,movie,L'enfant de Paris (1913),L'enfant de Paris (1913),1913,124.0,"Crime,Drama",L'Enfant de Paris (1913),7.2,446.0,"Léonce Perret,Louis Leubas,Maurice Lagrenée,Ém..."
1,tt0006206,movie,Les vampires (1915),Les vampires (1915),1915,421.0,"Action,Adventure,Crime",Les vampires (1915),7.3,5398.0,"Stacia Napierkowska,Musidora,Édouard Mathé,Mar..."
2,tt0006864,movie,Intolerance (1916),Intolerance: Love's Struggle Throughout the Ag...,1916,163.0,"Drama,History",Intolérance (1916),7.7,16642.0,"Lillian Gish,Robert Harron,Mae Marsh,F.A. Turner"
3,tt0006886,movie,Judex (1916),Judex (1916),1916,300.0,"Adventure,Crime",Judex (1916),7.2,1117.0,"René Cresté,Musidora,René Poyen,Édouard Mathé"
4,tt0009968,movie,Broken Blossoms (1919),Broken Blossoms or The Yellow Man and the Girl...,1919,90.0,"Drama,Romance",Le lys brisé (1919),7.2,11014.0,"Norman Selby,Lillian Gish,Richard Barthelmess,..."
...,...,...,...,...,...,...,...,...,...,...,...
13089,tt9900782,movie,Kaithi (2019),Kaithi (2019),2019,145.0,"Action,Crime,Drama",Kaithi (2019),8.4,42096.0,"Karthi,Narain,Arjun Das,George Maryan"
13090,tt9904844,movie,Ott Tänak: The Movie (2019),Ott Tänak: The Movie (2019),2019,125.0,"Documentary,Sport",NaN,8.1,501.0,NaN
13091,tt9905462,movie,Pengalila (2019),Pengalila (2019),2019,111.0,Drama,NaN,7.6,680.0,NaN
13092,tt9911196,movie,The Marriage Escape (2020),De beentjes van Sint-Hildegard (2020),2020,103.0,"Comedy,Drama",De Beentjes van Sint-Hildegard (2020),7.4,3306.0,"Herman Finkers,Johanna ter Steege,Leonie ter B..."
13093,tt9911774,movie,Padmavyuhathile Abhimanyu (2019),Padmavyuhathile Abhimanyu (2019),2019,130.0,Drama,NaN,8.5,380.0,NaN

In [36]:
#enregistrer au format pickle
fusion_final.to_pickle(r"C:\Users\user\Downloads\Projet ML\Model1(KNN)\Données nettoyées\fusion_final.pkl.gz", compression = 'gzip')
fusion_final = pd.read_pickle(r"C:\Users\user\Downloads\Projet ML\Model1(KNN)\Données nettoyées\fusion_final.pkl.gz")
fusion_final

,tconst,titleType,primaryTitle,originalTitle,startYear,runtimeMinutes,genres,French_Title,averageRating,numVotes,primaryName
0,tt0003883,movie,L'enfant de Paris (1913),L'enfant de Paris (1913),1913,124.0,"Crime,Drama",L'Enfant de Paris (1913),7.2,446.0,"Léonce Perret,Louis Leubas,Maurice Lagrenée,Ém..."
1,tt0006206,movie,Les vampires (1915),Les vampires (1915),1915,421.0,"Action,Adventure,Crime",Les vampires (1915),7.3,5398.0,"Stacia Napierkowska,Musidora,Édouard Mathé,Mar..."
2,tt0006864,movie,Intolerance (1916),Intolerance: Love's Struggle Throughout the Ag...,1916,163.0,"Drama,History",Intolérance (1916),7.7,16642.0,"Lillian Gish,Robert Harron,Mae Marsh,F.A. Turner"
3,tt0006886,movie,Judex (1916),Judex (1916),1916,300.0,"Adventure,Crime",Judex (1916),7.2,1117.0,"René Cresté,Musidora,René Poyen,Édouard Mathé"
4,tt0009968,movie,Broken Blossoms (1919),Broken Blossoms or The Yellow Man and the Girl...,1919,90.0,"Drama,Romance",Le lys brisé (1919),7.2,11014.0,"Norman Selby,Lillian Gish,Richard Barthelmess,..."
...,...,...,...,...,...,...,...,...,...,...,...
13089,tt9900782,movie,Kaithi (2019),Kaithi (2019),2019,145.0,"Action,Crime,Drama",Kaithi (2019),8.4,42096.0,"Karthi,Narain,Arjun Das,George Maryan"
13090,tt9904844,movie,Ott Tänak: The Movie (2019),Ott Tänak: The Movie (2019),2019,125.0,"Documentary,Sport",NaN,8.1,501.0,NaN
13091,tt9905462,movie,Pengalila (2019),Pengalila (2019),2019,111.0,Drama,NaN,7.6,680.0,NaN
13092,tt9911196,movie,The Marriage Escape (2020),De beentjes van Sint-Hildegard (2020),2020,103.0,"Comedy,Drama",De Beentjes van Sint-Hildegard (2020),7.4,3306.0,"Herman Finkers,Johanna ter Steege,Leonie ter B..."
13093,tt9911774,movie,Padmavyuhathile Abhimanyu (2019),Padmavyuhathile Abhimanyu (2019),2019,130.0,Drama,NaN,8.5,380.0,NaN

# La méthode dummies

Diviser les genres

In [37]:
# encodage + tranformation en booléen
data_genres = fusion_final["genres"].str.get_dummies(sep=',').astype(bool) 
data_genres

,Action,Adult,Adventure,Animation,Biography,Comedy,Crime,Divers,Documentary,Drama,...,Mystery,News,Reality-TV,Romance,Sci-Fi,Sport,Talk-Show,Thriller,War,Western
0,False,False,False,False,False,False,True,False,False,True,...,False,False,False,False,False,False,False,False,False,False
1,True,False,True,False,False,False,True,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,True,...,False,False,False,False,False,False,False,False,False,False
3,False,False,True,False,False,False,True,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,True,...,False,False,False,True,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13089,True,False,False,False,False,False,True,False,False,True,...,False,False,False,False,False,False,False,False,False,False
13090,False,False,False,False,False,False,False,False,True,False,...,False,False,False,False,False,True,False,False,False,False
13091,False,False,False,False,False,False,False,False,False,True,...,False,False,False,False,False,False,False,False,False,False
13092,False,False,False,False,False,True,False,False,False,True,...,False,False,False,False,False,False,False,False,False,False
13093,False,False,False,False,False,False,False,False,False,True,...,False,False,False,False,False,False,False,False,False,False

In [38]:
# on concat sur les colonnes le data_genres avec fusion_final sans la colonne "genres"
data_diviser = pd.concat([fusion_final.drop(columns="genres"), data_genres ], axis=1)
data_diviser

,tconst,titleType,primaryTitle,originalTitle,startYear,runtimeMinutes,French_Title,averageRating,numVotes,primaryName,...,Mystery,News,Reality-TV,Romance,Sci-Fi,Sport,Talk-Show,Thriller,War,Western
0,tt0003883,movie,L'enfant de Paris (1913),L'enfant de Paris (1913),1913,124.0,L'Enfant de Paris (1913),7.2,446.0,"Léonce Perret,Louis Leubas,Maurice Lagrenée,Ém...",...,False,False,False,False,False,False,False,False,False,False
1,tt0006206,movie,Les vampires (1915),Les vampires (1915),1915,421.0,Les vampires (1915),7.3,5398.0,"Stacia Napierkowska,Musidora,Édouard Mathé,Mar...",...,False,False,False,False,False,False,False,False,False,False
2,tt0006864,movie,Intolerance (1916),Intolerance: Love's Struggle Throughout the Ag...,1916,163.0,Intolérance (1916),7.7,16642.0,"Lillian Gish,Robert Harron,Mae Marsh,F.A. Turner",...,False,False,False,False,False,False,False,False,False,False
3,tt0006886,movie,Judex (1916),Judex (1916),1916,300.0,Judex (1916),7.2,1117.0,"René Cresté,Musidora,René Poyen,Édouard Mathé",...,False,False,False,False,False,False,False,False,False,False
4,tt0009968,movie,Broken Blossoms (1919),Broken Blossoms or The Yellow Man and the Girl...,1919,90.0,Le lys brisé (1919),7.2,11014.0,"Norman Selby,Lillian Gish,Richard Barthelmess,...",...,False,False,False,True,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13089,tt9900782,movie,Kaithi (2019),Kaithi (2019),2019,145.0,Kaithi (2019),8.4,42096.0,"Karthi,Narain,Arjun Das,George Maryan",...,False,False,False,False,False,False,False,False,False,False
13090,tt9904844,movie,Ott Tänak: The Movie (2019),Ott Tänak: The Movie (2019),2019,125.0,NaN,8.1,501.0,NaN,...,False,False,False,False,False,True,False,False,False,False
13091,tt9905462,movie,Pengalila (2019),Pengalila (2019),2019,111.0,NaN,7.6,680.0,NaN,...,False,False,False,False,False,False,False,False,False,False
13092,tt9911196,movie,The Marriage Escape (2020),De beentjes van Sint-Hildegard (2020),2020,103.0,De Beentjes van Sint-Hildegard (2020),7.4,3306.0,"Herman Finkers,Johanna ter Steege,Leonie ter B...",...,False,False,False,False,False,False,False,False,False,False
13093,tt9911774,movie,Padmavyuhathile Abhimanyu (2019),Padmavyuhathile Abhimanyu (2019),2019,130.0,NaN,8.5,380.0,NaN,...,False,False,False,False,False,False,False,False,False,False

Diviser les PrimaryName

In [39]:
# encodage + tranformation en booléen
data_primaryName = fusion_final["primaryName"].str.get_dummies(sep=',').astype(bool) 
data_primaryName

,'Ganja' Karuppu,'University' Jeevan,A Martinez,A. Michael Baldwin,A. Venkatesh,A.J. Buckley,A.J. Simmons,A.K. Hangal,A.T.M. Shamsuzzaman,A.V.M. Rajan,...,Øyvind B. Fabricius Holm,Øyvind Hagen-Traberg,Øyvind Thoen,Ülkü Özen,Ümmü Putgül,Ünal Gürel,Üstün Asutay,Þorsteinn Bachmann,Þröstur Leó Gunnarsson,Þórhallur Sigurðsson
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13089,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
13090,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
13091,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
13092,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
13093,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [40]:
# on concat sur les colonnes le data_primaryName avec le data_diviser sans la colonne "primaryName"
data_diviser = pd.concat([data_diviser.drop(columns="primaryName"), data_primaryName ], axis=1)
data_diviser

,tconst,titleType,primaryTitle,originalTitle,startYear,runtimeMinutes,French_Title,averageRating,numVotes,Action,...,Øyvind B. Fabricius Holm,Øyvind Hagen-Traberg,Øyvind Thoen,Ülkü Özen,Ümmü Putgül,Ünal Gürel,Üstün Asutay,Þorsteinn Bachmann,Þröstur Leó Gunnarsson,Þórhallur Sigurðsson
0,tt0003883,movie,L'enfant de Paris (1913),L'enfant de Paris (1913),1913,124.0,L'Enfant de Paris (1913),7.2,446.0,False,...,False,False,False,False,False,False,False,False,False,False
1,tt0006206,movie,Les vampires (1915),Les vampires (1915),1915,421.0,Les vampires (1915),7.3,5398.0,True,...,False,False,False,False,False,False,False,False,False,False
2,tt0006864,movie,Intolerance (1916),Intolerance: Love's Struggle Throughout the Ag...,1916,163.0,Intolérance (1916),7.7,16642.0,False,...,False,False,False,False,False,False,False,False,False,False
3,tt0006886,movie,Judex (1916),Judex (1916),1916,300.0,Judex (1916),7.2,1117.0,False,...,False,False,False,False,False,False,False,False,False,False
4,tt0009968,movie,Broken Blossoms (1919),Broken Blossoms or The Yellow Man and the Girl...,1919,90.0,Le lys brisé (1919),7.2,11014.0,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13089,tt9900782,movie,Kaithi (2019),Kaithi (2019),2019,145.0,Kaithi (2019),8.4,42096.0,True,...,False,False,False,False,False,False,False,False,False,False
13090,tt9904844,movie,Ott Tänak: The Movie (2019),Ott Tänak: The Movie (2019),2019,125.0,NaN,8.1,501.0,False,...,False,False,False,False,False,False,False,False,False,False
13091,tt9905462,movie,Pengalila (2019),Pengalila (2019),2019,111.0,NaN,7.6,680.0,False,...,False,False,False,False,False,False,False,False,False,False
13092,tt9911196,movie,The Marriage Escape (2020),De beentjes van Sint-Hildegard (2020),2020,103.0,De Beentjes van Sint-Hildegard (2020),7.4,3306.0,False,...,False,False,False,False,False,False,False,False,False,False
13093,tt9911774,movie,Padmavyuhathile Abhimanyu (2019),Padmavyuhathile Abhimanyu (2019),2019,130.0,NaN,8.5,380.0,False,...,False,False,False,False,False,False,False,False,False,False

Diviser les runtimeMinutes

In [41]:
data_runtimeminutes= data_diviser["runtimeMinutes"].astype(str).str.get_dummies(sep=',').astype(bool) 
data_runtimeminutes

,100.0,101.0,102.0,103.0,104.0,105.0,106.0,107.0,108.0,109.0,...,90.0,91.0,92.0,93.0,94.0,95.0,96.0,97.0,98.0,99.0
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,True,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13089,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
13090,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
13091,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
13092,False,False,False,True,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
13093,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [42]:
# on concat sur les colonnes le data_primaryName avec le data_diviser sans la colonne "primaryName"
data_diviser = pd.concat([data_diviser.drop(columns="runtimeMinutes"), data_runtimeminutes ], axis=1)
data_diviser

,tconst,titleType,primaryTitle,originalTitle,startYear,French_Title,averageRating,numVotes,Action,Adult,...,90.0,91.0,92.0,93.0,94.0,95.0,96.0,97.0,98.0,99.0
0,tt0003883,movie,L'enfant de Paris (1913),L'enfant de Paris (1913),1913,L'Enfant de Paris (1913),7.2,446.0,False,False,...,False,False,False,False,False,False,False,False,False,False
1,tt0006206,movie,Les vampires (1915),Les vampires (1915),1915,Les vampires (1915),7.3,5398.0,True,False,...,False,False,False,False,False,False,False,False,False,False
2,tt0006864,movie,Intolerance (1916),Intolerance: Love's Struggle Throughout the Ag...,1916,Intolérance (1916),7.7,16642.0,False,False,...,False,False,False,False,False,False,False,False,False,False
3,tt0006886,movie,Judex (1916),Judex (1916),1916,Judex (1916),7.2,1117.0,False,False,...,False,False,False,False,False,False,False,False,False,False
4,tt0009968,movie,Broken Blossoms (1919),Broken Blossoms or The Yellow Man and the Girl...,1919,Le lys brisé (1919),7.2,11014.0,False,False,...,True,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13089,tt9900782,movie,Kaithi (2019),Kaithi (2019),2019,Kaithi (2019),8.4,42096.0,True,False,...,False,False,False,False,False,False,False,False,False,False
13090,tt9904844,movie,Ott Tänak: The Movie (2019),Ott Tänak: The Movie (2019),2019,NaN,8.1,501.0,False,False,...,False,False,False,False,False,False,False,False,False,False
13091,tt9905462,movie,Pengalila (2019),Pengalila (2019),2019,NaN,7.6,680.0,False,False,...,False,False,False,False,False,False,False,False,False,False
13092,tt9911196,movie,The Marriage Escape (2020),De beentjes van Sint-Hildegard (2020),2020,De Beentjes van Sint-Hildegard (2020),7.4,3306.0,False,False,...,False,False,False,False,False,False,False,False,False,False
13093,tt9911774,movie,Padmavyuhathile Abhimanyu (2019),Padmavyuhathile Abhimanyu (2019),2019,NaN,8.5,380.0,False,False,...,False,False,False,False,False,False,False,False,False,False

# Diviser les Startyear

In [43]:
# encodage + tranformation en booléen  en convertissant en string car get dummies est une methode en string
data_startyear = data_diviser["startYear"].astype(str).str.get_dummies(sep=',').astype(bool) 
data_startyear

,1913,1915,1916,1919,1920,1921,1922,1923,1924,1925,...,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
0,True,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,True,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,True,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,True,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,True,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13089,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,True,False,False,False,False,False
13090,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,True,False,False,False,False,False
13091,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,True,False,False,False,False,False
13092,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,True,False,False,False,False
13093,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,True,False,False,False,False,False

In [44]:
# on concat sur les colonnes le data_primaryName avec le data_dummies sans la colonne "startYear"
data_diviser = pd.concat([data_diviser, data_startyear ], axis=1)
data_diviser

,tconst,titleType,primaryTitle,originalTitle,startYear,French_Title,averageRating,numVotes,Action,Adult,...,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
0,tt0003883,movie,L'enfant de Paris (1913),L'enfant de Paris (1913),1913,L'Enfant de Paris (1913),7.2,446.0,False,False,...,False,False,False,False,False,False,False,False,False,False
1,tt0006206,movie,Les vampires (1915),Les vampires (1915),1915,Les vampires (1915),7.3,5398.0,True,False,...,False,False,False,False,False,False,False,False,False,False
2,tt0006864,movie,Intolerance (1916),Intolerance: Love's Struggle Throughout the Ag...,1916,Intolérance (1916),7.7,16642.0,False,False,...,False,False,False,False,False,False,False,False,False,False
3,tt0006886,movie,Judex (1916),Judex (1916),1916,Judex (1916),7.2,1117.0,False,False,...,False,False,False,False,False,False,False,False,False,False
4,tt0009968,movie,Broken Blossoms (1919),Broken Blossoms or The Yellow Man and the Girl...,1919,Le lys brisé (1919),7.2,11014.0,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13089,tt9900782,movie,Kaithi (2019),Kaithi (2019),2019,Kaithi (2019),8.4,42096.0,True,False,...,False,False,False,False,True,False,False,False,False,False
13090,tt9904844,movie,Ott Tänak: The Movie (2019),Ott Tänak: The Movie (2019),2019,NaN,8.1,501.0,False,False,...,False,False,False,False,True,False,False,False,False,False
13091,tt9905462,movie,Pengalila (2019),Pengalila (2019),2019,NaN,7.6,680.0,False,False,...,False,False,False,False,True,False,False,False,False,False
13092,tt9911196,movie,The Marriage Escape (2020),De beentjes van Sint-Hildegard (2020),2020,De Beentjes van Sint-Hildegard (2020),7.4,3306.0,False,False,...,False,False,False,False,False,True,False,False,False,False
13093,tt9911774,movie,Padmavyuhathile Abhimanyu (2019),Padmavyuhathile Abhimanyu (2019),2019,NaN,8.5,380.0,False,False,...,False,False,False,False,True,False,False,False,False,False

# FICHIER avec tous les acteurs

In [45]:
data_diviser.to_pickle(r"C:\Users\user\Downloads\Projet ML\Model1(KNN)\Données nettoyées\data_machine_learning.pkl.gz", compression = "gzip")
data_machine_learning = pd.read_pickle(r"C:\Users\user\Downloads\Projet ML\Model1(KNN)\Données nettoyées\data_machine_learning.pkl.gz")
data_machine_learning

,tconst,titleType,primaryTitle,originalTitle,startYear,French_Title,averageRating,numVotes,Action,Adult,...,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
0,tt0003883,movie,L'enfant de Paris (1913),L'enfant de Paris (1913),1913,L'Enfant de Paris (1913),7.2,446.0,False,False,...,False,False,False,False,False,False,False,False,False,False
1,tt0006206,movie,Les vampires (1915),Les vampires (1915),1915,Les vampires (1915),7.3,5398.0,True,False,...,False,False,False,False,False,False,False,False,False,False
2,tt0006864,movie,Intolerance (1916),Intolerance: Love's Struggle Throughout the Ag...,1916,Intolérance (1916),7.7,16642.0,False,False,...,False,False,False,False,False,False,False,False,False,False
3,tt0006886,movie,Judex (1916),Judex (1916),1916,Judex (1916),7.2,1117.0,False,False,...,False,False,False,False,False,False,False,False,False,False
4,tt0009968,movie,Broken Blossoms (1919),Broken Blossoms or The Yellow Man and the Girl...,1919,Le lys brisé (1919),7.2,11014.0,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13089,tt9900782,movie,Kaithi (2019),Kaithi (2019),2019,Kaithi (2019),8.4,42096.0,True,False,...,False,False,False,False,True,False,False,False,False,False
13090,tt9904844,movie,Ott Tänak: The Movie (2019),Ott Tänak: The Movie (2019),2019,NaN,8.1,501.0,False,False,...,False,False,False,False,True,False,False,False,False,False
13091,tt9905462,movie,Pengalila (2019),Pengalila (2019),2019,NaN,7.6,680.0,False,False,...,False,False,False,False,True,False,False,False,False,False
13092,tt9911196,movie,The Marriage Escape (2020),De beentjes van Sint-Hildegard (2020),2020,De Beentjes van Sint-Hildegard (2020),7.4,3306.0,False,False,...,False,False,False,False,False,True,False,False,False,False
13093,tt9911774,movie,Padmavyuhathile Abhimanyu (2019),Padmavyuhathile Abhimanyu (2019),2019,NaN,8.5,380.0,False,False,...,False,False,False,False,True,False,False,False,False,False

# FICHIER en retirant les acteurs qui ont fait seulement 1 film

In [46]:
somme = data_machine_learning.iloc[:,8:].sum()
somme

Action       1514
Adult           1
Adventure    1039
Animation     485
Biography    1230
             ...
2020          262
2021          360
2022          440
2023          476
2024           95
Length: 22863, dtype: int64

In [47]:
somme2 = somme[somme <2]
somme2

Adult                  1
Reality-TV             1
Talk-Show              1
'Ganja' Karuppu        1
'University' Jeevan    1
                      ..
607.0                  1
625.0                  1
746.0                  1
1913                   1
1915                   1
Length: 15489, dtype: int64

In [48]:
liste_nom = somme2.index.tolist()
data_machine_learning_clean = data_machine_learning.copy()
data_machine_learning_clean = data_machine_learning_clean.drop(columns = liste_nom)
data_machine_learning_clean

,tconst,titleType,primaryTitle,originalTitle,startYear,French_Title,averageRating,numVotes,Action,Adventure,...,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
0,tt0003883,movie,L'enfant de Paris (1913),L'enfant de Paris (1913),1913,L'Enfant de Paris (1913),7.2,446.0,False,False,...,False,False,False,False,False,False,False,False,False,False
1,tt0006206,movie,Les vampires (1915),Les vampires (1915),1915,Les vampires (1915),7.3,5398.0,True,True,...,False,False,False,False,False,False,False,False,False,False
2,tt0006864,movie,Intolerance (1916),Intolerance: Love's Struggle Throughout the Ag...,1916,Intolérance (1916),7.7,16642.0,False,False,...,False,False,False,False,False,False,False,False,False,False
3,tt0006886,movie,Judex (1916),Judex (1916),1916,Judex (1916),7.2,1117.0,False,True,...,False,False,False,False,False,False,False,False,False,False
4,tt0009968,movie,Broken Blossoms (1919),Broken Blossoms or The Yellow Man and the Girl...,1919,Le lys brisé (1919),7.2,11014.0,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13089,tt9900782,movie,Kaithi (2019),Kaithi (2019),2019,Kaithi (2019),8.4,42096.0,True,False,...,False,False,False,False,True,False,False,False,False,False
13090,tt9904844,movie,Ott Tänak: The Movie (2019),Ott Tänak: The Movie (2019),2019,NaN,8.1,501.0,False,False,...,False,False,False,False,True,False,False,False,False,False
13091,tt9905462,movie,Pengalila (2019),Pengalila (2019),2019,NaN,7.6,680.0,False,False,...,False,False,False,False,True,False,False,False,False,False
13092,tt9911196,movie,The Marriage Escape (2020),De beentjes van Sint-Hildegard (2020),2020,De Beentjes van Sint-Hildegard (2020),7.4,3306.0,False,False,...,False,False,False,False,False,True,False,False,False,False
13093,tt9911774,movie,Padmavyuhathile Abhimanyu (2019),Padmavyuhathile Abhimanyu (2019),2019,NaN,8.5,380.0,False,False,...,False,False,False,False,True,False,False,False,False,False

In [49]:
#Enregistrer au format pickle
data_machine_learning_clean.to_pickle(r"C:\Users\user\Downloads\Projet ML\Model1(KNN)\Données nettoyées\data_machine_learning_clean.pkl.gz", compression = "gzip")
data_machine_learning_clean = pd.read_pickle(r"C:\Users\user\Downloads\Projet ML\Model1(KNN)\Données nettoyées\data_machine_learning_clean.pkl.gz")
data_machine_learning_clean

,tconst,titleType,primaryTitle,originalTitle,startYear,French_Title,averageRating,numVotes,Action,Adventure,...,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
0,tt0003883,movie,L'enfant de Paris (1913),L'enfant de Paris (1913),1913,L'Enfant de Paris (1913),7.2,446.0,False,False,...,False,False,False,False,False,False,False,False,False,False
1,tt0006206,movie,Les vampires (1915),Les vampires (1915),1915,Les vampires (1915),7.3,5398.0,True,True,...,False,False,False,False,False,False,False,False,False,False
2,tt0006864,movie,Intolerance (1916),Intolerance: Love's Struggle Throughout the Ag...,1916,Intolérance (1916),7.7,16642.0,False,False,...,False,False,False,False,False,False,False,False,False,False
3,tt0006886,movie,Judex (1916),Judex (1916),1916,Judex (1916),7.2,1117.0,False,True,...,False,False,False,False,False,False,False,False,False,False
4,tt0009968,movie,Broken Blossoms (1919),Broken Blossoms or The Yellow Man and the Girl...,1919,Le lys brisé (1919),7.2,11014.0,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13089,tt9900782,movie,Kaithi (2019),Kaithi (2019),2019,Kaithi (2019),8.4,42096.0,True,False,...,False,False,False,False,True,False,False,False,False,False
13090,tt9904844,movie,Ott Tänak: The Movie (2019),Ott Tänak: The Movie (2019),2019,NaN,8.1,501.0,False,False,...,False,False,False,False,True,False,False,False,False,False
13091,tt9905462,movie,Pengalila (2019),Pengalila (2019),2019,NaN,7.6,680.0,False,False,...,False,False,False,False,True,False,False,False,False,False
13092,tt9911196,movie,The Marriage Escape (2020),De beentjes van Sint-Hildegard (2020),2020,De Beentjes van Sint-Hildegard (2020),7.4,3306.0,False,False,...,False,False,False,False,False,True,False,False,False,False
13093,tt9911774,movie,Padmavyuhathile Abhimanyu (2019),Padmavyuhathile Abhimanyu (2019),2019,NaN,8.5,380.0,False,False,...,False,False,False,False,True,False,False,False,False,False

In [50]:
data_machine_learning_clean[data_machine_learning_clean["Mohanlal"]==True]

,tconst,titleType,primaryTitle,originalTitle,startYear,French_Title,averageRating,numVotes,Action,Adventure,...,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
3546,tt0092507,movie,Abhimanyu (1991),Abhimanyu (1991),1991,NaN,7.3,436.0,False,False,...,False,False,False,False,False,False,False,False,False,False
4533,tt0119385,movie,Iruvar (1997),Iruvar (1997),1997,NaN,8.4,7293.0,False,False,...,False,False,False,False,False,False,False,False,False,False
4736,tt0133826,movie,Guru (1997),Guru (1997),1997,NaN,8.5,3479.0,False,False,...,False,False,False,False,False,False,False,False,False,False
4887,tt0156130,movie,Thazhvaram (1990),Thazhvaram (1990),1990,NaN,8.2,792.0,False,False,...,False,False,False,False,False,False,False,False,False,False
5224,tt0202055,movie,Vanaprastham (1999),Vanaprastham (1999),1999,Vanaprastham - La dernière danse (1999),8.1,1910.0,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11439,tt4471488,movie,Mythri (2015),Mythri (2015),2015,NaN,7.3,383.0,False,False,...,True,False,False,False,False,False,False,False,False,False
11836,tt5548032,movie,Oppam (2016),Oppam (2016),2016,NaN,7.3,4346.0,True,False,...,False,True,False,False,False,False,False,False,False,False
11985,tt5946852,movie,Janatha Garage (2016),Janatha Garage (2016),2016,NaN,7.2,8022.0,True,False,...,False,True,False,False,False,False,False,False,False,False
11986,tt5948916,movie,All of Us (2016),Manamantha (2016),2016,NaN,7.5,1030.0,False,False,...,False,True,False,False,False,False,False,False,False,False
12028,tt6067752,movie,Lucifer (2019),Lucifer (2019),2019,NaN,7.5,12417.0,True,False,...,False,False,False,False,True,False,False,False,False,False