In [11]:
import pandas as pd
import plotly.express as px

In [12]:
fusion_titlebasic_titlerating =pd.read_csv(r"C:\Users\user\Downloads\Projet ML\Model1(KNN)\Données nettoyées\fusion_titlebasic_titlerating.csv", sep = ",")
data_title_principal_nettoye = pd.read_csv(r"C:\Users\user\Downloads\Projet ML\Model1(KNN)\Données nettoyées\data_title_principal_nettoye.csv", sep = ",")
data_name_basics_purify = pd.read_csv(r"C:\Users\user\Downloads\Projet ML\Model1(KNN)\Données nettoyées\data_name_basics_purify.csv", sep = ",")

In [13]:
fusion_namebasic_titleprincipal = pd.merge(data_title_principal_nettoye, data_name_basics_purify, 
         how="left",     
         left_on='nconst',
         right_on='nconst')

In [14]:
viz=pd.merge(fusion_titlebasic_titlerating, fusion_namebasic_titleprincipal, 
         how="left",     
         left_on='tconst',
         right_on='tconst')

In [15]:
viz

,tconst,titleType,primaryTitle,originalTitle,startYear,runtimeMinutes,genres,Unnamed: 0,French_Title,averageRating,numVotes,nconst,category,characters,primaryName,primaryProfession,knownForTitles
0,tt0003883,movie,L'enfant de Paris,L'enfant de Paris,1913,124.0,"Crime,Drama",11535.0,L'Enfant de Paris,7.2,446.0,nm0494137,actress,NaN,Suzanne Le Bret,actress,"tt0319773,tt0436541,tt0006206,tt0438178"
1,tt0003883,movie,L'enfant de Paris,L'enfant de Paris,1913,124.0,"Crime,Drama",11535.0,L'Enfant de Paris,7.2,446.0,nm0674600,actor,"[""Léonce""]",Léonce Perret,"director,actor,writer","tt0438177,tt0003883,tt0319773,tt0009858"
2,tt0003883,movie,L'enfant de Paris,L'enfant de Paris,1913,124.0,"Crime,Drama",11535.0,L'Enfant de Paris,7.2,446.0,nm0504864,actor,"[""Edmond Le Bachelier""]",Louis Leubas,actor,"tt2746744,tt0006206,tt2122393,tt2122389"
3,tt0003883,movie,L'enfant de Paris,L'enfant de Paris,1913,124.0,"Crime,Drama",11535.0,L'Enfant de Paris,7.2,446.0,nm0481419,actor,"[""Le Bosco""]",Maurice Lagrenée,"actor,director","tt0193092,tt0158769,tt0494577,tt0213910"
4,tt0003883,movie,L'enfant de Paris,L'enfant de Paris,1913,124.0,"Crime,Drama",11535.0,L'Enfant de Paris,7.2,446.0,nm0449136,actor,"[""Pierre de Valen""]",Émile Keppens,"actor,director","tt0139366,tt0923839,tt0443196,tt3141508"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59366,tt9911774,movie,Padmavyuhathile Abhimanyu,Padmavyuhathile Abhimanyu,2019,130.0,Drama,NaN,NaN,8.5,380.0,nm15311055,actor,"[""Abhimanyu""]",NaN,NaN,NaN
59367,tt9911774,movie,Padmavyuhathile Abhimanyu,Padmavyuhathile Abhimanyu,2019,130.0,Drama,NaN,NaN,8.5,380.0,nm2649680,actor,NaN,Anoop Chandran,"actor,music_department,producer","tt0867145,tt1028558,tt9244322,tt2429086"
59368,tt9911774,movie,Padmavyuhathile Abhimanyu,Padmavyuhathile Abhimanyu,2019,130.0,Drama,NaN,NaN,8.5,380.0,nm1428724,actor,NaN,Indrans,"actor,costume_designer,music_department","tt10534500,tt3951566,tt9006564,tt8066304"
59369,tt9911774,movie,Padmavyuhathile Abhimanyu,Padmavyuhathile Abhimanyu,2019,130.0,Drama,NaN,NaN,8.5,380.0,nm1381069,actress,NaN,Sona Nair,"actress,music_department","tt0407273,tt0972913,tt0273115,tt1034393"
59370,tt9911774,movie,Padmavyuhathile Abhimanyu,Padmavyuhathile Abhimanyu,2019,130.0,Drama,NaN,NaN,8.5,380.0,nm10536451,director,NaN,Vineesh Aaradya,"writer,director",tt9911774

In [16]:
viz=viz.drop(['titleType','Unnamed: 0','characters'],axis=1)
viz

,tconst,primaryTitle,originalTitle,startYear,runtimeMinutes,genres,French_Title,averageRating,numVotes,nconst,category,primaryName,primaryProfession,knownForTitles
0,tt0003883,L'enfant de Paris,L'enfant de Paris,1913,124.0,"Crime,Drama",L'Enfant de Paris,7.2,446.0,nm0494137,actress,Suzanne Le Bret,actress,"tt0319773,tt0436541,tt0006206,tt0438178"
1,tt0003883,L'enfant de Paris,L'enfant de Paris,1913,124.0,"Crime,Drama",L'Enfant de Paris,7.2,446.0,nm0674600,actor,Léonce Perret,"director,actor,writer","tt0438177,tt0003883,tt0319773,tt0009858"
2,tt0003883,L'enfant de Paris,L'enfant de Paris,1913,124.0,"Crime,Drama",L'Enfant de Paris,7.2,446.0,nm0504864,actor,Louis Leubas,actor,"tt2746744,tt0006206,tt2122393,tt2122389"
3,tt0003883,L'enfant de Paris,L'enfant de Paris,1913,124.0,"Crime,Drama",L'Enfant de Paris,7.2,446.0,nm0481419,actor,Maurice Lagrenée,"actor,director","tt0193092,tt0158769,tt0494577,tt0213910"
4,tt0003883,L'enfant de Paris,L'enfant de Paris,1913,124.0,"Crime,Drama",L'Enfant de Paris,7.2,446.0,nm0449136,actor,Émile Keppens,"actor,director","tt0139366,tt0923839,tt0443196,tt3141508"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59366,tt9911774,Padmavyuhathile Abhimanyu,Padmavyuhathile Abhimanyu,2019,130.0,Drama,NaN,8.5,380.0,nm15311055,actor,NaN,NaN,NaN
59367,tt9911774,Padmavyuhathile Abhimanyu,Padmavyuhathile Abhimanyu,2019,130.0,Drama,NaN,8.5,380.0,nm2649680,actor,Anoop Chandran,"actor,music_department,producer","tt0867145,tt1028558,tt9244322,tt2429086"
59368,tt9911774,Padmavyuhathile Abhimanyu,Padmavyuhathile Abhimanyu,2019,130.0,Drama,NaN,8.5,380.0,nm1428724,actor,Indrans,"actor,costume_designer,music_department","tt10534500,tt3951566,tt9006564,tt8066304"
59369,tt9911774,Padmavyuhathile Abhimanyu,Padmavyuhathile Abhimanyu,2019,130.0,Drama,NaN,8.5,380.0,nm1381069,actress,Sona Nair,"actress,music_department","tt0407273,tt0972913,tt0273115,tt1034393"
59370,tt9911774,Padmavyuhathile Abhimanyu,Padmavyuhathile Abhimanyu,2019,130.0,Drama,NaN,8.5,380.0,nm10536451,director,Vineesh Aaradya,"writer,director",tt9911774

In [17]:
viz.to_csv(r"C:\Users\user\Downloads\Projet ML\Visualisation.csv")

In [18]:
#Les cinq genres les plus representés
top5_genres = viz.groupby(['genres']).count().reset_index().sort_values(by = "tconst" , ascending = False)[:5]
top5_genres

,genres,tconst,primaryTitle,originalTitle,startYear,runtimeMinutes,French_Title,averageRating,numVotes,nconst,category,primaryName,primaryProfession,knownForTitles
392,Drama,9957,9957,9957,9957,9957,5590,9957,9957,9957,9957,9922,9922,9922
452,"Drama,Romance",3569,3569,3569,3569,3569,2356,3569,3569,3569,3569,3557,3557,3557
252,"Comedy,Drama",3432,3432,3432,3432,3432,1911,3432,3432,3432,3432,3416,3416,3416
229,Comedy,1997,1997,1997,1997,1997,624,1997,1997,1993,1993,1981,1981,1981
260,"Comedy,Drama,Romance",1970,1970,1970,1970,1970,1280,1970,1970,1970,1970,1963,1963,1963

In [21]:
fig= px.pie(top5_genres, values="tconst", names = "genres", title = "Top 5 genres", hover_data=["genres"], labels = {"tconst" : " Total"} )
fig.show()

In [22]:
#Nombre de film par an
data_nblignes_per_year = viz.groupby(by="startYear").count().reset_index()
data_nblignes_per_year

,startYear,tconst,primaryTitle,originalTitle,runtimeMinutes,genres,French_Title,averageRating,numVotes,nconst,category,primaryName,primaryProfession,knownForTitles
0,1913,8,8,8,8,8,8,8,8,8,8,8,8,8
1,1915,7,7,7,7,7,7,7,7,7,7,7,7,7
2,1916,10,10,10,10,10,10,10,10,10,10,10,10,10
3,1919,21,21,21,21,21,13,21,21,21,21,14,14,14
4,1920,10,10,10,10,10,10,10,10,10,10,10,10,10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
104,2020,960,960,960,960,960,476,960,960,957,957,912,912,912
105,2021,1484,1484,1484,1484,1484,683,1484,1484,1476,1476,1448,1448,1448
106,2022,1970,1970,1970,1970,1970,806,1970,1970,1968,1968,1915,1915,1915
107,2023,2292,2292,2292,2292,2292,828,2292,2292,2288,2288,2229,2229,2229
108,2024,462,462,462,462,462,124,462,462,459,459,454,454,454

In [23]:
data_nb_films_per_year = viz.groupby(["startYear","tconst"]).count().reset_index()

data_nb_films_per_year_1 = data_nb_films_per_year.groupby(["startYear"]).count().reset_index()

In [25]:
data_nb_films_per_year

,startYear,tconst,primaryTitle,originalTitle,runtimeMinutes,genres,French_Title,averageRating,numVotes,nconst,category,primaryName,primaryProfession,knownForTitles
0,1913,tt0003883,8,8,8,8,8,8,8,8,8,8,8,8
1,1915,tt0006206,7,7,7,7,7,7,7,7,7,7,7,7
2,1916,tt0006864,5,5,5,5,5,5,5,5,5,5,5,5
3,1916,tt0006886,5,5,5,5,5,5,5,5,5,5,5,5
4,1919,tt0009968,8,8,8,8,8,8,8,8,8,8,8,8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12317,2024,tt31410930,6,6,6,6,6,6,6,6,6,5,5,5
12318,2024,tt31410956,5,5,5,5,0,5,5,5,5,5,5,5
12319,2024,tt31414473,5,5,5,5,0,5,5,5,5,5,5,5
12320,2024,tt31435295,5,5,5,5,0,5,5,5,5,5,5,5
12321,2024,tt4996328,5,5,5,5,5,5,5,5,5,5,5,5

In [26]:
fig1 = px.bar(data_nb_films_per_year_1, x = "startYear", y= "primaryTitle", title = "Nombre de films par an" )
fig1.update_xaxes(title="Années") 
fig1.update_yaxes(title="Nombre de films")
fig1.show()